### ISSUE TITLE
Make wikis stable 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#10]
- [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/7
- [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/8
- [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/9
- [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/11
- [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/12
- [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/13
- [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/14
- [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/15

**Comment by andrewayoub** [comment]
waiting for #15 content missing

**Comment by AhmedHanafy725** [comment]
I think wikis are now stable and it is checked with every commit in #91
