### ISSUE TITLE
As a user initialize 3bot 

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/jumpscaleX_threebot#100]
This document replaces [old spec](https://github.com/threefoldfoundation/info_3bot/blob/master/specs/initialize.md)

**Assumptions**
* Will be added in interface package
* A user can enter a country
* Some users did not write down their mnenonic phrase, we will check it
* On starting the 3bot, we will pass the 3bot name so the user can login again and the code can verify its owner. 3bot is started by a bootstrap 3bot.
* The default wallet keys will be added to the 3bot by redirecting to the existing wallet and back.
**Flow**
![image](https://user-images.githubusercontent.com/1687505/67080724-1a4aaa00-f196-11e9-9658-faa8bc5d7cb9.png)

**Mockups**

![image](https://user-images.githubusercontent.com/1687505/67080040-a4920e80-f194-11e9-87ed-9b1e57fc76c7.png)

**More info**
When initializing a 3bot we need to be sure that the user using it is the owner. Therefore the user will be redirected to login.

After login, the user will be able to set it's location, add a referred by name (which can be checked on existence using login.threefold.me API). 

We will also ask for the users seed. This has two reasons
- We need to know the user effectively has written it down before adding him to the phonebook
- We need the wallet derivative keys

The wallet keys will be stored in the 3bot, the root keys will NOT. They will be disposed after derivation and checking the public key of the user.

**API**

Following API's will be needed:
/api/3bot/initialize #we should check this URL
```json
{
"location" : { "country" : "Belgium"},
"wallet_key": { "sk" : "mylongsecretkey", "pk" : "mylongpubkey")
}
```

**Comment by jdelrue** [comment]
TODO:
- API URL should be actor but probably in an initialization package? Or general 3bot package?
- Where to send referred by? What do you get for referring? I know this was a question x months ago but is it still?

**Comment by MathiasDeWeerdt** [comment]
Todo: 
- API to retrieve double-name.
- API to retrieve whether the 3bot has been initialized. We could do this in the initialization package itself. 
- Generate derived key-set if the double-name has been verified. 
- Call the re-encryption API that still has to be exposed. 

Call with: 
@zaibon 
@serboctor
