### ISSUE TITLE
self signed problem on chrome

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#101]
![image](https://user-images.githubusercontent.com/64129/67123527-d46eff80-f1f0-11e9-855d-aac5e7411508.png)

no option to ignore or continue

**Comment by andrewayoub** [comment]
Can't reproduce this, I think it's an outdated issue

**Comment by xmonader** [comment]
now that we decided to have 80 served as well, not an issue anymore in development.
