### ISSUE TITLE
allow http on development

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#102]
because of #101 either that or we have a fully working flow without browsers security measures.

**Comment by xmonader** [comment]
I've wiki, chat running on 80 as well for now. until we figure out a clean solution.

**Comment by xmonader** [comment]
chat, gedis, wikis both running on 80, 443 now

**Comment by hossnys** [comment]
http and https is working fine for now on chat and wikis
![Screenshot from 2019-11-03 13-41-23](https://user-images.githubusercontent.com/26298009/68084520-5ee56f00-fe3f-11e9-8bd1-66eaf7da1fd8.png)
![Screenshot from 2019-11-03 13-42-26](https://user-images.githubusercontent.com/26298009/68084521-5ee56f00-fe3f-11e9-9976-d96ae17150b1.png)
![Screenshot from 2019-11-03 13-43-15](https://user-images.githubusercontent.com/26298009/68084526-79b7e380-fe3f-11e9-92ab-4d3a67d8e8d3.png)
