### ISSUE TITLE
wiki directory doesn't get registered

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#104]
Packages should allow having `wiki` dir as we do with `actors`, `models` dirs. and the wiki should be loaded on package start

https://github.com/threefoldtech/jumpscaleX_core/blob/fbdf396c866e841c6cf797f11d2b4a9929306a3b/JumpscaleCore/core/BASECLASSES/ThreeBotPackageBase.py#L76

**Comment by abom** [comment]
Waiting until we decide how to schedule wikis loading of all packages, a discussion about starting myjobs package by default #131.

**Comment by abom** [comment]
Now myjobs package start by default, so we can just schedule loading the wiki

https://github.com/threefoldtech/jumpscaleX_core/commit/780b4e2c82c8f0c80695dcf3bf8f30095f221507

**Comment by Pishoy** [comment]
verified 
```
mkdir -p /sandbox/bishoy/wiki
cd  /sandbox/bishoy/wiki
cp /sandbox/code/github/threefoldtech/jumpscaleX_threebot/docs/wikis/examples/* -r .
vim  /sandbox/bishoy/package.py
kosmos 
JSX> cl = j.servers.threebot.local_start_default() 
cl.actors.package_manager.package_add(path="/sandbox/bishoy")
```
check http://<IP>/wiki/bishoy

- js version 
```
3BOTDEVEL:jsx:jumpscaleX_threebot: git log -1
commit a4be009f84a9ae8b99445185d00ac667e09c9c79 (HEAD -> development, origin/development, origin/HEAD)
Author: Ahmed T. Youssef <xmonader@gmail.com>
Date:   Mon Nov 4 10:07:48 2019 +0200

    update landing page
```
