### ISSUE TITLE
install graphviz when starting threebot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#106]
it's needed in our dot macro test page. doesn't make sense to have without being able to show it!

**Comment by waleedhammam** [comment]
added in the wiki prepare method: https://github.com/threefoldtech/jumpscaleX_threebot/commit/6898b9427990d532b3db7b0ddc940950a8f796fd

**Comment by siddiquagig** [comment]
Verified.

Graphviz is now there.
