### ISSUE TITLE
always start wiki, chat, webinterface packages

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#108]

**Comment by AhmedHanafy725** [comment]
**Verified**
#### For wiki and chat:
wikis and chatbot are loaded once server is started.
![image](https://user-images.githubusercontent.com/41957921/67399418-84a38600-f5ac-11e9-96f4-1997b4508a7f.png)

#### webinterface:
bcdbfs, gedis http and gedis websocket tests are passing
![image](https://user-images.githubusercontent.com/41957921/67399793-0abfcc80-f5ad-11e9-83f0-a3686f957452.png)
