### ISSUE TITLE
FR: oauth over chatflows

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#109]
Support oauth for /chat route with
- github
- facebook
- linkedin?

**Comment by xmonader** [comment]
despiegk's idea: for the application ids required maybe we can have `oauth.threefold.io` that we ask to do authorization and redirection to certain 3bot?

**Comment by alichaddad** [comment]
Current progress: Code complete, still some testing on actual infrastructure that needs to be done.

**Comment by hossnys** [comment]
verified 
steps : 
1- make sure that wireguard is installed on your docker and host. 
2- then start kosmos and start threebot server and add registration package
```
cl = j.servers.threebot.local_start_default()
cl.actors.package_manager.package_add("/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/registration") 
 cl.reload() 
cl.actors.registration.register('samir.hosny', 'samir@incubaid.com', "")

```
3- visit the link you added like https://samir.hosny.3bot.testnet.grid.tf/chat
it will redirect you to login then ask for authorize  and you will see your github user on top right of screen.

![Screenshot from 2019-10-30 10-07-48](https://user-images.githubusercontent.com/26298009/67840481-acd83b00-fafe-11e9-89fb-5027cd68edf2.png)
