### ISSUE TITLE
Wrong github url in wikis

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#11]
![image](https://user-images.githubusercontent.com/24386802/64346101-d0e13980-cff1-11e9-9238-aab42a4559aa.png)

## Steps 
- Click  on github sign will direct you to wrong url as shown 
https://github.com/threefoldfoundation/foundation
![image](https://user-images.githubusercontent.com/24386802/64346428-67adf600-cff2-11e9-88fe-5d2adc2a0b06.png)

**Comment by waleedhammam** [comment]
fix links  in wikis: https://github.com/threefoldtech/jumpscaleX_threebot/commit/052e5d0691b8891ddc26717969d07f6e36953c21

**Comment by Dinaamagdy** [comment]
works in 
jumpscalex_core : 79a930098d114fbf43c98c5d5525d0ed7b599f98
jumpscalex_libs : development
jumpsccalex_threeboot: development
