### ISSUE TITLE
always cleanup nginx locations on start

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#110]
- when threebot start it needs to clear all locations
- keep letsencrypt location on website 80 (or regenerate it no problem)

**Comment by 0xIslamTaha** [comment]
steps:
- Start any threebot package as an example `j.threebot.package.calendar.start()`
- Change the package default names as an example change "calendar" to "xyz" in `sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/calendar/package.py`
- Stop the running pakcage.
- Start it again
- check that `ls /sandbox/cfg/nginx/default_openresty_threebot/servers/website_443_locations/` doesnt have `calendar` but `xyz` config file.
