### ISSUE TITLE
wiki-reload should reflect only the local changes only

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#111]
all of the git mgmt should be done by the user himself

**Comment by xmonader** [comment]
if there're no local changes will fetch from the remote.

**Comment by hossnys** [comment]
verified : 
steps : 
1- editing any local file in wiki repo , i edited this one for sidebar 
   ```
/sandbox/code/github/threefoldtech/jumpscaleX_threebot/docs/wikis/examples/docs/_sidebar.md
    
```
2-then reload wikis

```  jsx wiki-reload -n examples ```

3- i found my local changes in wiki page 

![Screenshot from 2019-10-23 10-50-18](https://user-images.githubusercontent.com/26298009/67375699-5198cc80-f583-11e9-8002-70a1db35c8e2.png)
