### ISSUE TITLE
chat doesn't show header image

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#114]
![image](https://user-images.githubusercontent.com/64129/67187080-be785f00-f3e9-11e9-8c06-3ad7ed2fa329.png)

**Comment by xmonader** [comment]
fixed here 00211cff31550823ef56e00268aeceb338a8063d problem was in chat/js/scripts.j

**Comment by siddiquagig** [comment]
Verified

![image](https://user-images.githubusercontent.com/25789724/67377432-b3166680-f596-11e9-89c4-bf3b927b636c.png)
