### ISSUE TITLE
As a 3bot FE user, get list of packages

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/jumpscaleX_threebot#116]
As a 3bot FE user, get list of packages

**More info**

When using the 3bot, packages are now hardcoded into the interface. @coeneivan is making a modular system so all packages can be added on-the-fly. For this to work, an actor should exist for the interface to get all the installed packages and the meta data (routes, icon, ...) from the 3bot backend.

**Actors**
GET

**Todo**
- [x] Set package is frontend exposed or not (package_manager)
- [x] Get list of frontend exposed packages (package_manager)

**Comment by zaibon** [comment]
So currently in jumspcale, there is a ThreebotPackage module that is used to track all the package that are installed in  3bot: https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/tools/threebot_package
This module is exposed over on Gedis by default using this actor: https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/threebot/base_actors/package_manager.py

This actor has the following method:
```python
 package_add(self, git_url=None, path=None, reload=True, schema_out=None, user_session=None):
 getname(p):
 package_delete(self, name, schema_out=None, user_session=None):
 package_stop(self, name, schema_out=None, user_session=None):
```

I guess we could update this actor allow to list all the installed package and add the missing information about package that you need in the FE

**Comment by jdelrue** [comment]
I guess we would need like a flag if it is frontend exposed or not, that way a package that is frontend exposed can register itself to
/{packagename}/*

We could then get the info through a convention file like 
/{packagename}/packageinfo.json

**Comment by rkhamis** [comment]
we could, indeed, have a packageinfo.json and add a field in it for frontend.
The list, as I mentioned can be exposed by the package_manager. we can even make the list there take a filter of "frontend-exposed"

**Comment by jdelrue** [comment]
@rkhamis 

so things to be done:
- Expose them through package_manager
- Add field frontend exposed

How do we set the field?

**Comment by rkhamis** [comment]
The creator of the package would add that info in the packageinfo

**Comment by xmonader** [comment]
@rkhamis I think a better solution is to register its name in nginx locations and query nginx locations to find web packages? even we can add a meta property on package object.

**Comment by jdelrue** [comment]
Querying from nginx doesnt seem like the best option, we should just add it to package info so we keep the things separated.

**Comment by jdelrue** [comment]
done @ https://github.com/threefoldtech/jumpscaleX_threebot/issues/162
