### ISSUE TITLE
As a user, manage contacts through vcard

### ISSUE THREAD

**Issue by KristofVanstappen** [threefoldtech/jumpscaleX_threebot#117]
Extend contact package based on iCal/vCard  under /threebotpackages/threebot/contact

As it is stored in BCDB we need to store as existing [models](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threebot/contacts/models/contact_1.toml)

- [ ] Radicale update
   - [ ] Modify the storage of radical to translate to models instead of the local file system check what have been done for [webdav](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threebot/fileserver/webdav/provider.py) 
   - [ ] Modify the existing radical server in jumpscaleX_libs_extra to launch our modified version

- [ ] Deployment
  - [ ] package.py
  - [ ] package factory
  - [ ] start paramaterized 

- [ ] Testing
  - [ ] create/update/delete/get contact

**Comment by rkhamis** [comment]
@KristofVanstappen is this intended to reflect the phonebook changes? or standalone contacts? because it seems to me that this should really be integrated with the phonebook since it's the public registry of all threebots, and these contacts are to be 3bot contacts if I understand correctly?

**Comment by rkhamis** [comment]
@KristofVanstappen also, cardav is already supported in our radicale implementation

**Comment by jdelrue** [comment]
@rkhamis yes we should integrate with phonebook!

**Comment by rkhamis** [comment]
@jdelrue I'll check the current models for our contacts, and where the actors are at, but I don't believe we should have different actors for the phonebook. the phonebook package should be run only on the phonebook node irself to register new 3bot or fetch information about existing ones.

This cardav should then have the model referencing the 3bot double.name or its id in its models

**Comment by jdelrue** [comment]
@rkhamis I think we have some confusion about difference between contacts in the 'contacts package' as the 3bot app and the phonebook

Contacts:
- Phone number
- Email 
- Home address
- ...

Phonebook:
- Public key
- 3bot name
- IP address

**Comment by rkhamis** [comment]
@jdelrue but when we talked earlier today, you said that these contacts will be both, actually.
Which would make a lot more sense

**Comment by gmachtel** [comment]
Created same story in threebotapps : [#4](https://github.com/threebotapps/contacts/issues/4). This one will be closed. Will refer to here not to loose the comments.

**Comment by gmachtel** [comment]
Right place is threebotapps
