### ISSUE TITLE
As a farmer import data

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/jumpscaleX_threebot#121]
As a farmer you should be able to import farm data

**Assumptions**
- Farmer will be created in the central Cockpit 3bot instantion
- Decentralization is out of scope for now
- In the Phonebook or Cockpit, a farmer is not an entity. A user can just own farms. 
- You can click the farmer icon wether you are logged in or not
- All post login functionalities will be done from the 3bot of the user, so most UI stuff here will be implemented and used from 3bot

**More info**

After clicking the farmer icon in the UI
![image](https://user-images.githubusercontent.com/1687505/67004836-77d0ef00-f0e1-11e9-8465-3ce81b37aff4.png)

The user will be redirected to the farming page. If the user does not have a farm yet, it is important that we can get legacy data from his old account.

After that the user will be able to login with his IYO account
![image](https://user-images.githubusercontent.com/1687505/67004545-d6499d80-f0e0-11e9-8031-7c6cb753c485.png)

The data can be pulled from legacy systems using actors [more info here](https://github.com/threefoldtech/jumpscaleX_threebot/issues/23).

Flow in chart:

![image](https://user-images.githubusercontent.com/1687505/67005291-94b9f200-f0e2-11e9-8f9d-9127a3f37d4d.png)

**DOD**
- UI is linked to actors
- Import from IYO is tested and done
- Import is re-asked as long as user has no farms

**TODO**
resource_prices

**Comment by zaibon** [comment]
> @zaibon you got an IYO org so we can test?

https://capacity.threefoldtoken.com/api/farmers/zaibon_farm

> Is this public data or you need a JWT to fetch?

this is public information

**Comment by despiegk** [comment]
I don't believe we need a migration tool,
lets just start from scratch

**Comment by rkhamis** [comment]
> I was working on a migration actor as part of this task. #23
> Where has the discussion reached in regard to threebot_id for migrated farms?

For now, I think we'll import the data to the requesting threebot's id
https://github.com/threefoldtech/jumpscaleX_threebot/issues/142

**Comment by rkhamis** [comment]
> I don't believe we need a migration tool,
> lets just start from scratch

What about all the farms already out there?

**Comment by rkhamis** [comment]
no longer needed
