### ISSUE TITLE
As a user, have pdf version of capacity invoice available

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#124]
downloadable pdf of transactions in admin panel

**Comment by m-motawea** [comment]
### Suggested approach

-  Payment details can be saved in a model locally in bcdb.
- A new section in dashboard can view these details like in a table, click on the table to view the details and has a download as pdf button

**Comment by m-motawea** [comment]
![image](https://user-images.githubusercontent.com/32568986/83393449-16069080-a3f7-11ea-9c55-873c6757e261.png)
![image](https://user-images.githubusercontent.com/32568986/83347925-c2c60c80-a328-11ea-9299-e59955c856d7.png)

**Comment by AhmedHanafy725** [comment]
**Verified**

**Branch:** development
**Commit:** 99a8bf276a12a0d961757768b908910a7244015a

+ By Double clicking on the transaction.

![image](https://user-images.githubusercontent.com/41957921/83639055-6a9e3d00-a5aa-11ea-8065-2a58eb9a5323.png)


+ Transaction details can be downloaded as pdf by clicking on `Export` button.

![image](https://user-images.githubusercontent.com/41957921/83630015-674f8500-a59b-11ea-8554-2e52257de1b8.png)
