### ISSUE TITLE
As a farmer, create a farm

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/jumpscaleX_threebot#125]
As a farmer you should be able to create a farm

**Assumptions**
 most of UI is ready for this

**More info**
![image](https://user-images.githubusercontent.com/1687505/66889481-ec713400-efe2-11e9-86ef-bb1038b2eb51.png)

Before implementation; please add to this issue:
- What will technically happen with this data, what is 'creating a farm'

/farms/put
```json
{
"name": "my farm",
"organizationId" : "myorgid",
wallet_addresses : [ "myWalletaddress" ],
"location" : { "lat" : 51.180303, "long" : 3.209025},
"email", "my@tf.org"
"resource_prices" : {
    "cru" : 1.2,
    "mru" : 1.2,
    "hru" : 1.2,
    "sru" : 1.2,
    "nru" : 1.2
    }
}
```

Walletaddress can be empty which means no payment at the time

**DOD**
- Actors are working and tested
- UI is linked to actors
- Location can be chosen on the map
- Farm is in the farm list

**TODO**
- [ ] ~~resource_prices~~ not needed now
- [x] Add method to directory farms actor to list all farm that belongs to a 3bot ID/double name

**Comment by zaibon** [comment]
@tobiaschielens 
Since we decided to not migrate all farms from the old directory. The organizationID field is not needed anymore, you can remove it from the UI.

Also I notice that we don't ask an email in the creation form, this is on the other hand, required.
So the required fields are:
- name
- wallet_addresses
- location
- email

**Comment by tobiaschielens** [comment]
I added the email. 
Creation of farms and editing of settings is implemented in the front-end.

**Comment by zaibon** [comment]
ok we have the MPV and this is enough for now
https://github.com/threebotapps/farmmanagement/commit/ea646683bc1c21a44f231ae36d295cb99bd07ec7
