### ISSUE TITLE
As a user login [development_userlogin]

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/jumpscaleX_threebot#128]
As a user login

**Assumptions**
- 3bot interface is not accessible without logging into 3bot account
- 3bot login is still not hosted in a 3bot but as central service

**More info**

Before starting up other 3bots, usings (eg also registering farms) each user should be known in the phonebook with it's doublename (.3bot) AND for now login.threefold.me.

When logging into the 3bot, a check should happen (HOW?) to see if the user is indeed known by the phonebook (using phonebook actors).

After login, the 3bot should check if the user is indeed valid by verifying with public key in the phonebook. Valid user session should be kept and verified with each actor call (user session).

**DOD**
- [ ]  Login with cookie when connecting to the Threebot
- [ ]  Sessions will be validated for each actor call

**Comment by zaibon** [comment]
@jdelrue is this issue still relevant. The way we register 3bot now already includes the creation of the phonebook entry and the public key is also update during the 3bot first initialization.

**Comment by despiegk** [comment]
needs to be reviewed
