### ISSUE TITLE
As a user, manage contacts

### ISSUE THREAD

**Issue by KristofVanstappen** [threefoldtech/jumpscaleX_threebot#129]
- [ ] UI on 3bot app
  - [ ] search contacts
  - [ ] birthdate format (also check other dates )
  - [ ] edit contact in popover ( same as create new )
  - [ ] edit popover 
    - [ ] prevent closing form when clicking outside
    - [ ] country dropdown ( now just text )
    - [ ] save button more clear ( maybe on the bottom )
    - [ ] salutation dropdown ( now checkbox ), add text field
    - [ ] add button repeats with each field. remove it.
    - [ ] make blocks more separated ( phone, email, address )
    - [ ] scrollbar is not sexy

- [ ] actors
  - [ ] rework upload contact picture ( big pictures not possible now ) - this needs filestorage package! @jdelrue

**Comment by gmachtel** [comment]
moved to threebotapps repository
