### ISSUE TITLE
myjobs package should be registered by default

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_threebot#131]
We need for example to load wiki in background, and we don't want every package to start myjobs on its own.

**Comment by abom** [comment]
@grimpy @andrewayoub

**Comment by abom** [comment]
Made myjobs package start by default with threebot server.

https://github.com/threefoldtech/jumpscaleX_core/commit/780b4e2c82c8f0c80695dcf3bf8f30095f221507

**Comment by hossnys** [comment]
verified :
myjobs package start now by default when you start threebot server.
![Screenshot from 2019-11-03 08-49-05](https://user-images.githubusercontent.com/26298009/68081726-4c593e80-fe1b-11e9-8035-29720d2c327c.png)
![Screenshot from 2019-11-03 09-16-28](https://user-images.githubusercontent.com/26298009/68081732-63982c00-fe1b-11e9-825e-2fafe0425f90.png)
