### ISSUE TITLE
As a consumer, start predefined appliance  

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#136]
As a consumer you should be able to install predefined apps (Ubuntu, Odoo, ...)

!need list of appliances!!
**Assumptions**
 most of UI is ready for this

**More info**
Before implementation; please add to this issue:
- ...

- start and stop solution ( technically like a  package)
- solution will be started with solution actor 
- types: url for creation (is this a flist?); actor to ask for the list and delete solution

Actors:
GET list of installed solutions
GET list of installable solutions
POST start instance of solution

- a wiki for every solution with install instructions etc
- a chatbot will be used to effectively start solution

**DOD**
- Actors are working and tested
- UI is linked to actors

**TODO**

**Comment by rkhamis** [comment]
Verified flists to be moved under: https://hub.grid.tf/tf-appliances

Actor: https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/threefold/tfgrid_workloads (same flow described in https://github.com/threefoldtech/jumpscaleX_threebot/issues/120)
