### ISSUE TITLE
link macro doesn't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#14]
```
!!!include
link = "https://github.com/threefoldtech/rivine/blob/master/doc/whitepaper.md"
```
![image](https://user-images.githubusercontent.com/24386802/64356096-9502a000-d002-11e9-9f24-7911a315a8d1.png)

![image](https://user-images.githubusercontent.com/24386802/64356053-84eac080-d002-11e9-92e0-5fc186986230.png)

**Comment by abom** [comment]
Please, we don't need screenshots, add the exact macro here, this is not clear at all, also which wiki? which source document?

**Comment by abom** [comment]
Also, this is not the link macro, this is include macro, but as multi-line, it should be as a block.

Please check if it's written as format, see docs [here](https://github.com/threefoldtech/digitalmeX/blob/development/docs/publishing_platform/wiki/macro/README.md#macros) (still valid, nothing changed regarding macros)

**Comment by abom** [comment]
Seems like it was the same issue as https://github.com/threefoldtech/jumpscaleX_threebot/issues/8#issuecomment-528425052 and https://github.com/threefoldtech/jumpscaleX_threebot/issues/12, which is already resolved.


![Screenshot from 2019-09-08 11-21-05](https://user-images.githubusercontent.com/511438/64486255-f442f900-d22a-11e9-9e76-77f7281a6acd.png)

**Comment by Dinaamagdy** [comment]
I already added exact macro  not only screenshot as it exist in description inside ```  and source also exist thrreefold rivine
BTW Issue solved and  veririfed on :
```
works in
jumpscalex_core : 79a930098d114fbf43c98c5d5525d0ed7b599f98
jumpscalex_libs : development
jumpsccalex_threeboot: development
```
