### ISSUE TITLE
weblibs to be served on /weblibs always as part of nginx locations

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#140]
- instead of copying/linking we should have a location for our static assets `weblibs` on /weblibs or something 

- implement linking instead of copying so we don't break other people packages until they gradually update

**Comment by andrewayoub** [comment]
> instead of copying/linking we should have a location for our static assets weblibs on /weblibs or something

https://github.com/threefoldtech/jumpscaleX_threebot/commit/5f790f248eab96a05d09ac79bb86ca565882fd92

> implement linking instead of copying so we don't break other people packages until they gradually update

https://github.com/threefoldtech/jumpscaleX_core/commit/23e888cfbc8359e21a8ec79004667167e9b047f5

**Comment by andrewayoub** [comment]
## Verification:
1- `j.servers.threebot.local_start_default()`
2- check that the static files of weblibs are served on /weblibs (check this link for example "/weblibs/bootstrap3/js/bootstrap.min.js"
