### ISSUE TITLE
Migrate farm per farmer

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_threebot#142]
In case of a farmer wanting to import their farms from legacy.

The farmer would supply their 3bot double name as well as their iyo information for the import to happen.

The code [here[(https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threefold/tfgrid_directory/jobs/sync_directory.pyhttps://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threefold/tfgrid_directory/jobs/sync_directory.py) needs to be adapted to import per farmer.

This is needed for #121

**Comment by jdelrue** [comment]
Discussed with kds, is postponed
