### ISSUE TITLE
threebot provisioning: should deploy multiple 3bot container on same machine

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#144]
https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/threebot_provisioning

Currently this actor creates a new machine for each 3bot. We would like to change that and allow to have multiple 3bot on the same machine. Each one in its own container.
This would make deployment faster and also cheaper.

Things to consider:
- when deploying a 3bot, the threebot_provisioning actor needs to be able to reach the gedis interface of the 3bot. Thus some port management has to be done when installing the 3bot container so there is not port conflicts.
- Some logic has to be created to ensure proper distribution of the 3bot over X machine. need to take care of the memory usage of the machine.

**Comment by andrewayoub** [comment]
the deployment tool has been refactored to store the machines and info in bcdb in a more logical structure here https://github.com/threefoldtech/jumpscaleX_libs_extra/commit/28372f8b566226f91e94b1ca0de31a598b28b4f6

added features:
* deploy multiple threebots on the same machine
* when you create a machine you can set the maximum capacity for this machine which the number of containers that can be created there 
* each container has it's gedis port and ssh port stored inside and you can get both clients from it easily
* you can use `deployer.machines.get_availabe()` which will try to get a machine or create a new one if all the machines are full

**Comment by zaibon** [comment]
@andrewayoub great job that looks very nice
