### ISSUE TITLE
identity actor

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#148]
as you can't get the threebot owner email directly from the phonebook we need to utilize `j.tools.threebot.default` to return some information about the 3bot owner (should be protected in the future with something like whitelist)

**Comment by xmonader** [comment]
threebot: b5c9d1d34157875d0c95e91f731348ef876a2a0b
core: https://github.com/threefoldtech/jumpscaleX_core/commit/dbf8c0ce8e947448a8361b7202d3b1f8544c3b08

**Comment by john-kheir** [comment]
Works fine

#### Verifications steps
1-  j.tools.threebot.me.default.email = "..."
2-  j.tools.threebot.me.default.pubkey = "..."
3-  j.tools.threebot.me.default.save()
4- reload the threebot server
5- then check if `curl -XPOST http://127.0.0.1/web/gedis/http/identity/email ` will return your mail.
