### ISSUE TITLE
Registry Package

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_threebot#160]
This package will be used to register any type of packages or schemas in the grid registry.
It will then create a record of the type of registered item with where it resides. This will then make the item searchable across many fields.

**Comment by waleedhammam** [comment]
Checklist:
- [ ] 
- [ ] 
- [ ]

**Comment by waleedhammam** [comment]
Check list:
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by waleedhammam** [comment]
**Checklist**:
In actor side:
- [ ] register content 
    - add content (encrypted/non encrypted) of a wiki, blog, package ..  could be structured or not
    - if data is encrypted so is it signed using a signature hex private key and only authorized people can access it

- [ ] get content
    - get a specific content using its id

- [ ] be able to register a jumpscale schema
    - make sure the registrar knows about the schema's used [for  threebot client object]

- [ ] search for encrypted content
    - search for encrypted content if user have access to it
    - search could be by tags, categories, country ..
    - make sure if  result > 50 don't return for now

- [ ] search for content with format (non-encrypted)
    - only works for non-encrypted content
     - search the data
        if found: see if there was a jumpscale schema used
        if jumpscale schema
           deserialize the data if needed and put in jumpscale object
            serialize the coming from the jumpscaleobject to the format asked for
               return the data
        if not jumpscale schema
            deserialize & re-serialize if needed to make sure the return format is the right one

__
Registery package:
Test for registration of some wiki page 
- [ ] we should create 2 examples, one where we encrypt for multiple threebot identities (j.tools.threebot...)
- [ ] need to sign with private key of author, we sign the bin data from dataobj (_data)
- [ ]  verify if we can get the data and if we can decrypt (if encrypted)
- [ ] general verification

__
Jumpscale client side:
Make it easier to register / find

**Comment by RafyAmgadBenjamin** [comment]
I am done with the client and fixing some issue mention above

**Comment by RafyAmgadBenjamin** [comment]
I have  ticked Bugs that was done  and made documentation

**Comment by waleedhammam** [comment]
**Commits**
**Core:** https://github.com/threefoldtech/jumpscaleX_core/commit/4c7ba1ac25e601079c3c6225b03fd6d5adf01fd6
**Threebot:** https://github.com/threefoldtech/jumpscaleX_threebot/commit/244cf107476d0cda5e61175614b747f88dc08536

**Docs**
**- Package:** https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid/registry/wiki/README.md
**- Client:** https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/clients/tfgrid_registry/README.md

Future work:
-  update the threebot with threebot session when it is ready to be used
-  threebot.registry.entry.data_encrypted.1 the tid must be a single value not a list in schemes
-  Registery in register must support list of objects of data.

**Comment by john-kheir** [comment]
Concerning Docs:
1- Connect the client docs to packages docs + Add missing steps for users to try the whole flow. like starting the server, loading package, etc
2- Use threebot ids in the docs instead of using integers

Issues:
handle exception coming from j.clients.tfgrid_registry.find_encrypted(author_id) when using wrong auth_id

**Comment by waleedhammam** [comment]
Docs are updated at: 
client: https://github.com/threefoldtech/jumpscaleX_core/pull/193, 
package: https://github.com/threefoldtech/jumpscaleX_threebot/pull/214
