### ISSUE TITLE
Add package.toml to keep track of package metadata

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#162]
- [x] Packages can have metadata (description, frontend or not, .. etc)
- [x] Package manager should be able to list packages with optionally checking for frontend flag in the package.toml for all of the packages 
- [x] update relevant docs

The suggestion is to bundle optional package.toml with the package with sane defaults like empty string fro description and false for frontend.

**Comment by jdelrue** [comment]
I found this code in package manager:


![image](https://user-images.githubusercontent.com/1687505/67772468-66c99b80-fa5a-11e9-9691-d52c649f040a.png)


So probably it already exists somehow? Maybe we should get rid of this or use this?

Also, this issue could be added to the other I guess:
[137](
https://github.com/threefoldtech/jumpscaleX_threebot/issues/137)

**Comment by ahelsayd** [comment]
@jdelrue  currently we have an actor to list installed pakages
```server.actors.package_manager.packages_list()```

https://github.com/threefoldtech/jumpscaleX_core/blob/2c6ced07334ee4a6c11374e6f479bf52d8be154c/JumpscaleCore/servers/threebot/base_actors/package_manager.py#L154

**Comment by ahelsayd** [comment]
i added a ```frontend``` flag to filter only frontend packages, all you need is a ```meta.toml``` file in the root directory of the package like this
https://github.com/threefoldtech/jumpscaleX_threebot/blob/8c25818db8db3f79802bfb415aee58b71b248be8/ThreeBotPackages/alerta/meta.toml#L1-L2

**Comment by john-kheir** [comment]
#### Verification Steps
1- Get Client 
cl = j.servers.threebot.local_start_default() 

2- Add any package 
cl.actors.package_manager.package_add(path='')

3- Update  `meta.toml` of this package in which `frontend=true`

4- List packages with frontend=True and check if the package you added is there
cl.actors.package_manager.packages_list(frontend=True).packages
