### ISSUE TITLE
openresty chat and wiki endpoints updates

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#165]
Currently it's threebot/chat/session/SESSION_NAME
- Allow it to be on /chatflow/chat_topic as well
- Check if possible to have it under `3bot_url/$package/chatflow` so it's relative to the package 
- Don't remove the old chat endpoints just yet

**Comment by xmonader** [comment]
wiki rewrite: cc9d71e116fc869deb8c935053049516658670a4
chat rewrite: 1ff46a2df9effa18b9f1e95fa06b5a1364186469

**Comment by john-kheir** [comment]
#### Verification steps:
1- start the server 
2- `jsx wiki-load -u https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/wikis/examples/docs -n examples -f
`
3- check if 172.17.0.2:/wikis/examples and 172.17.0.2:/examples/wikis will render the same page
