### ISSUE TITLE
oauth package

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#166]
3bot can choose to be an identity server itself that will require

- site providers to be defined on the 3bot 
- oauth server not to be hardcoded in chatflow
- allow protecting other routes using our central oauth_proxy `oauth2.testnet.grid.tf`

**Comment by john-kheir** [comment]
Verified: check the steps here https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/oauth2
