### ISSUE TITLE
Allow support for query params in web gedis GET

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_threebot#168]
Gedis doesn't respect query params when GET is used. We need support for it.

**Comment by serboctor** [comment]
fixed here https://github.com/threefoldtech/jumpscaleX_threebot/commit/1991225302ef46c50030a29e0e7ceff8ed232a52

**Comment by siddiquagig** [comment]
Verified

Loaded the alerta package and then tried 


```
3BOTDEVEL:tf:~: curl 10.16.0.249/web/gedis/http/alerta/list_alerts_by_env?env_name=all
{"result": {"alerts": [{"severity": 10, "status": "new", "time": 1572951129, "environment": "ALL", "service": "JSX", "resource": "xmonader", "event": "event 1", "value": "n/a", "messageType": "error", "text": "rafir text", "count": 1, "occurrences": [], "id": 41}]}, "error_code": "", "error_message": ""}
```


![image](https://user-images.githubusercontent.com/25789724/68203097-832b8200-ffde-11e9-80a6-5936a628f96c.png)
