### ISSUE TITLE
MVP for threebot server (jumpscale_web)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#17]
- Core functionality
   - [x] Registering packages
   - [x] OpenResty configurations 
      - [x] Websites
      - [x] Wikis
      - [x] Static Assets
      - [x] HTTP Proxies
      - [ ] TCP Proxies

   - [x] Rack functionality 

- Packages functionality
  - [x] websites registration (static) (urgent)
  - [x] chatflows registration
  - [x] wikis registration (urgent)
  - [x] Actors registration (urgent)
  - [x] Web applications (e.g bottle applications/gevent servers)
 
- Required Documentation
  - [x] Registering website (static) (urgent)
  - [x] Registering wiki 
  - [x] Registering Actor
  - [ ] Using Actor from frontend (urgent)
 
- [x] Packages Examples

on branch jumpscale_web

**Comment by despiegk** [comment]
maybe new branch?
