### ISSUE TITLE
make cockpit frontend load from javascript file directly instead of webpack build

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#170]
At the moment, the tfgrid_cockpit package old a build version of the cockpit in this repo: https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/threefold/tfgrid_directory/frontend

I would like we change that to only load the file directly without the need of building using webpack.

Next to that I would like to know what is the strategy to update these things one they are live? I would like to reach a point where I can very easily pull new changes/fix onto the testnet threeboot

@jdelrue @xmonader 
please advice :-)

related issue: https://github.com/threefoldtech/tf_cockpit/issues/35

**Comment by xmonader** [comment]
@jdelrue shared his team workflow with vue.js apps https://github.com/jimbertools/vue-apps/blob/master/Readme.md and the documentation will be updated with a complete example :)

**Comment by jdelrue** [comment]
we are currently working on that for first packages calendar and contacts and will then address other packages.

**Comment by zaibon** [comment]
Let's pause this since the concept of 3bot app is being reworked on.
