### ISSUE TITLE
When trying to filter on farm_id, the filter does not seems to be working

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/jumpscaleX_threebot#171]
I tried to pass the farm_id to filter nodes, however the filter is not working.
![image](https://user-images.githubusercontent.com/17977313/67933992-38b59a00-fbc7-11e9-959b-d0b5366085e8.png)

**Comment by zaibon** [comment]
I just tested this and it works fine. I'll close. Feel free to re-open if you still hit the problem.

Also take in account that farm_id is not an int.
