### ISSUE TITLE
tfgrid_dns package naming 

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/jumpscaleX_threebot#176]
The package name is **tfgrid_dns**, but the content of the package use the naming **nameManager** as the following:

- ├── tfgrid_dns
│   ├── actors
│   │   └── namemanager.py
│   ├── NameManagerFactory.py
│   ├── package.py

- jslocation is `j.threebot.package.namemanager`

_Should the name be consistent to either one of **nameManager** or **tfgrid_dns**?_

**Comment by rkhamis** [comment]
Indeed, it needs to be updated to be consistent

**Comment by xmonader** [comment]
/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/dns
