### ISSUE TITLE
Blog: twitter icon doesn't work corerectly

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#179]
- Click on twitter icon .
## Issue
will redirect u to Instagram page instead of twitter page
![image](https://user-images.githubusercontent.com/24386802/67956885-7208fc80-fbfd-11e9-8daa-cc195cc71e08.png)

**Comment by xmonader** [comment]
yes, won't fix it's coming already from a blog source, not related to the blog itself
