### ISSUE TITLE
MyJobs package

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#18]
Create myjobs package with the following requirements

- [x] Collecting workers information from BCDB (workers_list)
- [x] Collecting tasks information from BCDB (jobs_list)
   - the json return should also embed (action name, action args, action kwargs)

Documentation
- [x] How to create the package
- [x] How to register the website on threebot 
- [x] How to create the actor and how to communicate with BCDB models and sending it back on the websocket

**Comment by xmonader** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/myjobs

**Comment by despiegk** [comment]
its not done yet but there is other story
