### ISSUE TITLE
myjobs and alerta don't work correctly

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#185]
alerta and ,myjobs both of them keep loading without result in tables as shown in the following images :

![image](https://user-images.githubusercontent.com/24386802/68108277-0ae69300-fef0-11e9-9141-25ba446300c8.png)

![image](https://user-images.githubusercontent.com/24386802/68108299-176aeb80-fef0-11e9-97ea-2512b5876b21.png)

**Comment by abom** [comment]
Should be resolved as stated here https://github.com/threefoldtech/jumpscaleX_threebot/issues/195

**Comment by hossnys** [comment]
for myjobs it's working now 
![Screenshot from 2019-11-05 19-10-42](https://user-images.githubusercontent.com/26298009/68229509-132df380-0000-11ea-81e9-e0e04f5b7da5.png)

but for alerta it's still  spinning with this error
![Screenshot from 2019-11-05 19-08-03](https://user-images.githubusercontent.com/26298009/68229637-4a040980-0000-11ea-82f8-687343ffec95.png)

**Comment by hossnys** [comment]
Alerta is working now also 
![Screenshot from 2019-11-06 12-31-29](https://user-images.githubusercontent.com/26298009/68290920-74ea6e00-0091-11ea-920a-22258c2019ab.png)
