### ISSUE TITLE
Blog package doesn't get loaded

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#188]
follow the following steps : 
1- kosmos: j.tools.blog_loader.add_blog("xmon", "git@gitlab.com:xmonader/sample-blog-jsx.git")

2- Start the threebot server first in kosmos using: cl = j.servers.threebot.local_start_default(web=True)

3- Add The blogs package: cl.actors.package_manager.package_add(path="/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/blog")
cl.reload() 

# iSSUE
BLOG not working any more 
![image](https://user-images.githubusercontent.com/24386802/68126857-5bc0b080-ff1d-11e9-8cc6-20997bdab314.png)

**Comment by xmonader** [comment]
shouldn't be part of jsx anymore
