### ISSUE TITLE
Svelte UI visualizer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#19]
Create a job visualizer app with

- [x] Listing workers
- [x] Listing tasks
- [X] Suitable filters

Along with documentation on covering the following
- [x] Creating/initializing the application
- [x] Creating components
- [x] Routing between components
- [x] Interaction with websockets (gedis websocket client) 
- [x] Add deployment insructions 

Work to be on digitalMeX on branch development_web branch

**Comment by hossnys** [comment]
Here is myjobs [docs](https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/myjobs) 
verified on branch development_web_blog
