### ISSUE TITLE
Convention for static/spa locations in the package to minimize the package.py code

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/jumpscaleX_threebot#190]
- If frontend dir exists in the package directory we create SPA location serve it
- If html dir exists in the package directory we create Static location to serve it it

**Comment by ranatrk** [comment]
WIP: create a decorater to check if the frontend flag is in the meta.toml file, and accordingly create the locations and websites. 
reference: **alerta package**

**Comment by ranatrk** [comment]
**Changes**:
 - Check if package dir includes html directory
 - if dir exists, then create locations and website (executed in ThreebotPackage)
https://github.com/threefoldtech/jumpscaleX_core/commit/0e503e71c0072baf661d35f5cd158b34032a79c3

**TODO**:
 - remove the location creation from all packages that have location creation
 - make sure html dir exists in the packages that require location creation

**Comment by ranatrk** [comment]
Add convention for **frontend** (spa locations) and **html** (static locations) https://github.com/threefoldtech/jumpscaleX_core/commit/d2d84c72ba72d0d455508cb3086065e0dc9c1ff9

**Comment by ranatrk** [comment]
Refactored the following packages for the convention used:
- ffbrowser
- alerta
- interface
- myjobs
- packages_manager

https://github.com/threefoldtech/jumpscaleX_threebot/commit/42bb62a8dab5e6b700df25f64542fbcfb604ff91

Convention:
- SPA should have /frontend dir in package
- Static apps should have /html dir in package
- package.py doesn't need to include the creation of the locations, unless it is to be configured differently for a specific package

**Comment by ranatrk** [comment]
Fixes:
1. Changed packages_manager(name=package) to package_manager(name=package_manager) to avoid conflicts as package is commonly used. https://github.com/threefoldtech/jumpscaleX_threebot/commit/08a7eba74a831d78ee6b1c56efa09eafaf0cc6bb
(example in package interface there is a package dir in the frontend)
2. Refactored interfaces to use the locations in ThreebotPackage.py https://github.com/threefoldtech/jumpscaleX_threebot/commit/99318644d1f6a2e20d8bb9a9c1c0d7ec98a3a137
3. Moved _create_locations() in ThreebotPackage.py to _init_before_action() to avoid overriding some files.  https://github.com/threefoldtech/jumpscaleX_core/commit/3cfb81807d8b191ff3c9c5e7de732864d6ed9474


Other issue not handled:
- If alerta and interface are both loaded in the same time, it produces an issue with vue.js

**Comment by ranatrk** [comment]
@xmonader added the following changes: 
https://github.com/threefoldtech/jumpscaleX_threebot/commit/fc77a835e5e554f97e55d4d8f03696b08e1e48ee
https://github.com/threefoldtech/jumpscaleX_threebot/commit/b39dae6ab854d600971c36be1b50fac669ebac05
https://github.com/threefoldtech/jumpscaleX_threebot/commit/5e4952d0509d614f8bb8ede096a9837bf2e14ece

**Comment by Pishoy** [comment]
alerta and myjobs are verified, waiting @ranatrk to fix packagemanagerui

**Comment by xmonader** [comment]
@Pishoy code merged already

**Comment by Pishoy** [comment]
verified for packagemanagerui 
http://ip/packagemanagerui/ 

- jsx version
```
3BOTDEVEL:jsx:jumpscaleX_threebot: git log -1
commit f707112b4902e398c8ff9043cde3032fccbb1daa (HEAD -> development, origin/development, origin/HEAD)
Author: Rana Tarek Hassan <rana.t.hassan@gmail.com>
Date:   Sun Nov 10 17:01:18 2019 +0200

    Replace packages in packagemanagerui to packagemanagerui #190 (#207)

```
