### ISSUE TITLE
Wikis: re-load single document if it has errors upon request

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_threebot#191]
If a document has errors, reload it when requested.

**Comment by abom** [comment]
When a document is requested, its name is the final processed document, nothing can give me the original.

I'm trying to store `base_path` in metadata of docsite, so we have a repo, and where is the source directory of this docsite inside this repo.

Example metadata:

```
{'name': 'examples', 'repo': 'https://github.com/threefoldtech/jumpscaleX_threebot', 'base_path': 'docs/wikis/examples/docs'}
```

**Comment by abom** [comment]
Added in https://github.com/threefoldtech/jumpscaleX_libs/commit/a864e35e5e887233ec5ed4fb560766b2b3054015 and https://github.com/threefoldtech/jumpscaleX_threebot/commit/992ada684bdfa5af8ace366514caea8467d47bd8.

**Comment by abom** [comment]
Note that docsites need to be reloaded for this to work.

**Comment by AhmedHanafy725** [comment]
### Verification steps:
1 - Start threebot server `cl = j.servers.threebot.local_start_default()`
2- Load test wikis 
```
path = "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/docs/wikis/examples/docs"
docsite = j.tools.markdowndocs.load(path, name="test_wikis")
docsite.write()
```

3- Change in this file `test_html.md` under wikis path.

![image](https://user-images.githubusercontent.com/41957921/68220064-b32f5100-ffef-11e9-837c-f1a4871e6cc9.png)


4- Remove the changes that made this error and request this page again.

![image](https://user-images.githubusercontent.com/41957921/68219881-65b2e400-ffef-11e9-928a-da457b702933.png)

**Verified**
