### ISSUE TITLE
workload reservation money flow

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#194]
Let's define the minimal money flow that needs to happens for a reservation to be deployed on the grid.

**Comment by zaibon** [comment]
Here is the high level documentation about how reservation works: https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid/tfgrid_workloads/wiki/reservation.md#workload-id

**Comment by robvanmieghem** [comment]
related issue: https://github.com/threefoldtech/jumpscaleX_threebot/issues/138

**Comment by zaibon** [comment]
> Related issue with an early reflection on the payment: https://github.com/threefoldtech/jumpscaleX_threebot/issues/138

@robvanmieghem 
Ok I re-read this discussion. Couple of questions:
- Are everything stated in the discussion still applicable for stellar ?
- Does stellar provide better mechanism we could leverage to make this all easy-peasy and more fair for both parties ??

**Comment by LeeSmet** [comment]
>     * Are everything stated in the discussion still applicable for stellar ?
As far as I understand, yes. Following from the discussion, some way to lock funds is needed, and stellar has the ability to do this.

Since an initial implementation would assume a happy path, we can operate on the premisis that both the user and farmer are trustworthy. As such, an easy solution would be to create [a mutlisig time locked escrow account](https://www.stellar.org/developers/guides/walkthroughs/stellar-smart-contracts.html#2-party-multisignature-escrow-account-with-time-lock-recovery) in which the user can lock the funds for the farmer, and the farmer can claim the funds after the contract expires.

The real difficulty would be designing a system which can verify if some arbitrary conditions are met, to decide if the farmer should be payed or not (as discussed in the linked issue)

WIP for the jumpscale stellar client:
https://github.com/threefoldtech/jumpscaleX_libs/tree/development_stellar_client/JumpscaleLibs/clients/stellar

**Comment by robvanmieghem** [comment]
The wip is merged to the development branch.
The question remains on the agreement and the payment. Is there an agreement first, followed by a payment, which includes the hash of the agreement or vice versa?
Thi  seems like the simpler solution. 
Yes,  escrow accounts can be created to lock the funds .
It does have some downsides, like lumens required to add conditions and some complexity like offchain kept unlocktransactions that need proper sequence numbers if used for timelocks.

**Comment by zaibon** [comment]
>  The question remains on the agreement and the payment. Is there an agreement first, followed by a payment, which includes the hash of the agreement or vice versa?

How see the flow would be:
```
1. user create a reservation schema, sign it and send it to BCDB
2. user notify the farmer there is a reservation for him to look at
2.1 result of this call is the creation of escrow account between farmer and user
2.2 user found the escrow account with the required found for its reservation
3. farmer checks the reservation and the amount on the escrow account
3.1 if farmer agrees both on the content of the reservation and the amount it signs the reservation and the erscrow transaction to release the found
4. farmer has been paid and user can access its workload

**Comment by robvanmieghem** [comment]
I don't really see the benefit of using an escrow account here.
1. user creates a reservation schema, sign it and send it to BCDB
2. user notifies the farmer there is a reservation for him to look at
3. farmer checks the reservation
3.1 if farmer agrees both on the content of the reservation and the amount it signs the reservation
4. User pays the farmer with the hash of the rservation added to the transaction 
5. farmer sees the payment and the and user can access its workload

**Comment by zaibon** [comment]
With the escrow we ensure that the user as actually the found to pay the reservation ?
Without this the user can just never pay the farmer no ?

**Comment by robvanmieghem** [comment]
@zaiubon Since the farmer only activates the resevation after the payment has been received(step 5), this is no problem. The jumpscale client would have to be extended to list transactions including the memofields.

**Comment by LeeSmet** [comment]
While the escrow is not strictly needed at this time, we would eventually have some form of locking in the final flow, as there the tokens would be destroyed if it can be proven that the farmer  did not uphold his end of the reservation, right?

**Comment by robvanmieghem** [comment]
Indeed but several options exist for that depending on which path we take.
I would keep it simple  for now.

**Comment by LeeSmet** [comment]
# payment flow proposal

- The user (threebot) creates a reservation, signs it, and pushes it to the explorer.
- After the reservation has been pushed to the explorer, the threebot extracts all node ids from the workloads, looks up what farm they are in, and what threebot manages that farm.
- the user threebot does a call to every farmer threebot, with the workload id as argument, asking if the farmer threebot agrees to deploy this reservation. (Note, phonebook entries don't seem to have a threebot id - how to look up mapping??).
    - If one or more farmer threebots refuse, the reservation won't be deployed. Nothing to be done anymore.
- All farmer threebots agree. Map the workloads to be deployed per farmer, so we can calculate how much resources are being deployed for every farmer. We can then look up the price per resource per farmer. to calculate how much every farmer needs to be payed. Note, we should probably do this before pushing the reservation in step 1, the client 3bot can check if it even has enough TFT to fund the reservation.
- Pay every farmer threebot, add the reservation ID as a memo.
- Finally, farmer threebots should be notified of they payment somehow. They extract the reservation id, also calculate how much they should be charging for the reservation, and if everything checks out, they sign the reservation as a farmer.

## caveats

- This asumes a happy path payment flow. If any of the farmers is undepayed, the 3bot will not sigh the reservation, and the workloads will not be deployed. Eventually we will need some kind of system where 1 threebot refusing can notify the other 3bots, so they can all refund the client.

- If a farmer is overpayed, the 3bot can, on an individual basis, decide to refund the overpayed amount.

- Theoretically, the resource price of a farm could be changed in between the client calculating how much he needs to pay, and the farmer calculating how much he should be payed, which will lead to incorrect payments, causing the workload to not be deployed.

**Comment by LeeSmet** [comment]
Work to calculate how much tokens need to be paid per farmer in a reservation: https://github.com/threefoldtech/jumpscaleX_libs/issues/106

**Comment by zaibon** [comment]
Implemented at 
https://github.com/threefoldtech/jumpscaleX_libs/blob/development/JumpscaleLibs/sal/zosv2/billing.py#L32 and https://github.com/threefoldtech/jumpscaleX_libs/blob/development/JumpscaleLibs/sal/zosv2/billing.py#L47
