### ISSUE TITLE
Monitoring system (like alerta) using svelte and gedis

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#20]
Create alerta package with the following requirements

- Actor (alerta)
   - [x] list alerts information from BCDB (list_alerts)
   - [x] list alerts by environment information from BCDB (list_alerts)
   - [x] create alert information from BCDB (new_alert)

- UI using svelte
  - [x] Listing alerts
  - [x] Suitable filters (component, status, ..etc)
  - [x] searchable content

Along with documentation on covering the following
- [x] Creating/initializing the application
- [x] Creating components
- [x] Routing between components
- [x] Interaction with websockets (gedis websocket client) 
- [x] Add deployment instructions 
- [x] How to create the package
- [x] How to register the website on threebot 
- [x] How to create the actor and how to communicate with BCDB models and sending it back on the websocket

**Comment by xmonader** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/alerta

**Comment by hossnys** [comment]
verified on branch development_web_alerta for only jumpscaleX_threebot repo and other repos on development :
alerta installation **OK**
listing alerts from UI and from BCDB **OK**
search content from UI **OK**
create alert from BCDB **OK**

![Screenshot from 2019-09-11 14-03-36](https://user-images.githubusercontent.com/26298009/64696281-4fc8ed00-d49e-11e9-8dbe-033d5bc5f2ca.png)

![Screenshot from 2019-09-11 14-04-00](https://user-images.githubusercontent.com/26298009/64696283-4fc8ed00-d49e-11e9-8828-018be5c034bf.png)

![Screenshot from 2019-09-11 14-04-51](https://user-images.githubusercontent.com/26298009/64696284-4fc8ed00-d49e-11e9-9bf8-abbd25d50481.png)

![Screenshot from 2019-09-11 14-15-11](https://user-images.githubusercontent.com/26298009/64696285-50618380-d49e-11e9-9f02-35dbce665cbd.png)
