### ISSUE TITLE
pastebin based on gedis and svelte

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#21]
Create pastebin package with the following requirements

- Actor (pastebin)
   - [x] get paste information from BCDB (get_paste)
   - [x] create new paste (new_paste)

- UI using svelte
  - [x] Creating a paste
  - [x] Download link
  - [x] Copy to clipboard
  - [x] Copy paste url
  - [x] Highlighted code

Along with documentation on covering the following
- [x] Creating/initializing the application
- [x] Creating components
- [x] Routing between components
- [x] Interaction with websockets (gedis websocket client) 
- [x] Add deployment instructions 
- [x] How to create the package
- [x] How to register the website on threebot 
- [x] How to create the actor and how to communicate with BCDB models and sending it back on the websocket

**Comment by xmonader** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/pastebin

**Comment by hossnys** [comment]
verified on branch development_web_blog
