### ISSUE TITLE
wiki: a macro to generate a pdf link from google documents, presentations and spreadsheets

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_threebot#217]
- [x] Update service account docs on how to access private files and enabling other related google apis.
- [x] Make sure [gdrive tool](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/docs/wikis/tech/gdrive.md) works well and return useful errors and update its docs
- [x] Write gpdf macro to parse google docs links and return a download link by using [gdrive tool](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/docs/wikis/tech/gdrive.md) endpoints.

Note: `googleslides` tool have some [useful utils](https://github.com/threefoldtech/jumpscaleX_libs/blob/master/JumpscaleLibs/tools/googleslides/slides2html/google_links_utils.py#L4) to parse links, update them to support doc type parsing too (thanks @xmonader)

**Comment by abom** [comment]
After testing our gdrive client and tool, it needs some enhancements regarding handling and documentation updates (already in-progress).

I updated the documentation of how to get service accounts for google api to explain how private files can be accessed by this type of credentials https://github.com/threefoldtech/jumpscaleX_threebot/pull/215.

**Comment by abom** [comment]
Now, trying to update [gdrive tool](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/docs/wikis/tech/gdrive.md) to show more useful errors that redirects the user/admin to correct documentation in case invalid response from google apis due to e.g. invalid credentials or setup.

**Comment by abom** [comment]
Need to be merged https://github.com/threefoldtech/jumpscaleX_threebot/pull/218

**Comment by abom** [comment]
Fixed gdrive client, as it caches the operation with only file id, but if the `destpath` is different, it would fail as it cannot find the new destpath yet! https://github.com/threefoldtech/jumpscaleX_libs/pull/37

Also, found out that nginx config does not contain gdrive locations!
fixed here https://github.com/threefoldtech/jumpscaleX_core/pull/196

Updated gdrive handler here too
https://github.com/threefoldtech/jumpscaleX_threebot/pull/220

Still trying to get gdrive endpoints work, for now, [endpoints that generate a pdf](https://github.com/threefoldtech/jumpscaleX_threebot/blob/d555a5a7893a48c7c43b14911dab284b18144ec0/docs/wikis/tech/gdrive.md#available-endpoints) file works (`docuemnt`, `presentation` and `spreadsheets`)  but `slide` does not.

**Comment by abom** [comment]
Added error handling to gdrive actor in https://github.com/threefoldtech/jumpscaleX_core/pull/196/commits/82816472164c77fcf6d1893c3ba0e6e98cf4813d and errors page for gdrive tool in https://github.com/threefoldtech/jumpscaleX_threebot/pull/220/commits/f98cdffe42fb964408e6d334d0f9b692f3fc119f.

**Comment by abom** [comment]
Updated gpdf macro in https://github.com/threefoldtech/jumpscaleX_libs/pull/37/commits/dff6bfdc42e45b2218f83aa33103accc9a345ef4 to use gdrive endpoints and added documentation in https://github.com/threefoldtech/jumpscaleX_threebot/pull/220/commits/d5a67ae8f13cfb880821133402dc8800027f09ab

**Comment by abom** [comment]
Three related PRS need to be merged

https://github.com/threefoldtech/jumpscaleX_core/pull/196
https://github.com/threefoldtech/jumpscaleX_libs/pull/37
https://github.com/threefoldtech/jumpscaleX_threebot/pull/220

**Comment by abom** [comment]
@Pishoy `gpdf` macro docs https://github.com/threefoldtech/jumpscaleX_threebot/blob/d5a67ae8f13cfb880821133402dc8800027f09ab/docs/wikis/macro/gpdf.md

**Comment by Pishoy** [comment]
when i load wiki examples i got below error 
```
jsx wiki-load -u https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/wikis/examples/docs -n myexamples -f

Wed 13 10:57:15 Doc.py               - 413 - doc                                : write:doc:test_gpdf:/sandbox/code/github/threefoldtech/jumpscaleX_threebot/docs/wikis/examples/docs/test_gpdf.md
Wed 13 10:57:15 Doc.py               - 359 - doc                                : ```python
ERROR IN MACRO*** TODO: *1 ***
macro:
gpdf
ERROR:
COULD NOT FIND MACRO
```
Wed 13 10:57:15 DocSite.py           - 363 - docsite                            : ## ERROR: test_gpdf

- in doc: doc:test_gpdf:/sandbox/code/github/threefoldtech/jumpscaleX_threebot/docs/wikis/examples/docs/test_gpdf.md

```python
ERROR IN MACRO*** TODO: *1 ***
macro:
gpdf
ERROR:
COULD NOT FIND MACRO
```
Wed 13 10:57:15 /markdowndocs/Doc.py - 362 - _macros_process                    : EXCEPTION: 
    KeyError('gpdf',)
--TRACEBACK------------------
/sandbox/bin/jsx in <module>
    886    cli()
/sandbox/bin/jsx in wiki_load
    456    load_wiki(wiki_name, wiki_url, download=download, pull=pull)
/sandbox/bin/jsx in load_wiki
    424    wiki.write()
/sandbox/lib/jumpscale/JumpscaleLibs/tools/markdowndocs/DocSite.py in write
    697    doc.write()
/sandbox/lib/jumpscale/JumpscaleLibs/tools/markdowndocs/Doc.py in write
    414    md = self.markdown  # just to trigger the error checking
/sandbox/lib/jumpscale/JumpscaleLibs/tools/markdowndocs/Doc.py in markdown
    229    self._process()
/sandbox/lib/jumpscale/JumpscaleLibs/tools/markdowndocs/Doc.py in _process
    220    self._macros_process()
/sandbox/lib/jumpscale/JumpscaleLibs/tools/markdowndocs/Doc.py in _macros_process
    362    method = j.tools.markdowndocs._macros[macro_name]
-----------------------------

```
- jsx version 
```

```

**Comment by abom** [comment]
@Pishoy Please make sure to pull all repos including jumpscaleX_core, jumpscaleX_libs

**Comment by Pishoy** [comment]
it is verified for document but when open presentations and spreadsheets , gives me an error about permission
![image](https://user-images.githubusercontent.com/21987477/68763077-4126bf80-0620-11ea-9df2-8c764a629b01.png)

**Comment by abom** [comment]
Is it a private file? The service account you set have an access to this file? if not, just try another one you can access using this service account.

The error message have some useful info, please try to check it and tell us if it's not good enough.

**Comment by Pishoy** [comment]
verified 
- jsx version
```
3BOTDEVEL:jsx:jumpscaleX_threebot: git log -1
commit 063063d0b1e08a36501c79b5da4022ee9f103fe3 (HEAD -> development, origin/development, origin/HEAD)
Author: RafyAmgadBenjamin <46320202+RafyAmgadBenjamin@users.noreply.github.com>
Date:   Wed Nov 13 13:38:38 2019 +0200

    update the ChatFactory.py and BottleInterfaceFactory.py to reuse the enable_cors from GedisHttpFactory.py (#223)
```
