### ISSUE TITLE
/docs in the url shouldn't be needed if docs directory exists in the repo root

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#227]
to load wiki by git url you need to specify the path to `/docs`, shouldn't be needed if it's in the toplevel

**Comment by Pishoy** [comment]
i started a wiki as below command 
```
 jsx wiki-load -u https://github.com/threefoldtech/jumpscaleX_threebot -n threefold-examples -f
```
and i got below picture but when click in link alerta link as shown in picture, i got `404 - Not found`
![image](https://user-images.githubusercontent.com/21987477/68834769-32431a00-06bf-11ea-8a6e-e02d3416d03a.png)

@abom please advice this should work or not ?

**Comment by abom** [comment]
Alerta is outside this docsite source, which is `docs` directory. Docs directory in this reop is not meant to be used as a docsite, please test with other repositories like https://github.com/threefoldfoundation/info_foundation.

**Comment by Pishoy** [comment]
verified 
- jsx version
```
3BOTDEVEL:jsx:jumpscaleX_threebot: git log -1
commit 2210665d12c97054bd80553be6a7dff28caf1f6c (HEAD -> development, origin/development, origin/HEAD)
Author: tobiaschielens <tobias.chielens@gmail.com>
Date:   Wed Nov 13 19:12:49 2019 +0100

    Fixed update farm requiring to change farmname (#234)

```
