### ISSUE TITLE
tfgrid_directory [development_tfgrid_directory] 

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#23]
https://github.com/threefoldtech/jumpscaleX_threebot/tree/provisioning-actors/ThreeBotPackages/threefold/tfgrid_directory/actors

- [x] wait till development_bcdb_sqlite is done & migrate the models (* -> **)
- [x] put on right branch
- [ ] ask kristof to review the actors & the way how we use the model
- [ ] show kristof how it get info from deployed zos-nodes
- [x] create a actor method (using myjobs) to pull info from old TFDir, if node already exists don't overwrite
- [ ] create example in non jumpscale pythong how to call the redis client and use actors from gedis to call actor and verify info

**Comment by rkhamis** [comment]
start feature development on development branch until development_bcdb_sqlite is ready. Then migrate models to use sqlite.

Make sure to develop on branch `development_tfgrid_directory`

**Comment by serboctor** [comment]
I created a preliminary actor for migration but some stuff is still missing like figuring out the threebot id that will be used for migrated farms. 
I can see there's a discussion going on here https://github.com/threefoldtech/tf_cockpit/issues/12

**Comment by zaibon** [comment]
@serboctor where is your code for the migration ?

**Comment by serboctor** [comment]
@zaibon https://github.com/threefoldtech/jumpscaleX_threebot/blob/development_tfgrid_directory/ThreeBotPackages/threefold/directory/actors/farms.py#L87

**Comment by serboctor** [comment]
@despiegk For the last point in the ticket description do you just want a script that shows how to call gedis actors using redis? I don't get the `verify info` part.
