### ISSUE TITLE
Actors not working if called before installed

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/jumpscaleX_threebot#232]
# Scenario 1:
```
cl = j.servers.threebot.local_start_default(web=True)
cl.actors.package_manager.package_add(path="/.... some pkg with actors")
cl.reload()
```
Threebot will start and actor will work

# Scenario 2:
```
cl = j.servers.threebot.local_start_default(web=True)

```
Try actor now, doesnt work
```
cl.actors.package_manager.package_add(path="/.... some pkg with actors")
cl.reload()
```
Try actor now, still doesnt work

**Comment by abom** [comment]
I cannot reproduce this issue and have some questions, how do you "try" an actor? because before adding the package, the actor itself won't be available in `cl.actors` list, and web interface of your package too.

**Comment by abom** [comment]
It turns out that the gedis client used in http handler is not the same as the main client sometimes, specially if it's not the same process, so it needs a reload too.

Should be fixed by https://github.com/threefoldtech/jumpscaleX_threebot/pull/239
