### ISSUE TITLE
actors for the tfgrid_workloads

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#24]
## steps

https://github.com/threefoldtech/jumpscaleX_threebot/tree/provisioning-actors/ThreeBotPackages/threefold/tfgrid_workloads

- [ ] make sure they use the new bcdb_development_sqlite (once its on development)
- [x] add tests to show how it works, sign, add, ... multiple scenario's
- [x] ask kristof to review the actors/models/...

## links

- [ ] https://github.com/threefoldtech/jumpscaleX_threebot/pull/16

**Comment by ashraffouda** [comment]
@despiegk  can u plz check the actor and models in this pr ? https://github.com/threefoldtech/jumpscaleX_threebot/pull/16 
I added tests for it and fixed the actor

**Comment by rkhamis** [comment]
Will be verified when sqlite rework is done

**Comment by zaibon** [comment]
@rkhamis @Dinaamagdy 

> Will be verified when sqlite rework is done


This is not yet code complete. no point starting verifying yet.

**Comment by zaibon** [comment]
duplicates of https://github.com/threefoldtech/jumpscaleX_threebot/issues/26
