### ISSUE TITLE
setup cockpit again

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#247]
With all the changed that happens the last week the tesnet cockpit that was deployed at `cockpit.testnet.grid.tf` is broken. This URL now the 3bot initialization form.
So we need to setup the cockpit again.

Todo:
- [x] Decide at which URL is it going to be hosted. At the moment there is now way to decide at which path a UI should be deployed. things are hardcoded into the `package.py file` and cockpit UI is served at `/grid_directory`. 
So should we document the address of the cockpit to be `explorer.testnet.grid.tf/grid_directory` ?
- [x] Make the home page of the explorer always redirect to the cockpit URL and not show the 3bot UI.

**Comment by zaibon** [comment]
As a manual workardoung for now I added a nginx config with a redirection from `/` to `/grid_directory` 
so at least when someone goes to `explorer.testnet.grid.tf` or `cockpit.testnet.grid.tf` it sees the cockpit UI

**Comment by despiegk** [comment]
first need to have the branch [development_actorsimprovement] usable

**Comment by zaibon** [comment]
blocked on https://github.com/threefoldtech/jumpscaleX_core/issues/444

**Comment by zaibon** [comment]
https://github.com/threefoldtech/jumpscaleX_core/issues/444 is now solved and tesnet explorer seems to be stable.
Home page also show the directory UI now, so we are all set. Thanks
