### ISSUE TITLE
Create packages for our websites

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_threebot#25]
Follow docs here: https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/servers/threebot#packages

to create packages for all our websites

**Comment by rkhamis** [comment]
@Pishoy please create a list of all the websites we need to package and keep this storycard updated with progress

**Comment by Pishoy** [comment]
- below are a list of websites

- [ ] www.enertia.io
- [ ] www.freeflowtokens.com
- [ ] threefold.io
- [ ] www.goldflow.io
- [ ] www.freeflowtoken.com
- [ ] harvested.io
- [ ] www.freeflowpages.com
- [ ] www.capemusicacademy.com
- [ ] www.atwg.tech
- [ ] www.freeflowevent.com
- [ ] www.bettertoken.com
- [ ] www.faircoffee.trade
- [ ] www.3bot.org
- [ ] www.freeflownation.org
- [ ] www.veda-masters.com
- [ ] www.harvested.io
- [ ] www2.harvested.io
- [ ] www.threefold.io
- [ ] www.es.freeflownation.org
- [ ] www.grid.tf
- [ ] www.openly.live
- [ ] www.support.grid.tf
- [ ] www.es.veda-egypt.com
- [ ] www.nbh-digital.com
- [ ] www.cultivo.earth
- [ ] www.veda-retreats.com
- [ ] bettertoken.com
- [ ] www.veda-egypt.com
- [ ] www.threefold.love
- [ ] www.staging.freeflowpages.com
- [ ] www.threefold.tech
- [ ] www.euroflow.io
- [ ] www.inid.io

**Comment by Pishoy** [comment]
verified 
1 - install jumpscaleX
2 -  if website was already running
     Kill ALL tmux running servers
     clean bcdb  `kosmos 'j.data.bcdb.destroy_all()'`
     remove old servers config `rm -rf /sandbox/cfg/nginx/default_openresty_threebot/servers/*`
3 - create you package file as below 
```
from Jumpscale import j


class Package(j.baseclasses.threebot_package):
    def _init(self, **kwargs):
        if "branch" in kwargs.keys():
            self.branch = kwargs["branch"]
        else:
            self.branch = "master"

    def prepare(self):
        """
        is called at install time
        :return:
        """
        server = self.openresty
        server.install(reset=True)
        server.configure()
        website = server.websites.get("threefold_tech")
        website.ssl = True
        website.port = 443
        locations = website.locations.get("main")
        static_location = locations.locations_static.new()
        static_location.name = "static"
        static_location.path_url = "/"
        static_location.path_location = f"/var/www/threefold_tech"
        static_location.use_jumpscale_weblibs = True
        website.domain = 'threefold_tech.grid.tf'
        website.path = '/var/www/threefold_tech'
        locations.configure()
        website.configure()


    def start(self):
        """
        called when the 3bot starts
        :return:
        """
        self.prepare()

    def stop(self):
        """
        called when the 3bot stops
        :return:
        """
        pass

    def uninstall(self):
        """
        called when the package is no longer needed and will be removed from the threebot
        :return:
        """
        pass


``
4 - open new session and load ur package 
```
kosmos -p

j.tools.threebot_packages.get('mythreefold_tech',path='/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold_tech') 

j.servers.threebot.default.start(web=True, ssl=True)
```

**Comment by rkhamis** [comment]
@Pishoy this task is actually about creating the website packages, not just verifying that the packages work.

**Comment by rkhamis** [comment]
please add the created packages here: https://github.com/threefoldtech/threefold_websites

**Comment by Pishoy** [comment]
waiting https://github.com/threefoldtech/jumpscaleX_threebot/issues/33

**Comment by Pishoy** [comment]
all websites are done

**Comment by PeterNashaat** [comment]
- Create new Package.py for all websites :

1 - install jumpscaleX
2 - if website was already running
>  Kill ALL tmux running servers

clean bcdb

``` kosmos 'j.data.bcdb.destroy_all()'```
or 
```bcdb delete --all```

important dirs :  /sandbox/cfg/nginx/default_openresty_threebot/servers/ has all websites conf file

3 - create your package file package.py and package.toml in website repo 

package.py example of enertia website > change enertia to the name of your website

```
from Jumpscale import j

class Package(j.baseclasses.threebot_package):

    def start(self):
        server = self.openresty
        server.configure()
        for port in [80, 443]:
            website = server.get_from_port(port)
            locations = website.locations.get(f"enertia_locations_{port}")

            website_location = locations.locations_static.new()
            website_location.name = "enertiawebsite"
            website_location.path_url = "/"
            fullpath = j.sal.fs.joinPaths(self.package_root, "html/")
            website_location.path_location = fullpath

            locations.configure()
            website.configure()
            website.save()


``` 

package.toml example file of enertai website

```
[source]
name = "enertiaio"
description = "enertiaio website"
threebot = "threefold"
version = "1.0.0"
```

then move all website files in directory html .

- should be like this :
![image](https://user-images.githubusercontent.com/13523434/71617627-95800180-2bc4-11ea-98f3-aad7161c8896.png)


From Jumpscale machine do :

```
JSX> cl = j.servers.threebot.local_start_zerobot(background=False)                                                    
MARK THREEBOT IS STARTING
JSX> cl = j.clients.gedis.get("abc", port=8901, package_name="zerobot.packagemanager")                                
JSX> cl.actors.package_manager.package_add(git_url="https://github.com/PeterNashaat/www_enertia_io")                       
```

- from browser go the machine_ip:80 

![image](https://user-images.githubusercontent.com/13523434/71617761-38388000-2bc5-11ea-91fb-086c85b0f769.png)

**Comment by PeterNashaat** [comment]
Websites need to have Package.py and package.toml files for now :
- [] www.3bot.org
       - repo : https://github.com/threefoldtech/www_3bot_org
       - branch name : production 
        - staging branch : master

www.threefold.love

www.threefold.tech
www.incubaid.com

**Comment by Pishoy** [comment]
3bot.org and incubaid.com has been modified and tested, also threefold.love and threefold.tech tested
