### ISSUE TITLE
for package renames, don't crash server for invalid paths, ignore loading the package completely

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#252]
if you rename a package after loading the server will try to load it from the path it knows in bcdb, don't crash and ignore the package completely if so

**Comment by xmonader** [comment]
solved by design now

**Comment by Dinaamagdy** [comment]
## Steps 
- start threebot server 
- change name of base package 
- restart the server

nothing change , so I will close the issue if u have any comment or another scenario , please inform us ?
