### ISSUE TITLE
wikis: search box in some pages don't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#258]
when wiki is one page only no search results are returned

![image](https://user-images.githubusercontent.com/24386802/69034683-89602c00-09ea-11ea-9ede-49d8475c1d3a.png)

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/71958579-4e63c300-31f9-11ea-9b81-4bcdb896e540.png)
Fixed on development

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
