### ISSUE TITLE
3bot: update all API with proper ACL

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#260]
Now that the ACL system has been merged. We need to go over all the API of the 3bot and make sure that the proper ACL is applied on all methods.

This is a blocking issue and we cannot release 3bot for public until then since now all 3bot APIs are just public.

**Comment by despiegk** [comment]
needs be part of security discussion which we still need to do
ACL;s are not on actors
only admin's should be able to use actors in first place, which should also resolve this

**Comment by zaibon** [comment]
> only admin's should be able to use actors

Can you elaborate on that ? I have package that have only public methods and other that have methods that needs to be authenticated. (directory, workload manager).
What is the plan for actor of that sort ?

**Comment by despiegk** [comment]
see security story
