### ISSUE TITLE
Changes to connect page

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/jumpscaleX_threebot#262]
The new connect page for community growing still has some issues and needs some work:

- [ ] Double name will be changed to 3bot name -> no . in between just like 'jdelrue' (will then refer to jdelrue.3bot.me as 3bot address)
- [ ] Every one registering in the  registration app should be checked if the name does not already exists on eg https://login.threefold.me/api/users/jdelrue.3bot
- [ ]  If they are already registered, a message should be shown 'You already registered through the 3bot connect app, thanks for being member of our community'
- [ ] We an API to check if a user already exists on the connect thing when signing up a user, so can force the user to validate the same email address
- [ ] Flow will have some changes, @Sacha96 will get back on this later today

**Comment by ken-de-moor** [comment]
This is a relic of the old referral flow which was abandoned. Closing
