### ISSUE TITLE
web gedis http documentation is outdated

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscaleX_threebot#265]
I was following the documentation at <https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/gedis_http/README.md>, but I should actaully use `.../web/gedis/http/<actor>/<method>` instead of `../actors/<actor>/<method>`.

**Comment by waleedhammam** [comment]
docs updated at: https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/gedis_http/README.md

**Comment by GlenDC** [comment]
LGTM
