### ISSUE TITLE
package_list on package manager not ok 

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#279]
![image](https://user-images.githubusercontent.com/6021844/69779267-b3161180-11a7-11ea-946b-bb3f6917be22.png)

why this frontend in meta.toml

need to use package.toml & discuss with Kristof how we will do

I think should be using our registry not this frontend thing

**Comment by xmonader** [comment]
75cb77493739e9e96e6f2bb8797cc163ce18738c
original issue: https://github.com/threefoldtech/jumpscale

I don't think it's related to Registery, it's about the packages we show their UI in the 3bot, the suggestion was all the packages that has `frontend` directory are `frontend` packages

**Comment by john-kheir** [comment]
1- Got a gedis client
2- Added registry package 
3- Made sure i can list the packages
```
JSX> cl =  j.clients.gedis.get("hamada", port=8901)                                                                                                             
JSX> cl.actors.package_manager.package_add(path="/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/registry")                      
^[[AHUP 29466
b'OK'

JSX> cl.actors.package_manager.packages_list()                                                                                                                  
## actors.zerobot.packagemanager.package_manager.packages_list.cfce8bcb494e152552a9b2dc31c273eb
 - packages            :
```
