### ISSUE TITLE
package_manager core actor -> package

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#282]
![image](https://user-images.githubusercontent.com/6021844/69779419-45b6b080-11a8-11ea-85f3-97d7ef2cedba.png)

- [x] move to package as described below
- [ ]update wiki pages underneath

## implementation instructions

- move to: /sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/packagemanager

**Comment by xmonader** [comment]
Moved into packagemanager package
