### ISSUE TITLE
chatbot actor to package

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#284]
![image](https://user-images.githubusercontent.com/6021844/69779514-8e6e6980-11a8-11ea-925f-9c58356084be.png)

**Comment by despiegk** [comment]
in chatbot right package

**Comment by xmonader** [comment]
Right now it's part of zerbot/base package.

**Comment by Dinaamagdy** [comment]
can't find chatbot on  base actors on developemnt branch
but I can find it in this commit
https://github.com/threefoldtech/jumpscaleX_threebot/blob/87875f5b1cbeba6d78dea8ef6b6cf0f9d01718ad/ThreeBotPackages/zerobot/base/actors/chatbot.py

**Comment by xmonader** [comment]
It's in webinterface/actors now.

**Comment by john-kheir** [comment]
Verified
