### ISSUE TITLE
team.py core actor move to package

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#285]
![image](https://user-images.githubusercontent.com/6021844/69779389-2f105980-11a8-11ea-9946-db8ef85178a2.png)

same for 
/sandbox/code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/servers/threebot/base_actors/community.py

move to a new package, ask Kristof for review

**Comment by xmonader** [comment]
moved into zerobot/base package
