### ISSUE TITLE
gpdf macro to embed pdf in wiki pages

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#300]
gpdf should embed pdf viewer in the wiki page

**Comment by xmonader** [comment]
implemented here https://github.com/threefoldtech/jumpscaleX_threebot/commit/727e9b3ffae142a37629e13e806d3bf9ec3b1408

**Comment by john-kheir** [comment]
### Verification steps
1- Setup gdrive credentials
https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/wikis/tech#setting-up-gdrive-and-service-account

2- Run a wiki with gpdf macro in any document (you can run wiki_examples package)

3- Go to (ip container)/zerobot/wiki_examples/wiki and then to pdf documents and make sure you can view the documents.
