### ISSUE TITLE
allow packages to have multiple wikis [development_web]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#302]
- package can have multiple wikis in directory `wikis`
- wikis are on `3botIP/$3botauthor/$package_name/wiki` endpoint
- specific wiki is on `3botIP/$3botauthor/$package_name/wiki/$wiki_name` endpoint

**Comment by ranatrk** [comment]
Wiki directory in a package can consist of one of the following:
1. One wiki where its contents are in wiki directory directly in the package. eg: `/$package_name/wiki/README.md`. 
**The wiki name will be the same as the package name AUTHOR.PACKAGE_NAME**
2. One or more wikis can exist, where the content of each wiki will be inside a nested directory with the wiki name. eg: `/$package_name/wiki/$wiki_name/README.md`
**The wiki name will be the same as the internal directory inside wiki**

https://github.com/threefoldtech/jumpscaleX_core/commit/7d9a3ccee81f2422d014bb20027b32ef39041955
_**note: The two options cannot exist together, the default will be the first option and if there is no README, then any directories will be considered seperate wikis inside the package**_

**Comment by ranatrk** [comment]
Steps for veriying:

**Comment by john-kheir** [comment]
Verified
