### ISSUE TITLE
Need clear docs for wikis and fix wrong links

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#310]
- the location of current wikis loaction not clear.
- the exist one here https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/zerobot/webinterface/wiki/wikis , not clear and have wrong links

**Comment by abom** [comment]
Wiki documentation are updated here
https://github.com/threefoldtech/jumpscaleX_threebot/blob/development_fixes2/docs/wikis/tech/README.md.

**Comment by Dinaamagdy** [comment]
verified and did small edit there https://github.com/threefoldtech/jumpscaleX_threebot/pull/331
