### ISSUE TITLE
need to update webinterface tests [development_fixes_2]

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#316]
#### web_interfaces tests here need to be updates to be applicable with the new changes  
https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/zerobot/webinterface/package.py#L72

**Comment by ranatrk** [comment]
**Issue**: the functions in the package.py class in webinterface are not accessible from the package

**Comment by xmonader** [comment]
@ranatrk try using jslocation for that package and do jsx generate

**Comment by ranatrk** [comment]
> @ranatrk try using jslocation for that package and do jsx generate

@xmonader a jslocation can't be added to a Package directly.

**Comment by ranatrk** [comment]
WIP: changing the flow of the test as many things should be changed:
- using bcdbfs
- testing gedis http

**Comment by ranatrk** [comment]
Fixes done in test_package used in the web interface test:
https://github.com/threefoldtech/jumpscaleX_core/commit/6df9fcd1c7007a3987bf33988cb75abcb06b6e29

**Comment by ranatrk** [comment]
test now accessible from `j.tools.packages.webinterface.test()`
https://github.com/threefoldtech/jumpscaleX_threebot/commit/8073c1d95aa9a98eb6e592e81b9ac4d6c52bc669
