### ISSUE TITLE
Support serving generic wikis

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_threebot#325]
Support loading and serving wikis without packages:

- [x] get back `jsx wiki-load` to work with threegit.
- [x] get back the generic wiki handler which loads wiki by name from `/docsites`.

**Comment by abom** [comment]
Updated the code to use threegit instead of markdowndocs, still facing some problems with actors and myjobs.wait, trying to test `jsx wiki-load` with `-f`.

**Comment by abom** [comment]
Now wikis can be accessed as `/wiki/<wiki_name>` directly.

**Comment by abom** [comment]
Also, `jsx wiki-load` works again and using `threegit` instead of `markdowndocs`, and it accepts `-n` for name, `-u` for URL or path and `-r` for reset flag (to process all files again).

By default, it uses myjobs in background, to do in in foreground, use `-f` flag, example using all options:


```
jsx wiki-load -n foundation -u https://github.com/threefoldfoundation/info_foundation/ -f -r
```

**Comment by abom** [comment]
Also, wiki-reload is using threegit now too (https://github.com/threefoldtech/jumpscaleX_core/commit/ceab6a3c1b1b001def6ce9c4ee99891d7ddc1cf4)

```
jsx wiki-reload -n foundation -r
```

**Comment by john-kheir** [comment]
Verified
