### ISSUE TITLE
repo does not cloned when use git_url in threebot_packages method 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_threebot#33]
![image](https://user-images.githubusercontent.com/21987477/65035934-9ad57b00-d94a-11e9-8961-8ad0b3e96ad2.png)

3BOTDEVEL:jsx:~: ls /sandbox/code/github/
bettertoken  freeflownation  harvested-io  threefoldfoundation  threefoldtech

![image](https://user-images.githubusercontent.com/21987477/65035961-a88b0080-d94a-11e9-99f7-802e4265b01a.png)

- js version 
```
3BOTDEVEL:jsx:jumpscaleX_core: git log -1
commit d7b15db3f24010e34b5d94dbffe424ecca179257 (HEAD -> development, origin/development, origin/HEAD)
Author: Waleed Hammam <waleed.hammam@gmail.com>
Date:   Tue Sep 17 12:49:32 2019 +0200

    fix validate file name in salFS
```

**Comment by abom** [comment]
@Pishoy  i think it's `giturl` not `git_url`?

**Comment by Pishoy** [comment]
correct but please update docs to correct one https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/servers/threebot

**Comment by serboctor** [comment]
Fixed by https://github.com/threefoldtech/jumpscaleX_core/commit/c86b824134aa974fdc9c93a295b3253b75331235

**Comment by Pishoy** [comment]
verified
