### ISSUE TITLE
update script to deploy 3bot infrasturcture

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#333]
[development_deploy_infrasturcture]
update script in https://github.com/threefoldtech/jumpscaleX_threebot/blob/f285d79695ba4b667111c0b316347d816793725d/scripts/setupinfra.py

- prev issue https://github.com/threefoldtech/jumpscaleX_threebot/issues/50

**Comment by ranatrk** [comment]
[development_deploy_infrasturcture]
Items working: 
- installation wireguard with js
- droplet creations on DO
- js installation

still script changes are WIP, and still didnt test anything using threebot as threebot server is still not working

https://github.com/threefoldtech/jumpscaleX_threebot/commit/f59e4910b0c2fa1e72e4c2bceba7560918339000

**Comment by ranatrk** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/commit/4adbe77e71a374775394bbb9dd8bc990db4072f7
https://github.com/threefoldtech/jumpscaleX_libs/commit/3269db9bcb4a6b14ca84df1662e8d11f66322f91

**Comment by ranatrk** [comment]
The script is now working, and the wireguard configs are created correctly. Need to verify more details so will do further testing and debugging.
https://github.com/threefoldtech/jumpscaleX_core/commit/88abc8729f1b843aade164fd6141350d13732919
https://github.com/threefoldtech/jumpscaleX_threebot/commit/7b59b711d47cf25ab2cd631a743c170e2acd6aec

**Comment by ranatrk** [comment]
The script is used to deploy 3 machines from the main machine where explorer is running. Similar to the architecture mentioned in the previous issue.
To verify : 
- Edit the `project_name` in the script to not replace existing digital ocean machines
- On a digital ocean machine with js, create a digital ocean client manually before running the script with the name "main":
   ```
   j.clients.digitalocean.get("main",token_="TOKEN",project_name="PROJECT_TEST_NAME")
    ```
- run script on the main digital ocean using `kosmos -p '/sandbox/code/github/threefoldtech/jumpscaleX_threebot/scripts/setupinfra.py'
`
The explorer should be running in tmux in the main machine

**Comment by Dina-Abd-Elrahman** [comment]
- the three created droplets don't have redis installed on it.

**Comment by ranatrk** [comment]
This was due to an error that was not triggered where `/sandbox/var/redis` directory was not created. **Fix**: https://github.com/threefoldtech/jumpscaleX_threebot/commit/4a5657137d0937065afb56aa9eac06d56ab80813

**Comment by Dina-Abd-Elrahman** [comment]
- verified
