### ISSUE TITLE
need to call install/start multiple times to write locations on nginx

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#337]
starting 3bot sever

# steps
- `watch -n 0.1 /sandbox/cfg/nginx/default_openresty_threebot/servers/website_80_locations`
- `j.servers.threebot.local_start_explorer()`

You won't find chat_static or wiki_static locations

```
JSX> j.threebot.packages.zerobot.webinterface.install()        
JSX> j.threebot.packages.zerobot.webinterface.start()  
```

![image](https://user-images.githubusercontent.com/64129/72332363-96d02480-36c2-11ea-9f49-ba61aba3448f.png)

- start webinterface again `j.threebot.packages.zerobot.webinterface.start()`

![image](https://user-images.githubusercontent.com/64129/72332440-b8311080-36c2-11ea-875a-1534e600fd46.png)

**Comment by xmonader** [comment]
broken list iter implementation https://github.com/threefoldtech/jumpscaleX_core/commit/a38dc2eda1d6745166cbe8a18357580901184858 (Fixed on development)

**Comment by Dinaamagdy** [comment]
verified on development branch
