### ISSUE TITLE
Can't invoke actor method directly

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtech/jumpscaleX_threebot#345]
we can't directly access the actors like this
https://github.com/threefoldtech/jumpscaleX_threebot/blob/ebf8c854df0dc230e705b1a7473585227585dd17/ThreeBotPackages/zerobot/webinterface/bottle/gedis.py#L82

instead it should go through gedis server otherwise the schema out wont be loaded inside the method

**Comment by RafyAmgadBenjamin** [comment]
**Can't reproduce**
* get actor ```actor = j.threebot.actor_get(author3bot="tfgrid", package_name="directory", actor_name="nodes")```

* list actors ```actor.list()```

**Make sure that the package you are using is loaded first**

![image](https://user-images.githubusercontent.com/46320202/72892309-df20bf80-3d1e-11ea-887d-cc842aa88a05.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
