### ISSUE TITLE
info endpoint to show websites [development_web103]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#362]
/info to show websites as well

**Comment by serboctor** [comment]
Fixed here https://github.com/threefoldtech/jumpscaleX_threebot/commit/274f4c4a69fe6e84106b437e26d10ccc1296f04b
Now the /threefold/info page shows the website link for packages that are also websites 

![Screenshot from 2020-02-05 10-02-12](https://user-images.githubusercontent.com/6323012/73822393-aa246a80-47fe-11ea-89ae-54861f3a7877.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
