### ISSUE TITLE
improve searching in alerta

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#365]
it doesn't work with case insensitive search, doesn't allow filtering by date,
![image](https://user-images.githubusercontent.com/64129/74210281-be031d00-4c93-11ea-8d56-97f6db728cef.png)

**Comment by abom** [comment]
Now search is done inside every value of the table.

Added in https://github.com/threefoldtech/jumpscaleX_threebot/commit/7be0af61342992896515991a58d80ac271920b5f.

**Comment by hossnys** [comment]
verified that search in every value inside the table , search textbox is forcing lower case letters .
but search textbox doesn't trim the input text , so if you are searching for existing data but with suffix space (by fault) it'll not show any data .
![Screenshot from 2020-02-12 09-46-11](https://user-images.githubusercontent.com/26298009/74314886-f6335a00-4d7e-11ea-9103-5b4f2c37e5ff.png)

![Screenshot from 2020-02-12 10-06-43](https://user-images.githubusercontent.com/26298009/74315014-372b6e80-4d7f-11ea-8cfa-108aa7bf7b24.png)

**Comment by abom** [comment]
Fixed search at https://github.com/threefoldtech/jumpscaleX_threebot/commit/744876ba3bec194a0f357e0354b32ac7ee10864f.

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-02-12 12-23-13](https://user-images.githubusercontent.com/26298009/74325974-47007e00-4d92-11ea-9f2a-3b9cfaf499df.png)

![Screenshot from 2020-02-12 12-22-18](https://user-images.githubusercontent.com/26298009/74325936-2d5f3680-4d92-11ea-8121-b6dd8f3742be.png)
