### ISSUE TITLE
update alerta application name [unstable]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#368]
right now the alerta is the directory name and in the source.toml it's alerta_ui. let's unify it to `alerta` and rebuild the frontend

**Comment by hossnys** [comment]
there is a typo in alerta nav bar "cenral" to be "central "
![Screenshot from 2020-02-11 12-58-15](https://user-images.githubusercontent.com/26298009/74231351-160b4500-4ccf-11ea-8615-122bd0fbe4ea.png)

**Comment by abom** [comment]
Updated at  https://github.com/threefoldtech/jumpscaleX_core/commit/224a233d5d704d5adeb7ffa48d0176eb578fc42f , https://github.com/threefoldtech/jumpscaleX_threebot/commit/7be0af61342992896515991a58d80ac271920b5f and https://github.com/threefoldtech/jumpscaleX_threebot/commit/21954e6d631e964772bc6b957c36dff91830bf91.

**Comment by hossnys** [comment]
verified on branch unstable 

![Screenshot from 2020-02-12 09-56-24](https://user-images.githubusercontent.com/26298009/74314282-d94a5700-4d7d-11ea-8f8e-b6c255ed5807.png)
