### ISSUE TITLE
Adapt the chat flow so it generate the reservation schema and send it to BCDB 

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#369]
Task from story: https://github.com/threefoldtech/home/issues/419

**Comment by BolaNasr** [comment]
My Approach : 
chatflow will be like that after 3bot login (mail/username) : 
![image](https://user-images.githubusercontent.com/10259267/74324717-1a4b6700-4d90-11ea-9070-f77928c971e1.png)
Then ask user about:
- his pub ssh-key
- user/password corex
- time / duration of up

after finish i will show to user 
- how to access using IP and port 
- how to configure his wire-guard 
- how to connect using ssh 

i will use like this behaviour https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid/provision_examples/ubuntu_ssh.py to create container and reservation through actor ( workloads) 

@zaibon  can review it please

**Comment by zaibon** [comment]
What is planned regarding network creation ?
Before you can deploy a container, the user needs to have defined a network. So you know which IP you need to assign to the container.

Other then that, the current approach looks ok. Maybe except regarding the duration. I would just set it to a year or something for now. Until we have money flow implemented.

**Comment by rkhamis** [comment]
Why don't we auto assign IPs and give the wireguard config to the user. less chances of things going wrong that way

**Comment by zaibon** [comment]
There is only so much you can guess from the user infrastructure.
The user must at least gives the /16 subnet he wants to use for it's network.
The rest can be deducted from there and generate a "standard" network configuration.
And keep in mind that as soon as you remove the possibility to do IP management from the user, you have to do it...Which mean keeping track of what ip is handed to which container etc...This becomes messy very fast specially in cases where this chat bot is something anyone could use.

**Comment by BolaNasr** [comment]
now we need to decide on the approach of the signature of the resever's threebot, because having a central chatflow motherbot means the request is always signed by the motherbot's private key.
@zaibon  @rkhamis

**Comment by zaibon** [comment]
I've been trying to find a solution but I do not thing we have what would be require to allow users to sign the transaction. But since we need to have something working asap. Let's do the following.

The reservation will be signed and most probably paid by the 3bot running the chat flow.
This avoid to have to make the user sign but still allow to create a network that only the user can access.
