### ISSUE TITLE
Update threebot docs 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#371]
some docs need to be updated 
- myjobs 
- alerta
- blogs 
- pastebin 

this links 
https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs#complete-examples

**Comment by RafyAmgadBenjamin** [comment]
update alerts docs
### commit
https://github.com/threefoldtech/jumpscaleX_threebot/commit/47dd1b60e1ec95e82e9d38a381a85a2b5e53aaed
https://github.com/threefoldtech/jumpscaleX_threebot/commit/3e276b4cd3c0d81c0161ddaa354d822ebc385033

update myjobs docs
### commit
https://github.com/threefoldtech/jumpscaleX_threebot/commit/9c92d7054e0d35c30a15ce6f9c38a61b2f31296c

pastepin docs will be left per my discussion with @xmonader  as this package is archived

**Comment by xmonader** [comment]
not valid anymore.
