### ISSUE TITLE
workers fail after start threebot server 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#372]
## Steps 
- start threebot server 
j.server.threebot.start(background=True)

## Issue 
check workers in tmux will find them fail with the follwoing error 
![image](https://user-images.githubusercontent.com/24386802/74437105-43dbbf80-4e70-11ea-87f3-b09d4edd9805.png)

![image](https://user-images.githubusercontent.com/24386802/74437163-5ce47080-4e70-11ea-9ae8-67b042b4f2d9.png)

**Comment by rkhamis** [comment]
obsolete
