### ISSUE TITLE
wrong url on view wiki in the wiki pages 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#377]
Make sure to keep track of the docs url to go to the correct docs

e.g 

![image](https://user-images.githubusercontent.com/64129/74589019-4eca5780-500a-11ea-9935-061dd062b64f.png)

should go to http://165.22.206.215/wiki/info_foundation#/docs/readme.md
and not http://165.22.206.215/wiki/info_foundation

**Comment by waleedhammam** [comment]
this is caused by loading wrong url ex: https://github.com/threefoldfoundation/info_tokens should be 
https://github.com/threefoldfoundation/info_tokens/tree/development/docs

**Comment by waleedhammam** [comment]
unified at: https://github.com/threefoldtech/jumpscaleX_core/commit/7d8d9615bd1111c8cee78946d84b95e96553ce4f, https://github.com/threefoldtech/jumpscaleX_threebot/commit/af01647597ffee13224ca4ba699dfe7d9acab220

**Comment by hossnys** [comment]
verified on branch unstable ,
verification steps : 
follow steps [here](https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/docs/wikis/tech/quickstart.md#threefold-wikis)

![Screenshot from 2020-02-16 16-40-26](https://user-images.githubusercontent.com/26298009/74606700-4aba3a80-50db-11ea-8dfd-d325df3fe49e.png)
