### ISSUE TITLE
links should be case insensitive [unstable]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#378]
![image](https://user-images.githubusercontent.com/64129/74589061-bb455680-500a-11ea-937c-17f089840520.png)

please make matching on teal/Teal/TEAL the same. Don't bother if there're other entries with the same name

**Comment by waleedhammam** [comment]
- Got a problem with Github custom links 
example:
- `[link](jumpscaleX_threebot:readme)` would yields `jumpscalex_threebot` with small case which is not an existing repo
- Cleaning links converts it to snake case so can lead to files corruption ex: `SomeCode.md` will turned into `some_code.md`

**Comment by despiegk** [comment]
I will rewrite the linker, enough time lost
