### ISSUE TITLE
fileserver package for the threebot

### ISSUE THREAD

**Issue by zgorizzo69** [threefoldtech/jumpscaleX_threebot#38]
Create a fileserver  package based on webdav  under jumpscaleX_threebot/ThreeBotPackages/threebot/fileserver

# storie
As a 3bot owner I want to display and manage(add,modify,delete) my user files through the web so that my data will be stored on my 3bot and made accessible from the web

There already inside the folder a webdav implementation and a filemanger_UI.
The package should leverage those to instantiate the webdav server and serve the front website to manage the files

Here the 3bot will launch the server (webdav) and serve the front (filemanager_ui)

- [x] actors
   - [ ] do we need something here ?

- [ ] UI on 3bot app
  - [x] filemanager_ui
  - [x] make sure the package install will trigger the filemanager_ui install
  - [ ] move the static folder under filemanager_UI on another repo and make the package pull the files from that repo  instead of having all the static files inside the threebot repo

- [x] webdav server
  - [x] make sure it is working
  - [x] make sure the package install will trigger the webdav install
  - [x] extract the schemas and put them into a toml files under threebotpackages/threebot/fileserver/models - already in jumpscaleX_core/JumpscaleCore/data/bcdb/models_threebot

- [x] Deployment
  - [x] package.py
  - [x] package factory
  - [x] start paramaterized 

- [ ] Bugs
  - [ ] file created date is not accurate it show 50years in the UI
  - [ ] make the exists function return false when a path has been deleted
  - [ ] content of file is not shown inside the UI

- [ ] Testing
  - [ ] create/update/delete/get files
  - [ ] search files
  - [ ] access the filemanager_ui from a browser

**Comment by zgorizzo69** [comment]
do we need the actor's file for this one ?

**Comment by zgorizzo69** [comment]
![image](https://user-images.githubusercontent.com/16853695/65337385-4fc89b80-dbc8-11e9-9efd-0c5f1180057f.png)
Can this work like this ?

**Comment by rkhamis** [comment]
Currently, it's all done in the app. can indeed by refactored in an actor, but wouldn't consider this to be top priority. The complete testing will have to be done, of course to make sure the story is satisfied

**Comment by zgorizzo69** [comment]
> Currently, it's all done in the app. can indeed by refactored in an actor, but wouldn't consider this to be top priority. The complete testing will have to be done, of course to make sure the story is satisfied

ok will check what the priority is for this one

**Comment by zgorizzo69** [comment]
I will add a low priority for the move the static folder under filemanager_UI on another repo  
because I don't know what repo we should use. We should create a repo for all the static files that we need
