### ISSUE TITLE
full reset doesn't clean the output docsify dir

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#380]
make sure when flag reset used to start on clean slate without files from before.

**Comment by waleedhammam** [comment]
This was caused of wrong links should be resolved by https://github.com/threefoldtech/jumpscaleX_threebot/issues/377

![image](https://user-images.githubusercontent.com/10658229/74608146-60cdf800-50e7-11ea-9f22-4de92887db7f.png)

In code it directly deletes the output dir

**Comment by hossnys** [comment]
verified on branch unstable :
verification steps : 
- create test.md file in any of docsite directory sub-folders , e.g info_grid :

![Screenshot from 2020-02-17 15-36-52](https://user-images.githubusercontent.com/26298009/74659115-65a0b380-519c-11ea-9f5c-80caeb75aa5c.png)

- then do ``` jsx wiki-load -r``` and you will notice that the created file was deleted 

![Screenshot from 2020-02-17 15-37-33](https://user-images.githubusercontent.com/26298009/74659225-9c76c980-519c-11ea-80ad-07a2d63d1e45.png)

**Comment by Dina-Abd-Elrahman** [comment]
- `jsx wiki-load -r` doesn't reset at all. 

- steps for reproduce:
touch a file in the docsite dir. /sandbox/var/docsites/info_grid
start threebot server.
then , reload wikis `jsx wiki-load -r`

- Check again for files, I found the just created file exists.

**Comment by abom** [comment]
@Dina-Abd-Elrahman Did you wait for this command to finish? can you please verify with a single repo?

```
jsx wiki-load -r
```

Would do it for many wikis, and you have to wait for long time before it's done, verify with a single wiki if possible.

If it does not work with you after doing `jsx wiki-load -r` without any arguments, then, maybe we had an issue in this command when doing it for multiple wikis (as me and @waleedhammam already tested a single wiki and it worked).

**Comment by Dina-Abd-Elrahman** [comment]
I tried this scenario and it's working correctly:

- start 3bot server. 
- load the wiki certain repo. 
- change in the repo ( add certain file) 
- reload the wiki. 
- check for existence of  the file which i just added
