### ISSUE TITLE
grid, info_grid both docsites exist

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#381]
![image](https://user-images.githubusercontent.com/64129/74600863-f6459980-509f-11ea-9acd-925e6958a3ce.png)

after installing threefold.wikis package i found out there're info_grid, and grid docsites  and both are referenced in the `/wiki/` endpoint. and only `grid` works.

**Comment by waleedhammam** [comment]
resolved in https://github.com/threefoldtech/jumpscaleX_threebot/issues/377
![image](https://user-images.githubusercontent.com/10658229/74603571-70d0e200-50bd-11ea-8054-7adff6b662dc.png)

**Comment by hossnys** [comment]
verified on branch unstable 
now in wikis page you can just see info_grid and it works fine .

![Screenshot from 2020-02-16 16-47-34](https://user-images.githubusercontent.com/26298009/74606909-ff089080-50dc-11ea-8c20-a2808c7dcfc9.png)

![Screenshot from 2020-02-16 16-56-32](https://user-images.githubusercontent.com/26298009/74606923-252e3080-50dd-11ea-98c8-1031d7cc7d1d.png)
