### ISSUE TITLE
Reservation model uses reserved word "json" as a property name

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtech/jumpscaleX_threebot#382]
https://github.com/threefoldtech/jumpscaleX_threebot/blob/dfde9b9758d18a8334095db4538999521e60341a/ThreeBotPackages/tfgrid/workloads/models/tfgrid_workloads_reservation_1.toml#L2-L7

This will override _json property which returns the json representation of the object which I guess the same result expected from json property in the model

**Comment by zaibon** [comment]
How does a property call `json` overwrite another property called `_json` ?

**Comment by andrewayoub** [comment]
https://github.com/threefoldtech/jumpscaleX_core/blob/31642f4863ffc48cd48168d81766745bdbd4148d/JumpscaleCore/data/schema/templates/JSXObject2.py#L11-L12

for each property in the schema this code will create `_{property_name}` to be used for the setter and getter

**Comment by zaibon** [comment]
I see, the bug I got make sense now.
So I think there are 2 things to be done here:
- Document very clearly what are the reserved keywords that cannot be used on a model
- Implement a check in the model that raises an exception if a reserved keyword is used in a model so the developer knows early on that he needs to modify it's field name.
