### ISSUE TITLE
local_start_explorer doesn't install the packages required for the directory

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#384]
I tried to deploy a new explorer from scratch using development branch.
After the installation of jumpscale itself, I tried to start the explorer with `kosmos -p "j.servers.threebot.local_start_explorer(background=True, with_shell=False)"`
Result of this commands starts the 3bot server, but none of the package from the explorer are installed.
The packages that should be automatically installed are:
```
tfgrid/phonebook
tfgrid/directory
tfgrid/workloads
```

**Comment by abom** [comment]
Should be fixed by this

https://github.com/threefoldtech/jumpscaleX_core/pull/540

**Comment by hossnys** [comment]
verified on branch unstable_hotfix_threebot
steps :
```
 kosmos -p "j.servers.threebot.local_start_explorer(background=True, with_shell=False)"
```
and go to ```https://3bot_container_ip/zerobot/packagemanager/```

you should see these packages loaded by default :
- tfgrid/phonebook 
- tfgrid/directory
- tfgrid/workloads

![Screenshot from 2020-02-18 17-20-25](https://user-images.githubusercontent.com/26298009/74749793-5fc9d180-5273-11ea-843c-8b8d47f06889.png)
