### ISSUE TITLE
threebot identity actor needs updating

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_threebot#388]
https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/zerobot/webinterface/actors/identity.py 

 - needs to ensure that the threebot,me has been inited properly.
 - should have the instance name as a parameter (`default` by default)
 - should return threebot.me.<instance> information correctly

**Comment by serboctor** [comment]
Fixed here https://github.com/threefoldtech/jumpscaleX_threebot/commit/420afc7ca815c2cbcc0c33854efdbbd9ff59aa6c 
![Screenshot from 2020-02-25 17-13-16](https://user-images.githubusercontent.com/6323012/75260493-5c45c580-57f2-11ea-92ac-8a0ffb57e99d.png)
