### ISSUE TITLE
workloadmanager: signature validation is done on the json part set by the user, not the actual data_reservation

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/jumpscaleX_threebot#390]
In this line we see that the signature validation check is done on the `reservation.json` property here https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid/workloads/actors/workload_manager.py#L181

The problem now is that I can get any signed message that has been previously signed by the user (since they are public anyway), and then just put the message in `json` and the signature in place. then the verification will pass, but then I can put any other `reservation_data` that can be completely different from what is stored in `json`

This way a malicious user can deploy whatever he wants on behalf of other users.

**Comment by muhamadazmy** [comment]
Suggestion:
As a quick fix, we can unmarshal the json data and make sure it creates an exact copy of the `reservation_data` field.

**Comment by muhamadazmy** [comment]
Suggestion:
As a quick fix, we can unmarshal the json data and make sure it creates an exact copy of the `reservation_data` field.

**Comment by waleedhammam** [comment]
on branch `unstable` commit https://github.com/threefoldtech/jumpscaleX_threebot/commit/4e115cd3ed59bef1a2eac92d0cb463acc9f9db26

- added the quick fix suggestion, will need to do more tests to verify

![image](https://user-images.githubusercontent.com/10658229/75988053-abc67880-5ef9-11ea-81ae-2911ec6006c8.png)
