### ISSUE TITLE
update 3bot login to new release [development_3bot_login]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_threebot#399]
we need to update our 3bot login to follow the newest release of the 3bot connect.

see: https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/ThreeBotPackages/zerobot/webinterface/bottle/auth.py

**Comment by Hamdy** [comment]
fixed and merged into unstale, verified with @abom and @grimpy

**Comment by Hamdy** [comment]
Verified !
