### ISSUE TITLE
add logs to bottle gedis http server [development_hotlogs]

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_threebot#427]
- we should be able to see logs from gedis http calls
located in https://github.com/threefoldtech/jumpscaleX_threebot/blob/c7d64def8092803c4c4fdac95930cd4d929e7b2c/ThreeBotPackages/zerobot/webinterface/bottle/gedis.py

**Comment by waleedhammam** [comment]
add at: https://github.com/threefoldtech/jumpscaleX_threebot/pull/428

example logs:

![Screenshot from 2020-03-16 17-25-51](https://user-images.githubusercontent.com/10658229/76773948-ef4b9d00-67ab-11ea-8643-0265d467ba8a.png)

**Comment by Dina-Abd-Elrahman** [comment]
- try to access https://172.17.0.2/tfgrid/directory/actors/nodes/list and check the logs from here 

`js_logs -a bottle_server tail`

![ff](https://user-images.githubusercontent.com/21218053/76853033-3a6dba80-6855-11ea-9f89-2625d587ff0b.png)

**Comment by grimpy** [comment]
currently all logs of threebotserver going to bottleserver this was not the intention

**Comment by waleedhammam** [comment]
There's a problem in j.application.start, it doesn't reset the context after application is done, working on implementing it ..

**Comment by waleedhammam** [comment]
Added context reset to j.application at:

https://github.com/threefoldtech/jumpscaleX_core/pull/625/files
https://github.com/threefoldtech/jumpscaleX_threebot/pull/438/files
https://github.com/threefoldtech/jumpscaleX_libs_extra/pull/24/files

and updated docs here https://github.com/threefoldtech/jumpscaleX_core/blob/5023f3d967023df5a50f88567b628d6c1f96e1f5/docs/logger/README.md#logging-mechanism

- To define app we use for example: j.application.start("threebotserver") add this to your application init

- at the end of application make sure to j.application.reset_context() to reset the log context to the previous application

to make sure  logs goes to the right context

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
