### ISSUE TITLE
add an entry in the sidebar of admin panel for chatflows deployment [development_tfchatflows]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#437]
https://github.com/threefoldtech/home/issues/525

just place holder for these chatflows (make sure to load chatflows of tfgrid_solutions packages)

 - ubuntu 
 - Generic flist
 - Minio/S3
 - K8S cluster
 - threebot -> threebot_reservation

**Comment by abom** [comment]
Now the UI for chatflows inside admin dashboard is ready, but there is a problem when installing any chatflow package, it cannot load the chatflows directory after refresh, and it needs a threebot server restart.

**Comment by abom** [comment]
Fixed the loading problem at https://github.com/threefoldtech/jumpscaleX_core/pull/628.

**Comment by abom** [comment]
It's done now, also, we only allow chatflows of tfgrid_solutions to admins only.

`development_tfchatflows` on core, threebot and libs.

**Comment by Dina-Abd-Elrahman** [comment]
verified.
