### ISSUE TITLE
hardcoded IP in gateway actor `domain_tcpservice_client_expose`

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#441]
https://github.com/threefoldtech/jumpscaleX_threebot/blob/1d92831f1be1d2bee1d38be6a78028659520ce9b/ThreeBotPackages/tfgrid/gateway/actors/gateway.py#L325

```python
    @j.baseclasses.actor_method
    def domain_tcpservice_client_expose(
        self, threebot_name, client_secret, signature, schema_out=None, user_session=None
    ):
        """
        Registers a domain in coredns (needs to be authoritative)

        ```in
        threebot_name = (S) # 3bot threebot_name
        client_secret = (S)
        signature = (S) #the signature of the payload "{threebot_name}"
        ```
        """
        result = self.explorer.actors.phonebook.validate_signature(
            name=threebot_name, payload=threebot_name, signature=signature
        )
        if not result.is_valid:
            raise j.exceptions.Value("Invalid signature")

        fqdn = f"{threebot_name}.{THREEBOT_DOMAIN}"
        self._gateway.tcpservice_register(fqdn, client_secret=client_secret)
        self._gateway.domain_register_a(threebot_name, f"{THREEBOT_DOMAIN}", "165.227.201.194")  # TODO remove fixed ip
        return True

```

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
