### ISSUE TITLE
default values needs to show in the spinbox in chatflows

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#454]
![image](https://user-images.githubusercontent.com/64129/77145512-72614180-6a91-11ea-8ebe-86f0d7295e79.png)

here asks if unsure to 2048 but the spinbox is ""

**Comment by ranatrk** [comment]
Fix on [unstable]: https://github.com/threefoldtech/jumpscaleX_threebot/commit/ca8ad2fec1d10f541020f5430da75cfe876eeba1

**Comment by john-kheir** [comment]
Verified
