### ISSUE TITLE
don't show product x been deployed in chatflow without verifying reservation on explorer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#455]
![image](https://user-images.githubusercontent.com/64129/77146357-8b6af200-6a93-11ea-9deb-4c9c11e37d20.png)
![image](https://user-images.githubusercontent.com/64129/77146390-9c1b6800-6a93-11ea-8631-25b7e49a95a2.png)

- [x] ubuntu
- [x] your flist
- [x] minio
- [x] k8s
- [x] threebot_reservation

**Comment by xmonader** [comment]
check threefoldtech/jumpscaleX_libs@cedf3ede7ba02dd37f5fe389b496ff021387daf0

**Comment by BolaNasr** [comment]
Fixed in commit [unstable] [ threebot] https://github.com/threefoldtech/jumpscaleX_threebot/commit/b98dd1a4eb5a9f29d18030b647f3eb1c307069e6 

Fixed in commit [unstable] [ libs] https://github.com/threefoldtech/jumpscaleX_libs/commit/207a557b6b6b12be7dfc96475df7a658444bb567

**Comment by john-kheir** [comment]
Verified
