### ISSUE TITLE
Farmmanagement package has dependencies in cockpit [farmmanagement_fix]

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/jumpscaleX_threebot#456]
When trying to run the farm management package in the front-end, there are dependencies in the cockpit package. This means that farmmanagement cannot be used without cockpit. 

Possible fixes:
 - Make the datastore available for both packages
 - move the shared components back from shared to their own components

**Comment by xmonader** [comment]
Fixed in https://github.com/threefoldtech/jumpscaleX_threebot/pull/457
