### ISSUE TITLE
add a buttone to allow pulling wiki repository (like reload)

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_threebot#473]

**Comment by abom** [comment]
Added reload button at https://github.com/threefoldtech/jumpscaleX_threebot/commit/252b6beb73c52ed866a3fe7c94795916911b5198.

Go to `/wiki`, you can now pull any wiki repository. Make sure there're no local changes, otherwise, pulling will fail.

**Comment by hossnys** [comment]
verified on branch unstable :

![Screenshot from 2020-03-25 09-55-21](https://user-images.githubusercontent.com/26298009/77513933-8c7a9580-6e7e-11ea-8bda-008f53c18a7f.png)
