### ISSUE TITLE
An SMTP/IMAP package for threebot

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_threebot#48]
Create an email package based on smtp/imap  under /threebotpackages/threebot/email

# story
As a 3bot owner I want to be able to 
 - add an email account and sync it
 - create/send emails
 - attach files in my email
 - receive emails
 - search emails

I also expect to display and save  emails through the 3botApp so that my emails will be stored on my 3bot but still accessible from my 3bot app

As it is stored in bcdb we would also need models to be stored

Part | Layer | Protocol or Format
-- | -- | --
Server | Syncer | IMAP Server
Server | Email | SMTP

Here we ONLY focus on the server side as the front side will be done by the jimber guys as they are developing the 3bot app

- [x] IMAP server using BCDB
- [x] SMTP server using BCDB
- [x] Add models corresponding to the files stored

- [x] actors
    - [ ] put/get signature
    - [ ] automatically forward emails
        - [ ] get/put forward email  addresses ( multiple )
        - [ ] enable/disable forwarding 
    - [ ] out of office
        - [ ] get/put out of office email
        - [ ] enable/disable out of office ( with date ) 
        - [ ] import emails from external services ( func analysis needed )

- [ ] UI on 3bot app
    - [ ] list mails
        - [ ] add checkbox  
        - [ ] bulk delete emails  
        - [ ] add attachment chip in email list
    - [x] send email 
    - [ ] search emails
    - [ ] filter emails  ( subfolder in inbox )
        - [ ] starred emails  
        - [ ] unread emails  
    - [ ] context menu
        - [ ] layout  
        - [ ] add forward, reply, reply to all in context menu  
    - [ ] new email
        - [ ] make from, to, subject smaller and body larger
        - [ ] create full screen option
    - [ ] attachments
        - [ ] add (multiple ) attachments
        - [ ] delete attachments
        - [ ] show attachments
        - [ ] open/download attachments when clicking
    - [x] move to other folder
    - [ ] create new folder
    - [ ] create draft folder
    - [ ] save draft
    - [ ] improve caching  
    - [ ] settings page  
        - [ ] signature
        - [ ] automatically forward emails
        - [ ] out of office
        - [ ] import emails from external services ( func analysis needed )

- [ ] Deployment
  - [ ] package.py
  - [ ] package factory
  - [ ] start paramaterized 

- [ ] Testing
  - [ ] sync account
  - [ ]  send email with attachment
  - [ ]  display emails
  - [ ] search emails
  - [ ] delete emails

**Comment by rkhamis** [comment]
@grimpy @RafyAmgadBenjamin please link your work and update progress here

**Comment by grimpy** [comment]
IMAP work is being done at https://github.com/threefoldtech/jumpscaleX_libs/tree/development_imap/JumpscaleLibs/servers/mail

Currently basic functionality works for evolution/thunderbird there are still some caveats with attachements
