### ISSUE TITLE
error loading solutions from admin on using localhost:7000

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#482]
In the admin on a macbook, solution chatflow (here to create ubuntu) doesn't load because port not specified in the generated url. 

<img width="500" alt="Schermafbeelding 2020-03-27 om 07 49 10" src="https://user-images.githubusercontent.com/30384423/77732301-db523780-7004-11ea-9126-a04bc551a533.png">

**Comment by xmonader** [comment]
code fixed in gedis package client threefoldtech/jumpscaleX_weblibs@cb34dfb9cc85a6c084a3e8e84c4e67d511111102

Problem still with auth against localhost:7000
