### ISSUE TITLE
for all solutions chatflows show the wg configurations before wg-quick command

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#483]
we should show wg config to copy or to download then show wg-quick command not the other way around

**Comment by BolaNasr** [comment]
Fixed at https://github.com/threefoldtech/jumpscaleX_threebot/commit/852ed1aa41673a689b4b2bdb8ea831db4eb3e0f6

**Comment by john-kheir** [comment]
Verified
