### ISSUE TITLE
show the entered data for solution deployment to the user before sending the reservation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#484]
user should be able to review the data entered before sending the reservation

**Comment by alichaddad** [comment]
Check:
-https://github.com/threefoldtech/jumpscaleX_threebot/commit/a0620648ebd62e0c2d85f8b8fced1c426f56d069

-https://github.com/threefoldtech/jumpscaleX_core/commit/ab79ef7cfe443cb035a93ee118443b034b2f1709

**Comment by john-kheir** [comment]
Verified
