### ISSUE TITLE
code server package needs to be improved [unstable_fix1]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#485]
codeserver package needs to pull binary from right location 
https://github.com/cdr/code-server/releases

change package.py to have an install function in there which checks if the binary is there,if not download
ok to only work in ubuntu for now

**Comment by xmonader** [comment]
- binary should be in the docker image
- Prepare method added just in case the bin wasn't in the image

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/commit/11e105577df3355063d2aa9ddd548eb7ac398c01#diff-fbc36a60e68837719a49226f59c4265e
https://github.com/threefoldtech/jumpscaleX_threebot/commit/0b356c34b633cf8240a7c19bd2b01f2b911161f2#diff-fbc36a60e68837719a49226f59c4265e

**Comment by john-kheir** [comment]
Verified
