### ISSUE TITLE
when error e.g. in installing package there was no alert or even logs

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#487]
![image](https://user-images.githubusercontent.com/6021844/77842481-f488ee80-7192-11ea-9b20-786898653bc4.png)

tried to install the solution, it did not give an alert
yet still it clearly did not work

no-where we could see alert or log

**Comment by despiegk** [comment]
this happens for +- any package e.g. jupyter

**Comment by abom** [comment]
For solutions (chatflows), it seems like the error is not on the backend, did you pull `weblibs`?

**Comment by abom** [comment]
![Screenshot from 2020-03-29 10-46-42](https://user-images.githubusercontent.com/511438/77844889-96680580-71aa-11ea-9fb5-eef152c1d522.png)

**Comment by waleedhammam** [comment]
Also can see if errors happens

![Screenshot from 2020-03-29 12-07-29](https://user-images.githubusercontent.com/10658229/77846395-10ea5280-71b6-11ea-9199-8394eda930ac.png)

**Comment by waleedhammam** [comment]
installing packages now raises the errors
![image](https://user-images.githubusercontent.com/10658229/77887632-38e7bd80-726b-11ea-9b25-36f8d0b5e6ac.png)

**Comment by john-kheir** [comment]
failed to install codeserver package and can't see any logs or alerts related 
![codeserver_error](https://user-images.githubusercontent.com/15011431/78014458-3f983280-7348-11ea-95b8-77124b206065.png)

**Comment by john-kheir** [comment]
was a problem with my docker .. Verified

**Comment by abom** [comment]
Now if you tried to do any operation, and it failed, it would show an error in case this error is handled, otherwise it will log and create an alert.

For other packages, like chats...etc, it's up to show the error and in any format, for the package manager, it will show any related errors when doing any of its operations like `install`, `stop`, `enable` on any package.
