### ISSUE TITLE
delete of alerts does not work [unstable_fix1]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#488]
get 3bot by using jsx threebot

**Comment by waleedhammam** [comment]
Fixed at: https://github.com/threefoldtech/jumpscaleX_threebot/commit/7fcb658958dbf01957a90e40c7d0ebc6e44562dd

**Comment by john-kheir** [comment]
Verified on unstable_fix1 (core0, threebot)
