### ISSUE TITLE
packages cleanup in 3bot [unstable_fix1]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#489]
install a 3bot. using
```
jsx threebot
```
in a container

## deliverables

- [x] go over all packages, every package not relevant should be archived
- [x] make sure every package installs using nothing but the admin panel
    - there is no development env in the container and that is supposed to be like that
    - if anything missing in the container let Kristof know he will fix and rebuild
- [x] make sure start/stop works for all of them

# packages

## archived

archived the following
- [x] appstore
- [x] _bcdb_crud
- [x] calendar
- [x] contacts
- [x] core
- [x] demo
- [x] ffbrowser
- [x] ffconnect
- [x] filemanager
- [x] fileserver
- [x] helloworld
- [x] mail
- [x] oauth2
- [x] test_package
- [x] tft_explorer
- [x] vuejs
- [x] webhooks
- [x] webplatform_archived
- [x] initialize (archived)
- [x] Ibiza package  (archived)
- [x] token (archived)
- [x] gitea  (archived)
- [x] minecraft (archived)
- [x] odoo (archived)
- [x] taiga (archived)
- [x] wordpress (archived)
- [x] communityapp (archived)

## zerobot author

- [x] alerta package
- [x] Base package
- [x] chatbot_examples package (requires LOGIN) 
- [x] codeserver package
- [x] myjobs_ui package
- [x] wiki_example package
- [x] packgemanager package all the featuers work
- [x] admin package package
- [x] webinterface package
- [x] svelte all features work 
- [x] directory
- [x] dns
- [ ] gateway
- [x] network
- [x] phonebook
- [x] registration
- [x] registery
- [x] threebot_provisioning
- [x] workloads
- [x] any_flist
- [x] kubernetes_cluster
- [x] minio
- [x] ubuntu
- [x] blog crashed during installation 
- [x] capacity
- [x] farmmanagement
- [x] simplemail
- [x] simulator  crashed during installation ```Error has happened during this operation: {"error": ""}```
- [x] wikis

**Comment by waleedhammam** [comment]
Old packages or not used to be asked about

## Zerobot

- [ ] 
- [ ]

**Comment by waleedhammam** [comment]
Old packages, or to be asked about

## Zerobot:

- [ ] [_bcdb_crud](https://github.com/threefoldtech/jumpscaleX_threebot/tree/d554503976d981fb886db96a6f39bd1acce1ad9b/ThreeBotPackages/zerobot/_bcdb_crud)

- [ ] [food_multi.py](https://github.com/threefoldtech/jumpscaleX_threebot/blob/007f1b4bd713520ad9746bf034e701922806eddf/ThreeBotPackages/zerobot/chatbot_examples/chatflows/food_multi.py) chat in chatbot_examples

- [ ] [File manager](https://github.com/threefoldtech/jumpscaleX_threebot/tree/20e8e190d7f5cbe038aa59a6cc48d34d6fbbd12c/ThreeBotPackages/zerobot/filemanager)

- [ ] [webhooks](https://github.com/threefoldtech/jumpscaleX_threebot/tree/d554503976d981fb886db96a6f39bd1acce1ad9b/ThreeBotPackages/zerobot/webhooks)

**Comment by xmonader** [comment]
archived the following
- appstore
- _bcdb_crud
- calendar
- contacts
- core
- demo
- ffbrowser
- ffconnect
- filemanager
- fileserver
- helloworld
- mail
- oauth2
- test_package
- tft_explorer
- vuejs
- webhooks
- webplatform_archived

**Comment by RafyAmgadBenjamin** [comment]
### Summary of checking all the packages in all authors 
## zerobot author

**alerta package**
when i delete the package i still can see it in its tab and i have to clue that it is delete or even stopped 

**Base package**
all the features working nothing crashedes 

**chatbot_examples package**
all the features working nothing crashedes 

**codeserver package**
* all features work but when i stop this package and press on codeserver tab it give (bad gateway)

**myjobs_ui package**
* all the features working nothing crashedes 
* in myjobs_ui tab when the packge delete or stopped, it shows nothing or any indicator so it feels like it is working normal 


**wiki_example package** 
* all the features work

**packgemanager package**
* all the featuers work

**admin package package**
* all the featuers work

**webinterface package**
* all the featuers work

## jumpscale author
 
**Ibiza package**
crached during installation 

```Error has happened during this operation: {"error": "could not find name for bcdb in config of package, jumpscale.ibiza, found "}```

**svelte**
* all features work 

## tfgird

**directory**
* all the feautes work 

**dns**
* all the features work 

**gateway**
* crasheded during installation 
```Error has happened during this operation: {"error": "Failed to connect to 192.168.99.254"}```

**network**
* all the features work

**phonebook**
* all the features work 

**registeration**
* all the features work 

**registery**
* all the features work

**threebot_provisioning**
* all the feature work well 

**token**
* crashed during installation 
```Error has happened during this operation: {"error": "'BCDB' object has no attribute 'instances'"}```

**workloads**
* all the featues work 

**gittea**
* crashed during installation
```Error has happened during this operation: {"error": "could not find name for bcdb in config of package, tfgrid.gitea, found "}```

**minecraft**
* all the features working

**odoo**
* all the features working 

**taiga**
* crashed during installation
```Error has happened during this operation: {"error": "username and password are required"}```

**wordpress**
* all the features are working 

## tfgrid_solutions author

**any_flist**
* all the features are working 

**kubernetes_cluster**
* all the features working 

**minio**
* all the features working 

**ubuntu**
* all the features working 

## threebot author

**blog**
* crashed during installation 
```Error has happened during this operation: {"error": "could not find name for bcdb in config of package, threebot.blog, found "}```

**capacity**
* all the features working

**farmmanagement**
* all the features working

**initialize**
* crash during installation 
```Error has happened during this operation: {"error": "could not find name for bcdb in config of package, threebot.initialize, found "}```


## threefold author

**communityapp**
* crashed during installation 
```Error has happened during this operation: {"error": "could not find name for bcdb in config of package, threefold.communityapp, found "}```

**simplemail**
* crashed during installation
```Error has happened during this operation: {"error": "could not find name for bcdb in config of package, threefold.simplemail, found "}```

**simulator**
* crashed during installation
```Error has happened during this operation: {"error": ""}```

**tf_websites**
* crashed during installation
```Error has happened during this operation: {"error": "retried git pull too many times, failed"}```

**wikis**
* all the features working
