### ISSUE TITLE
codeserver did not install, yet it says its running, this cannot be

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#491]
![image](https://user-images.githubusercontent.com/6021844/77842741-42ebbc80-7196-11ea-9973-1ec89dc2318d.png)

codeserver did not install, yet it says its running, this cannot be

also did not show alert or logs

**Comment by m-motawea** [comment]
Fixed in commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/66d4bd86404bece696228ce8a3904cca52de1f2c

Check for errors on package.start and update its status accordingly.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
