### ISSUE TITLE
keep track for ports in package farmmanagement to run on localhost:7000

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_threebot#492]
Package frontend should keep track of the port

going to http://localhost:7000/threebot/farmmanagement/ will redirect to https://localhost/threebot/farmmanagement/ 

or go to it from admin dashboard

![image](https://user-images.githubusercontent.com/10658229/77848269-e1424700-71c3-11ea-9c73-c4c724ad251b.png)

**Comment by waleedhammam** [comment]
works ok with https after https://github.com/threefoldtech/jumpscaleX_core/commit/32d3d1b03e710481743a379bf8753f88ac5ec947 

![Screenshot from 2020-03-29 17-19-41](https://user-images.githubusercontent.com/10658229/77852929-86b7e380-71e1-11ea-904f-45bd44f0d609.png)

**Comment by xmonader** [comment]
works for me as well. closing
