### ISSUE TITLE
chatflow for network deployment [unstable_chatflows]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#494]
chatflow for network deployment (the user should be able to reuse their network across their solutions

**Comment by john-kheir** [comment]
I tried to deploy ubuntu container from admin portal, I created a new network and reservation went fine but then i tried to use the existing network that I just created but couldn't find it (note: i found old networks i created days ago but not the one i just created)

**Comment by BolaNasr** [comment]
Thanks @john-kheir  
but i tried now with network name ```john_ticket``` then try another one with existing network 
i got it 
![image](https://user-images.githubusercontent.com/10259267/77907178-78bd9d80-7289-11ea-8b81-6e0f775f0823.png)
