### ISSUE TITLE
improve login error message instead of looping with 3bot connect login button

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#497]
![image](https://user-images.githubusercontent.com/64129/77853052-30977000-71e2-11ea-8fa6-a868d157bf8f.png)

It should show some reasonable error for the user instead of looping into the same page over and over

**Comment by ahelsayd** [comment]
commit https://github.com/threefoldtech/jumpscaleX_threebot/commit/662b219361d5fe6970faa59a5ac6a35431a92900

**Comment by AhmedHanafy725** [comment]
**Verified**

![image](https://user-images.githubusercontent.com/41957921/78038703-6d43a280-736d-11ea-9abb-ba425f9390b7.png)
