### ISSUE TITLE
revisit packagemanager in dashboard

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_threebot#498]
- Install/stop doesn't work all time
- package status could be misleading
- show installation status/errors

- if needed revisit the packagemanager actor

![Screenshot from 2020-03-29 17-39-36](https://user-images.githubusercontent.com/10658229/77853421-486ff380-71e4-11ea-9f2a-6f0487e605d2.png)

**Comment by abom** [comment]
Fixed package manager actors and UI at https://github.com/threefoldtech/jumpscaleX_threebot/commit/b9b0e5fb74e69eaa7709d516509f5db2a4f98385.

Also, added a small fix for `stop()` of `ThreeBotPackage` at https://github.com/threefoldtech/jumpscaleX_core/commit/0b22a80ca59c31a4df1785060529c01ab9aa01fe.

**Comment by john-kheir** [comment]
Verified
