### ISSUE TITLE
Includes on info_threefold that failed to work

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/jumpscaleX_threebot#500]
- [x] https://wiki2.threefold.io/#/token/faq/pricing_conflicts
- [x] https://wiki2.threefold.io/#/token/faq/token_vesting

these where archived but also not working before they where
- [ ] https://github.com/threefoldfoundation/info_threefold/blob/development/docs/tech/_archive/whitepapers/decentralized-system-does-not-exist-yet.md
- [ ] https://github.com/threefoldfoundation/info_threefold/blob/development/docs/tech/_archive/whitepapers/autonomous_layer.md
- [ ] https://github.com/threefoldfoundation/info_threefold/blob/development/docs/tech/_archive/whitepapers/blockchain_dilemma.md

**Comment by VonSub** [comment]
https://wiki2.threefold.io/#/legal/definitions another one

**Comment by abom** [comment]
The first link works fine now:

![Screenshot from 2020-03-30 18-02-01](https://user-images.githubusercontent.com/511438/77934657-ab2ec100-72b0-11ea-83a4-a56090f92086.png)

**Comment by abom** [comment]
Not sure if the changes I did to core, threebot and weblibs is the reason, but we can make sure by pulling all these repositories.

**Comment by abom** [comment]
For this one `https://wiki2.threefold.io/#/legal/definitions`:

```
!!!include("/definitions/_sidebar.md")
```

No such file can be located at `/definitions/_sidebar.md`, as I understood, it should be `/legal/_sidebar.md`.

Was the error shown not clear enough?
![Screenshot from 2020-03-30 18-19-51](https://user-images.githubusercontent.com/511438/77936346-0feb1b00-72b3-11ea-9d85-7abdc75a5828.png)

**Comment by abom** [comment]
Cannot check these archived documents too, please if something is currently used, just list it here.

But a general tips for includes if you face any error like `cannot find doc` or `404` like the [previous screenshot](https://github.com/threefoldtech/jumpscaleX_threebot/issues/500#issuecomment-606099342):
* If you used links, make sure the links is working (not giving 404).
* if you used paths, make sure the path can be found, and assume `/docs` is the root directory, so if we have the following directory structure, we can easily include `file1.md` using ```include("legal/file1.md")```, not using directories outside `docs`.
   * docs
      * legal
        * file1.md

**Comment by abom** [comment]
After i found out it's still not working on our staging machine, i was able to reproduce locally too.

Trying to resolve the issue.

**Comment by abom** [comment]
I added a possible fix at https://github.com/threefoldtech/jumpscaleX_core/commit/591062dad097c822dd9dfffe43feacf45ad768b7 and https://github.com/threefoldtech/jumpscaleX_threebot/commit/16be8892b7f1917a5613fa8031b676d65262d743.

If anyone going to test on staging, he needs ti pull both core and threebot (unstable branch)
