### ISSUE TITLE
chatflows to show qrcode to the user [unstable]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#501]
add a feature to the chatbot to show a qrcode to be scanned by apps (3bot connect app mainly)

- use [j.tools.qrcode](https://github.com/threefoldtech/jumpscaleX_libs/blob/a12880e1a4fd78422084712d24715424b3baed9c/JumpscaleLibs/tools/qrcode/QrCode.py#L1) 
- add in chatbot a helper qrcode_show(data....)
- in the chatflow UI show a qrcode as an image

check for more on the internals [chatbot docs](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/zerobot/webinterface/wiki/chatbot/internals.md)

**Comment by m-motawea** [comment]
Added in commit: https://github.com/threefoldtech/jumpscaleX_core/commit/63596f7517699bf6aef0a7faf84e3cdf348d9877

![image](https://user-images.githubusercontent.com/32568986/77911955-000f0f00-7292-11ea-990d-dc316e61a1d4.png)
