### ISSUE TITLE
exclude essential packages from stop/delete in packagemanager ui

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#502]
https://github.com/threefoldtech/jumpscaleX_core/blob/018395f859212d7a4392faed28052abe7d23b083/JumpscaleCore/servers/threebot/ThreebotServer.py#L394-L395

to keep 3bot functionality we should never disable e.g webinterface

**Comment by abom** [comment]
We can protected this on actor level, and also make them read-only inside the UI.

**Comment by dmahmouali** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/ae17172fbd0437bd047f466e8effb09dbfeb10c4

added condition for essential packages in actor and handled in frontend :
- zerobot.base
- zerobot.webinterface
- zerobot.admin
- zerobot.alerta

**Comment by xmonader** [comment]
there's no `zerobot.alerta` or `zerobot.packagemanager` packages anymore. should exculde admin, base, webinterface only.

**Comment by dmahmouali** [comment]
commit : https://github.com/threefoldtech/jumpscaleX_threebot/commit/3a8c67a299e25e4de0958f5d32c84b6a5540fc81
removerd.

**Comment by PeterNashaat** [comment]
issue verified, packages webinterface, admin and base are locked.
<img width="1288" alt="Screen Shot 2020-04-27 at 10 45 23 PM" src="https://user-images.githubusercontent.com/13523434/80419275-21870900-88d9-11ea-9cdf-eab4c453d2b1.png">
