### ISSUE TITLE
chatflow shouldn't require authentication when you don't have 3botconnect enabled

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#503]
- j.tools.threebot.with_threebotconnect indicates if the threebotconnect is enabled or not, should be respected and not to be overriden with login middleware

**Comment by abom** [comment]
Fixed by https://github.com/threefoldtech/jumpscaleX_threebot/commit/74082d98ce24c656355216bb7ff790ad82d24a94 and https://github.com/threefoldtech/jumpscaleX_libs/commit/5a837a0334f41853a560d7f8d68bf89eccb7fbf8.

**Comment by abom** [comment]
Threebot connect can be disabled, see docs at https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/docs/locations.md#threebot-connect.

**Comment by john-kheir** [comment]
Verified
