### ISSUE TITLE
Your flist chatflow gets stuck

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/jumpscaleX_threebot#506]
When opening your_flist chatflow, the spinner appears and the chatflow is stuck and doesn't proceed to take the user info

**Comment by ranatrk** [comment]
The loop to make sure the ssh key was added was within a form and so is checked before the form.ask() is reached and so will remain in this infinite loop and no question will ever be triggered to the user as the questions in a form will be triggered once form.ask() is done.
**Fix** : remove the form and use single questions that are seperated so that the input for ssh key is not through any form
https://github.com/threefoldtech/jumpscaleX_threebot/commit/3b1f6d4f77483aec845d54e23a24761c8e558d08

**Comment by ranatrk** [comment]
For verification purposes:
- init threebot identity locally using ` j.tools.threebot.init_my_threebot(name=3BOT_NAME,eail=EMAIL)`
- start threebot server
- access admin panel {IP}/admin
- Go to solutions --> generic flist
- If not installed, install/load package through the admin panel, or with package manager client
- Chatflow starts without being stuck

**Comment by AhmedHanafy725** [comment]
**Verrfied** 
chatflow is started and I could enter the flist.

![image](https://user-images.githubusercontent.com/41957921/78012768-c39ceb00-7345-11ea-903a-0e4db078039f.png)
