### ISSUE TITLE
Allow showing optional message with the qr code helper in chatflows

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#507]
qrcode_show and qrcode_show_data don't allow that, the goal is we can provide (copy/paste) usage for farmer addresses for payments

to allow:
- title ( default ) scan with your application
- qr code image
- text (default empty), but can show specific text along with the image

**Comment by m-motawea** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_core/commit/adfa5ffad790d4e07903a6f3456d0528d173eaaa
