### ISSUE TITLE
Recursion login to threebot dashboard

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_threebot#508]
### Steps
1- Start threebot server.
2- Go to server ip ending with `/admin`.
3- Login with 3bot connect.

### Expected result
After logging in should redirect to the dashboard.

### Actual result
Asking for login again.

**Comment by xmonader** [comment]
this is caused because you need to have matching identity on explorer with the 3bot connect app (definitely error needs to show)

**Comment by xmonader** [comment]
related issue: github.com/threefoldtech/jumpscaleX_threebot/issues/497

**Comment by AhmedHanafy725** [comment]
Done on #497
