### ISSUE TITLE
farmmanagement packages always returns all farms iso the logged in user's farms

### ISSUE THREAD

**Issue by ahelsayd** [threefoldtech/jumpscaleX_threebot#512]

**Comment by ahelsayd** [comment]
commit https://github.com/threefoldtech/jumpscaleX_threebot/commit/4957d9607f4c8f3cfe86dbff5a8938ed7b3e34ef

**Comment by Pishoy** [comment]
1 - i installed 3bot and run  j.tools.threebot.init_my_threebot 
2 - then i go to farm management and install package 
3- it gives me a white page , is this correct ?, i think should give me message like "now farm owned by your 3bot user  "
![image](https://user-images.githubusercontent.com/21987477/78143847-13a3ac80-742f-11ea-87bd-7fe3f18c0b73.png)

**Comment by Pishoy** [comment]
verified
