### ISSUE TITLE
faucet package for tft

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#517]
Create a package for faucet - check with @robvanmieghem -

**Comment by ahelsayd** [comment]
it is already implemented here 
https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/stellar-faucet

**Comment by siddiquagig** [comment]
Package Link is under :   https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/stellar_faucet


![image](https://user-images.githubusercontent.com/25789724/80417834-79c50780-88e7-11ea-82bb-a0dedcd9900f.png)
