### ISSUE TITLE
Ensure the flist that user chooses actually exists

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#521]
In chatflows "Generic flist" make sure to validate against the existence of the flist the user chooses

**Comment by BolaNasr** [comment]
Fixed at https://github.com/threefoldtech/jumpscaleX_threebot/commit/d32493c5b5470f58741e850da57f878a17b27248

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/78473099-3e974480-773e-11ea-9077-a704b83cea5c.png)
