### ISSUE TITLE
Don't use data/parity words in S3 chatflow and a sane default

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#522]
don't use words data/parity, use (nr of locations, locations allowed to fail) and default 6+3 if not sure

**Comment by ranatrk** [comment]
Fix : https://github.com/threefoldtech/jumpscaleX_threebot/commit/d365c9aec176440907391611f235cb56f27e2d72

**Comment by ranatrk** [comment]
Changed the default values for data and parity to 2 and 1 respectively. As the nodes currently being retrieved are not alot and so to get unique nodes for all the reservation components then 9+ nodes are needed. So for default values, where the user is not sure wht values to enter, I kept it as 2 and 1
