### ISSUE TITLE
SSH Authorization for ubuntu/your_flist

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#524]
For ubuntu, it makes more sense to have a complete solution in means ssh or (user/passwd) access to the machines instead of just a corex process running and they launch bash and from there they prepare the machine...

Idea is we do that using coreX client in the background

For the user, it also makes more sense to choose their key if the deployment running from the user's machine, if it's not the same machine on a central deployer, the deployer should connect to the network with wg config and do the required configurations for ssh and send the same config to the user back again

For a generic flist (which is more advanced one) we either ask the user to use only ssh enabled flists or we leave it at giving them coreX process only

**Comment by grimpy** [comment]
@xmonader for the generic flist we either don't do anything or we could ask in the chatflow if this flist has ssh and if we should enable it?

Come to think of it... don't flist support startup commands where we could make our ubuntu one start sshd by default? Also in the past it (v1) it was possible to push some config files during the create of the container from those we could configure the ssh authorized_keys files and we don't have to go inside the container via coreX at all.

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_libs/blob/unstable/JumpscaleLibs/sal/zosv2/container.py#L18

After seeing this method it does not look like we still have this config file support. we could however send the ssh_keys inside env variables and add a custom script in our flist that handles this as part of the startup (entrypoint)

**Comment by BolaNasr** [comment]
Fixed on unstable branch 
update flist with script to add ssh 
https://hub.grid.tf/tf-bootable/ubuntu:18.04-r1.flist

**Comment by xmonader** [comment]
Works beautifully! thanks @BolaNasr
