### ISSUE TITLE
add an option to make a package accessible  only for logged in users

### ISSUE THREAD

**Issue by ahelsayd** [threefoldtech/jumpscaleX_threebot#526]
currently we use is_auth to make package accessible for only admins
but we don't have an option to make it accessible for any logged in user

**Comment by xmonader** [comment]
let's link the docs for this and the commit please

**Comment by ahelsayd** [comment]
commit https://github.com/threefoldtech/jumpscaleX_threebot/commit/a101922260e6b7f2f6789d564c25321ec7938478

docs https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/docs/locations.md#threebot-connect

**Comment by Dina-Abd-Elrahman** [comment]
- verified .
