### ISSUE TITLE
keep track of deployed solutions and their reservation ids in bcdb [unstable_solutions]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#529]
keep track of solutions deployed and add helpers to  delete should cancel reservations

- [x] ubuntu
- [x] generic flist
- [x] minio
- [x] kubernetes
- [x] reservation manager (info below)

# reservation manager
add new view in admin dashboard (similar to package manager) to show a table of reservations and deployed solutions and an option to delete "cancel" reservation

**Comment by ranatrk** [comment]
Functionalities added in reservation chatflow sal: https://github.com/threefoldtech/jumpscaleX_libs/commit/00e6e3e70b9855a79afb4ec40109a102aad9bb1e
- `solutions_get(url)` : get list of solutions for the required chatflow's url found in package's models
- `reservation_cancel_for_solution(url,solution_name)` : cancel a reservation that corresponds to the name given when creating that reservation through the chatflow

**Comment by ranatrk** [comment]
was working on updating the chatflows. 
Will continue with this issue by looking into webix and adding to the dashboard the listing the solutions from `solutions_get()` along with a cancel option button for each solution

**Comment by xmonader** [comment]
verified.
