### ISSUE TITLE
threebot eating diskspace like there is no tomorrow

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/jumpscaleX_threebot#533]
![image](https://user-images.githubusercontent.com/64129/78673541-92db2980-78e2-11ea-845d-2e0d6fe1a26f.png)

11K `*.msgpack` files in
```
3BOTDEVEL:mainnet-explorer:~: ls -l  /sandbox/var/logs/threebotserver/ | wc -l
11025
```
in total 3G of logs (unreadable .msgpack) in 
- init
- tcprouter
- workers_[12]
- bottle_server
- threebotserver -> 11k of these
and before pruning, 3G of unrotated logs in /sandbox/var/logs/openresty/default_openresty_threebot/ 

then, and most importantly
18 Gig in `/sandbox/var/zdb/threebot/` , so whatever you store in zerodb, it has no place there. It is a write-only db, and 18Gig of logging will __never__ be read again if it's logging you put in there.

either way, that DB needs pruning, because I can't imagine we need 18G of data after a week with 130 nodes

That is after a week of existence

so if you store msgpack files for whatever reason (I suppose temp storage), also delete it, some can linger, but that will already alleviate some pressure.

**Comment by waleedhammam** [comment]
PR at: https://github.com/threefoldtech/jumpscaleX_core/pull/706/files
- Limit msgpack logs files to 50 (this number can be configured using myenv)
- If logs files > 50 then delete oldest 10

**Comment by waleedhammam** [comment]
for nginx logs it doesn't support log rotation so it has to be manually https://www.digitalocean.com/community/tutorials/how-to-configure-logging-and-log-rotation-in-nginx-on-an-ubuntu-vps#log-rotation

, so it could be a cronjob something like that https://serverfault.com/a/930514 to rotate these files 

![Screenshot from 2020-04-07 12-54-21](https://user-images.githubusercontent.com/10658229/78661351-efcce480-78ce-11ea-99c8-80325796afa8.png)

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/78673663-bf8f4100-78e2-11ea-817c-c1f9ad921d7b.png)

as the most of the disk space consumption is coming from  tfgrid_directory and we don't manage that nor part of threebot now, I'll move into verification.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
