### ISSUE TITLE
webgateway wizard 

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#536]
- connect containers to external points
- have at least 3 external https points we can use
- specify port in container & name on external points
- admin entry

**Comment by Pishoy** [comment]
steps as below 
1 - configure my threebot  `  j.me.configure() `
2 - go to 3bot admin portal
3 - install mino package and create a mino 
4 - go webgateway tab ( install package ) and then create a webgateway new point 
5 - select the minio that i have create it in step 3 
6 - enter a subdomain (s3) for it and wait until it finishes
7 - you should be able to access the minio using the returned url http://s3.bishoy.3bot.testnet.grid.tf

- jsx version 
```
3BOTDEVEL:bishoytest:jumpscaleX_threebot: git log -1
commit a97c33f44c13b9ade557ca808476eac501b29db8 (HEAD -> unstable, origin/unstable)
Author: Abdelrahman Ghanem <abom.jdev@gmail.com>
Date:   Mon Apr 13 10:49:00 2020 +0200

    Update README.md

```
