### ISSUE TITLE
new location type for SPA

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#54]
- static locations work fine with hash based routes
- e.g for our sapper export 
```
        location / {
              root   /home/xmonader/wspace/temp_test_sapper/myapp/__sapper__/export/;
              index  index.html;
              try_files $uri $uri/ /index.html;
            }
    }
```

either we make one that works for all of them, sapper, vue, ...etc or we have some generic tools in jsx that we can use to format raw location.

**Comment by xmonader** [comment]
dfb52f116366255f906c6ae13f0fd33125b8c901

**Comment by john-kheir** [comment]
### Verification Steps
1- cl = j.servers.threebot.local_start_default(web=True)
2-cl.actors.package_manager.package_add(path='/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/alerta')
3- cl.actors.package_manager.package_start("alerta")
4- Then check webpage on 172.17.0.2/alerta and make sure you can go through pages with no broken links
