### ISSUE TITLE
size should be added to ubuntu container in wizard

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#540]
- mem/cpu

**Comment by alichaddad** [comment]
Addressed here https://github.com/threefoldtech/jumpscaleX_threebot/commit/fe907226988c99631e9aa9f7aa106dfc9617e6b4

**Comment by Pishoy** [comment]
it addressed but i recommend to write the unit we are using "MB" 
![image](https://user-images.githubusercontent.com/21987477/78491302-dbf77600-7748-11ea-84e9-0d6428949b56.png)

**Comment by alichaddad** [comment]
See [here](https://github.com/threefoldtech/jumpscaleX_threebot/commit/025d6f61c4dfa46e3ebe25c79742846fad9124c3).

**Comment by Pishoy** [comment]
Thanks, verified
