### ISSUE TITLE
ipv6 flow in chatflows is buggy

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#541]
ipv6 flow in chatflows is buggy and always breaks

- investigate the reason 
- use DO machine with ip6

![image](https://user-images.githubusercontent.com/64129/78504862-e842f980-776f-11ea-9267-dc664483d756.png)

error is always can't pick random choice of empty sequence in line 49 
```
node = random.choice(nodes)
```

**Comment by ranatrk** [comment]
Nodes with public access were removed from the chosen nodes before picking nodes from them . Changed this to only occur when ip version is Ipv4 where the access nodes are left to be used for access only
https://github.com/threefoldtech/jumpscaleX_libs/commit/1fc325db597b90b661550785e022f9d060872be0

**Comment by xmonader** [comment]
Verified.
