### ISSUE TITLE
port wikis from docsify to mdbook [unstable_mdbook]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#544]
- sidebar change to summary
- book.toml
- mdbook to build html output 
- html output for books to be saved in in /sandbox/var/mdbooks/$packageauthor$packagename/
- add config in openresty to serve /sandbox/var/mdbooks

**Comment by abom** [comment]
Done, now wikis load using mdbook, `book.toml` gets generated.

For any package wiki, it requires at least `SUMMARY.md`.

**Comment by Dina-Abd-Elrahman** [comment]
-  verified.
