### ISSUE TITLE
threebotserver.bcdb fails

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#55]
in package.py if u do `self.bcdb` it fails, you need to override the property and return `j.data.bcdb...`

**Comment by abom** [comment]
Should be fixed

https://github.com/threefoldtech/jumpscaleX_core/pull/124
https://github.com/threefoldtech/jumpscaleX_core/commit/4e36d280357926a55aec79fc84fbfadda5609a01

**Comment by siddiquagig** [comment]
Verified:

Did the tfgrid_token package which has bcdb property and works fine

![bcdb](https://user-images.githubusercontent.com/25789724/66479674-06c08480-eaae-11e9-94e1-7b6fdbf14f44.jpg)
