### ISSUE TITLE
threefold wiki_packages

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#553]
- we have 2 new wiki's for ThreeFold: mdbook (sdk/info)
- all old wiki's can be removed from packages
- should be deployed on 3bot in 1 package, so user can install 1 package:
    - $ipaddr/wiki/threefold
    - $ipaddr/wiki/threefold_sdk
- have hook for github: so allow github to be configured to trigger change

**Comment by AhmedSa-mir** [comment]
Commits: 28b4042dcc484cc665fec8f1c5db9c3fc365fc02, 9e5bb89225da62304a181a98ab2f3eddef246144, 33b9b3d1edbb0111a7700d99317a6325dc1b8906
**Implemented 3 methods:**
- generate_pkg_summary()
- generate_summaries() (for all packages)
- generate_index_book() to generate 1 index book for all packages books

**Comment by AhmedSa-mir** [comment]
Notes:
1- mdbook renames README files to 'index' after building the book, so any link to README.md file in the book won't work.
* linking to index.md workds but index.md file is not found in the actual wiki dir before build which is confusing.
2- Any index.html file in the wiki dir will result in wrong behavior becuase the README.md is renamed to index.html after mdbook-build

**Comment by abom** [comment]
Package is done, see https://github.com/threefoldtech/jumpscaleX_threebot/blob/73c8329955ad76bbd4d138a746323328ef11308d/ThreeBotPackages/threefold/wikis/wiki/README.md.

Using webhooks to update content on push events, thanks @m-motawea, @AhmedSa-mir  and @dmahmouali.

**Comment by xmonader** [comment]
verified it myself
