### ISSUE TITLE
review chatflows and retest after merging payments in zos sal

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#554]
reservation_register now returns [reservation create object](https://github.com/threefoldtech/jumpscaleX_threebot/commit/6aef87be35ba47c5b9197b96c9de7f77820473cb#diff-035a5d6b8b11c81146757078d4aa8d21R50
)

- reservation_register change 
https://github.com/threefoldtech/jumpscaleX_libs/commit/c8ff23be9e6dd130be299134ee0ad3875131971d#diff-9c7be5c3654634d567f872d940d3c193R81

- qrcode part should work against just one object not list of escrow detail
https://github.com/threefoldtech/jumpscaleX_libs/blob/c8ff23be9e6dd130be299134ee0ad3875131971d/JumpscaleLibs/sal/zosv2/ZOSv2.py#L284

**Comment by ahelsayd** [comment]
simulator playground package is updated but this commit https://github.com/threefoldtech/jumpscaleX_threebot/commit/8628c0c4ae7a4293fcfdacb9b735381bdce74735

but i can't test it now because the testnet is down

**Comment by ranatrk** [comment]
Updated reservation_chatflow and zosv2 sal to recieve id and escrow info : https://github.com/threefoldtech/jumpscaleX_libs/commit/f8e7c322279112edce24882ffeeec44e9742ec7e
**Blocked** on testing as testnet is down

**Comment by xmonader** [comment]
been tested already. closing.
