### ISSUE TITLE
update all solutions to use secret env properly

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#559]
I don't think it's okay to use env for sharing access keys and passwords

**Comment by ranatrk** [comment]
Minio: https://github.com/threefoldtech/jumpscaleX_threebot/commit/5ed8872fda1c838e306a769a95cbde48729734f0

**Comment by ranatrk** [comment]
It is already implemented for Kubernetes cluster secret and threebot

**Comment by john-kheir** [comment]
Verified
