### ISSUE TITLE
threebot.local_start_default doesn't work

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#56]
calling local_start_default doesn't work to start the threebot, we work around it using package factory which isn't how it meant to be

**Comment by abom** [comment]
Related to #57.

**Comment by siddiquagig** [comment]
It is working now: (also verified in Related ticket #57 )

![threebotlocal](https://user-images.githubusercontent.com/25789724/66308222-9b44ae80-e917-11e9-9230-e8e26cf1af71.JPG)
