### ISSUE TITLE
webgateway solution improvements

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#560]
- [x]  move into tfgrid_solutions package along with minio, .. etc
- [x] add documentation in the same style of the other solutions

**Comment by xmonader** [comment]
I did the moving part 02fc803a907338ad3802b49ebc31a6b9976ef0c8
remaining part is docs

**Comment by ahelsayd** [comment]
docs commit https://github.com/threefoldtech/jumpscaleX_threebot/commit/fb164490d70e3e1165f657b63aa6338b400ed9a1
