### ISSUE TITLE
admin improvements [development_adminpanel]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#563]
# grids

- [x]  in jobs grid
    - [x] when click on row, show details of jobs, with also logs linked to it
    - [x] if error should be able to go from job which is failed to the error
- workers grid
    - [x] click on row of workers, see details from obj
- [x] there is no delete on logs: do a delete all on filtered part and on multi select logs
- [x] [wiki's in a grid like the others, now weird its different style](https://github.com/threefoldtech/jumpscaleX_threebot/issues/578)

# dashboard
- [x] fix bad formatting of message in alerts
- [x] a detail page of a package, job, ... it does not open to a detail widget
- [x] show multiple IP addr
- [x] allow to kill processes in show all (filtered or one by one or multiselect)
- [x] kill processes occupying ports (filtered, one by one, or multiselect)
- [x] if click on a process, show the details, make an actor which gives you the details (can be retrieved using psutil)
- [x] admin ports grid takes so much space
![image](https://user-images.githubusercontent.com/64129/79855617-80c1b680-83cb-11ea-80c5-ca5c055efe97.png)

**Comment by AhmedSa-mir** [comment]
Commits: https://github.com/threefoldtech/jumpscaleX_threebot/commit/09febfdea444a968429ce07cb90e0d68eefb2c5d   , https://github.com/threefoldtech/jumpscaleX_threebot/commit/fb10d2f857ffcea4ad4fa29d54a8a9608920a079

on unstable_dashboard branch

Implemented kill processes in show all and ports table

**Comment by dmahmouali** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/dc58f38cf0e2f4b48a564be706ce51702bcb37c0

Added process details window on process double click.

On unstable_dashboard branch

**Comment by waleedhammam** [comment]
Fixed message coloring

![Screenshot from 2020-04-21 16-00-15](https://user-images.githubusercontent.com/10658229/79875051-6696d100-83e9-11ea-8cfc-37247a35b20c.png)
![Screenshot from 2020-04-21 16-00-21](https://user-images.githubusercontent.com/10658229/79875040-64347700-83e9-11ea-9432-a20e1947f147.png)

**Comment by dmahmouali** [comment]
changed dashboard grid in commit : https://github.com/threefoldtech/jumpscaleX_threebot/commit/a03578cdcf4ed3981058914ae5ef2d934c6dd4c5
![Screenshot from 2020-04-21 19-16-21](https://user-images.githubusercontent.com/36021484/79893757-ce0e4a00-8404-11ea-8648-64493fec21f2.png)

**Comment by AhmedSa-mir** [comment]
Commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/4b5b626678d17e74726dacd8ca618b397b5faef2

- Multiple IP addresses are shown now in jsxinfo

**Comment by dmahmouali** [comment]
Commit:https://github.com/threefoldtech/jumpscaleX_threebot/commit/090786b2e5b6e5296d683a685e95a07e32c9930d

- Added delete all logs on filtered part

**Comment by dmahmouali** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/0be15c7fe68dae1b0a6628a80d21abfb8ef54088

added delete multi-select logs

**Comment by dmahmouali** [comment]
commit : https://github.com/threefoldtech/jumpscaleX_threebot/commit/6db62976b6b20d5702e27ace400d130a2bcc9fa2

Added show details for workers and jobs

**Comment by AhmedSa-mir** [comment]
Commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/2d3f6af94dd571631cf4801c34273279ac0502a4

Added package details window

**Comment by dmahmouali** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/d4eb497a588b42b5d95fd36e820fb65d718fc63d

added job error and logs details
