### ISSUE TITLE
fix wiki test in dashboard to align with the new wikis

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_threebot#565]
![Screenshot from 2020-04-11 17-25-38](https://user-images.githubusercontent.com/10658229/79047835-7f4cfd00-7c19-11ea-980c-340bd927a46e.png)

implemented in health actor

**Comment by waleedhammam** [comment]
fixed at: https://github.com/threefoldtech/jumpscaleX_threebot/commit/f072de2c8d33549339f3f038015f1629e5f5ae8e 
![Screenshot from 2020-04-12 09-53-42](https://user-images.githubusercontent.com/10658229/79063713-91737d80-7ca3-11ea-9782-c83042a4f38b.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
