### ISSUE TITLE
Integrate capacity page in the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#569]
Integrate https://explorer.testnet.grid.tf or https://explorer.grid.tf in the dashboard using IFrame based on the current explorer used

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/79140842-e7861500-7db8-11ea-8df5-e591679ab7cf.png)

**Comment by john-kheir** [comment]
Verified
