### ISSUE TITLE
package_manager doesn't work

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#57]
there's a bug in package_manager actor it doesn't really load the packages so we used j.tools.threebot_package to load it into threebot

**Comment by abom** [comment]
Should be fixed in https://github.com/threefoldtech/jumpscaleX_core/pull/124.

**Comment by siddiquagig** [comment]
Verified  :

```
kosmos -p 'j.servers.threebot.local_start_default(web=True)'
```

Then use the returned client to access package manager actor and add your package : 

![alerta](https://user-images.githubusercontent.com/25789724/66307639-04c3bd80-e916-11e9-8801-61c40b36ca13.JPG)
