### ISSUE TITLE
make sure to save the data entered by the user in solutions in bcdb.

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#571]
Need to be able to save the information the user entered in solutions for future reference when he checks the reservations manager grid

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/79136736-cc63d700-7db1-11ea-93d4-47b3031c7f81.png)

**Comment by ranatrk** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/commit/7a1f06f7c8a792c96a38c2b866cc91c5aed79de0
https://github.com/threefoldtech/jumpscaleX_libs/commit/c9314e6670d89cfc4b1fc717693a8101b3b872b9

**Comment by john-kheir** [comment]
Verified
