### ISSUE TITLE
wiki packages improvements in the admin dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#578]
Now that we have 
- Wikis
- TF Wikis 
in the admin panel and it will be all very confusing

Suggest: 
- Rename wikis -> Packages Docs
- Convert the weird UI of pull, reload, view into a grid with suitable actions
- Leave TF Wikis as is

**Comment by dmahmouali** [comment]
commit : https://github.com/threefoldtech/jumpscaleX_threebot/commit/f3800b3cb2b7e588dda8818a71ec53c0aa622cc8  ,  https://github.com/threefoldtech/jumpscaleX_threebot/commit/b796bd0f512ab0393937506741ba8248b640a103

- Rename wikis -> Packages Docs
- Convert the weird UI of pull, reload, view into a grid with suitable actions (view only now)
- Leave TF Wikis as is

**Comment by xmonader** [comment]
verified it myself
