### ISSUE TITLE
adding new 3bot account to admins not working 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/jumpscaleX_threebot#579]
on new installation using 3sdk package :
was trying to add admin to 3bot admins following docs [here](https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/ThreeBotPackages/zerobot/admin/wiki/README.md#login) using 
```
j.tools.threebot.me.default.admins.append("samir1.3bot")
```
and this error appeared: 
![Screenshot from 2020-04-14 10-20-15](https://user-images.githubusercontent.com/26298009/79207187-ac2f2900-7e40-11ea-93ce-d7a17e7deb5c.png)

**Comment by abom** [comment]
It's not used anymore, just need to update docs to use `j.me` instead.

**Comment by abom** [comment]
Done on unstable for both threebot and core.

**Comment by Pishoy** [comment]
verified
