### ISSUE TITLE
farm management: use the configured explorer url instead of hard coded one.

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#581]
farm management app when it boot should do a call to `/zerobot/admin/actors/admin/get_explorer` to get the configured explorer URL on the 3bot and use this one instead of the one hardcoded at: https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threebot/capacity/html/config/capacity.config.local.js

**Comment by DylanVerstraete** [comment]
Suggested fix:
Before you run the frontend, add a process enviroment variable and read from it in the config file like:
`process.env.VARIABLE`

maybe you can set this process env variable in the start script of this package?

**Comment by zaibon** [comment]
This is not a valid solution cause the explore URL can be change at runtime. This is not a one time thing to read at start. 
It needs to be read anytime the application is loaded.

**Comment by DylanVerstraete** [comment]
Hmm, what about creating an actor that fetches this variable from the threebot and then call this actor in the frontend to read this variable?

**Comment by zaibon** [comment]
> Hmm, what about creating an actor that fetches this variable from the threebot and then call this actor in the frontend to read this variable?

This is what I describe in the first comment yes.

**Comment by Pishoy** [comment]
Verified as below steps 

1 - Go to the admin portal
2 - Install farm management package
3 - Go to settings and check which explorer is selected the main one or the test net one
4 - Then open the farm management make sure the explorer URL in request include name of correct explorer 

jsx version 
```
3BOTDEVEL:3bot:jumpscaleX_threebot: git log -1
commit 8e612212d45d7bb13153e44d8ec0784c9000a35e (HEAD -> unstable, origin/unstable)
Author: m-motawea <magedmotawea@gmail.com>
Date:   Wed Apr 15 12:19:52 2020 +0200

    simulator start to inc base_url in background & remove voila in package

```
