### ISSUE TITLE
simulator package improvements 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#588]
simulator package shouldn't do simulator_get and don't start 2 servers one with voila and one without. `just j.tools.tfgrid_simulator.start()`

**Comment by m-motawea** [comment]
- removed voila from simulator package commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/8e612212d45d7bb13153e44d8ec0784c9000a35e

- add base_url to simulator background startupcmd commit:
https://github.com/threefoldtech/jumpscaleX_libs_extra/commit/2e3917d97b67d23068e6c355a3e8f1d82087475d

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
