### ISSUE TITLE
Adding a package from admin dashborad with space in package path cause file not exist error  

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/jumpscaleX_threebot#595]
there was space at the start of package path so i got this error:

![Screenshot from 2020-04-21 10-34-57](https://user-images.githubusercontent.com/26298009/79847883-a4cbca80-83c0-11ea-9c49-c8f57123dcf7.png)

**Comment by xmonader** [comment]
should be sanitized in admin/packagemanager actor

**Comment by m-motawea** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/64d9d6a25c7a0a7a571d88177a3fb2c0ea48f252

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
