### ISSUE TITLE
Deployed solutions, should only show solutions of the current selected network

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_threebot#600]
When you in settings swtich between devnet/mainnet/testnet we should only show the solutions linked to the current active network

**Comment by ranatrk** [comment]
Fixes:
- https://github.com/threefoldtech/jumpscaleX_threebot/commit/2e20a6e1427d0d6d58a61d6d33d862b78762be51
- https://github.com/threefoldtech/jumpscaleX_libs/commit/14402ffeebaaa23b980af8ce2b2ac6f505fd8b41

To test the scenario:
1. Using testnet : `j.clients.explorer.default_addr_set("explorer.testnet.grid.tf") `
2. Deploy a solution (eg: network) 
3. View the solution in the dashboard deployed solutions
3. Change to devnet: `j.clients.explorer.default_addr_set("explorer.devnet.grid.tf") `
4. Deploy another  solution (eg: network)
5. View the solution in the dashboard deployed solutions, only the latest one will show. (If the explorer was switched again, the old solution deployed will only show)
6. If the model for the network was used to list the instances, both instances will be available in the database but only the relevant one is used in the dashboard
![Screenshot from 2020-04-26 13-47-30](https://user-images.githubusercontent.com/17128393/80306585-80a72980-87c4-11ea-8a25-6deec4015582.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
