### ISSUE TITLE
Deployed solution: fetch all reservation from user

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#601]
Currently the deployed solution only show the solution deployed from the local threebot. 
I think we should allow to synchronise all the reservation made by the user so he can have a view on ALL the reservation ever made.

Normally, all the information are present in the reservation object so we should be able to reconstruct all data and cache it locally.

**Comment by BolaNasr** [comment]
add this feature in 
https://github.com/threefoldtech/jumpscaleX_threebot/pull/616
https://github.com/threefoldtech/jumpscaleX_libs/pull/179/

after review we will merge it then add it as verification

**Comment by zaibon** [comment]
I just tried this one. The deployed solution table is empty for me and I can see this error:
![2020-04-27_2950x945_scrot](https://user-images.githubusercontent.com/303164/80407589-24c4c980-88c6-11ea-9098-78fec962c6f4.png)

**Comment by grimpy** [comment]
@zaibon code wasn't merged back then just merged it now

**Comment by Dinaamagdy** [comment]
verified on development with latest fix https://github.com/threefoldtech/jumpscaleX_libs/commit/d58c9e575c02d5ca2be53b919edc37a40ffb3e0a
