### ISSUE TITLE
Chat flow: update gateway code to use new TFGateway

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#602]
We need two new chatflows:

## Delegate domain:
This one will ask the your for the name of the domain he wants to delegate
it will intruct the user to create a `ns` record in his dns and point it to tthe gateway `dns_nameserver` field in the gateway node

## Expose my solution
Ask for the subdomain to expose this can be either a subdomain of one of his own delegated domains or a subdomain of the gateway see field (managed_domains)

Select the solution to expose
depending on the solution kind ask for which port to expose...

Ask for payment if needed...

Internally we make a reservations that: registered the subdomain, create a small container with flist `https://hub.grid.tf/tf-official-apps/tcprouter:latest.flist.md` in the network of the solution, configure the trc (tcprouterclient) with a secret connecting to the tcprouter server on the server pointing to the private ip/port of the solution selected

**Comment by m-motawea** [comment]
Two chatflows added

![image](https://user-images.githubusercontent.com/32568986/80508057-da038a00-8977-11ea-8177-6bd2dfba88ec.png)
![image](https://user-images.githubusercontent.com/32568986/80508105-e851a600-8977-11ea-890a-51fccfaf8a96.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
