### ISSUE TITLE
minio chat flow: failed because mixed of free and not free node

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#603]
I got this error when trying to deploy a minio instance:
```
Fri 24 11:50:36 s/explorer/errors.py -  23 - raise_for_status                   : EXCEPTION: 
    HTTPError('400 Client Error: reservation can only contain either free nodes or paid nodes, not b
oth for url:
        https://explorer.testnet.grid.tf/explorer/reservations')
--TRACEBACK------------------
```

which result in 
![2020-04-24_2408x341_scrot](https://user-images.githubusercontent.com/303164/80209892-1dd25880-8633-11ea-8187-3a87ca8821e7.png)

So 2 things needs to happens:
1. update the chat flow so it pick the proper type of node based on the chosen curency
2. Would be cool to have a proper error message in the UI. the server send a perfectly user friendly error.

**Comment by nbabenko** [comment]
Having same issue with other deployments via chatbot - flist and ubuntu

**Comment by zaibon** [comment]
@nbabenko please create issue for it. Give as much detail as you can so we can identity the problem

**Comment by ranatrk** [comment]
- The nodes are chosen based on the currency type : https://github.com/threefoldtech/jumpscaleX_libs/commit/56edc08c2665cc438330d19c3ca6f6d665022d50#diff-47ef217232882edb91c5726cc77e9c7cR106
- This issue may also occur when the network node uses a currency while there is an attempt to deploy a solution on another node with a different currency. This is handled by 
   - Using the currency from the network the user chooses when deploying, the currency is obtained from the reservation object of the network itself deployed
   - Showing the currency used for the network in the list of networks the users chooses from

https://github.com/threefoldtech/jumpscaleX_libs/commit/c184411b67bf7370f4d42f3458a733dc53235e0f
https://github.com/threefoldtech/jumpscaleX_threebot/commit/5e0e42c60eebed766f92addbb03f24a55fb47e07#diff-5589d29dca43bc0f5e0a0142f264ee9bR19

**Comment by AhmedHanafy725** [comment]
**Verified**

Now while selecting network it detect the payment method and it continue without error.
![image](https://user-images.githubusercontent.com/41957921/80411073-e0d4c300-88cb-11ea-97c5-6b8158a31962.png)

![image](https://user-images.githubusercontent.com/41957921/80415690-2ba60900-88d3-11ea-8545-3ea124e1e5e4.png)


Also tried to hard code the payment method to see it will return user friendly error in chatflow or not.
![image](https://user-images.githubusercontent.com/41957921/80414910-0bc21580-88d2-11ea-80cd-2e96ff7a56af.png)
