### ISSUE TITLE
Minio chat flow: reservation with FreeTFT is never paid

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#604]
I tried to deploy a minio instance. I choose to use FreeTFT to pay the reservation.

The reservation never got deployed. After I checked the explorer logs it seems the payment for this reservation was never done.
```
Apr 24 12:09:49 testnet-explorer tfexplorer[24566]: 2020-04-24T12:09:49Z info scanning active escrow accounts balance
Apr 24 12:09:49 testnet-explorer tfexplorer[24566]: 2020-04-24T12:09:49Z info fetching balance for address address=GCA4PNY5SZBD5WUPTH7ILOFS76FUJMYAUO5N3WSJ4XTC4A3EXSYMZ2BX
Apr 24 12:09:49 testnet-explorer tfexplorer[24566]: 2020-04-24T12:09:49Z info status of balance for reservation address=GCA4PNY5SZBD5WUPTH7ILOFS76FUJMYAUO5N3WSJ4XTC4A3EXSYMZ2BX balance=0 id=459413
Apr 24 12:09:49 testnet-explorer tfexplorer[24566]: 2020-04-24T12:09:49Z debug required balance 117334800 not reached yet (0) address=GCA4PNY5SZBD5WUPTH7ILOFS76FUJMYAUO5N3WSJ4XTC4A3EXSYMZ2BX reservation_id=459413
```

Reservation: http://explorer.testnet.grid.tf/explorer/reservations/459413

**Comment by ranatrk** [comment]
The payment gets transferred from the wallet and listed in the wallet transactions. I also followed the next_action, it was changed from PAY to DEPLOY after the transfer was done. @zaibon shouldnt the state only change once the payment is done? or should we check on something else other than the next_action?
reservation : http://explorer.testnet.grid.tf/explorer/reservations/459447
stellar wallet transaction: 
![Screenshot from 2020-04-26 10-55-29](https://user-images.githubusercontent.com/17128393/80303112-7712c700-87ae-11ea-921c-1169c348fe4e.png)
next_action of reservation:
![Screenshot from 2020-04-26 10-55-47](https://user-images.githubusercontent.com/17128393/80303129-90b40e80-87ae-11ea-90fd-16f7ae6f17ea.png)

**Comment by zaibon** [comment]
>  @zaibon shouldnt the state only change once the payment is done?

Indeed, as soon as the explorer detected the payment the `next_action` value should change from `PAY` to `DEPLOY`.

OK seem you cannot reproduce the error. weird. I"ll retry on my end too. Did you try to pay with FreeTFT right ?

**Comment by ranatrk** [comment]
yes it was with FreeTft on testnet
