### ISSUE TITLE
Extend wallet manager

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_threebot#605]
Make it possible to:
- [x] export your wallet (make it possible to copy your private key)
- [x] import a wallet from a seed

**Comment by AhmedSa-mir** [comment]
Commits: https://github.com/threefoldtech/jumpscaleX_threebot/commit/debee39c3ef6720bf18c249caf9e910acfcce4c8 , https://github.com/threefoldtech/jumpscaleX_threebot/commit/425c1a3d5078494188ff332a9bc5f3f09889bd83

- Added export button in wallet details to show private key
- Added an import button in the layout to get the private key of the wallet to be imported

**Comment by AhmedHanafy725** [comment]
**Verified**
commit: e60c73351e84f4c8590227ad79a884e89334bd0c

Show secret to get the private key 
![image](https://user-images.githubusercontent.com/41957921/80409934-fe089200-88c9-11ea-936e-9074eec7f606.png)

By pressing on import wallet 
![image](https://user-images.githubusercontent.com/41957921/80410126-5c357500-88ca-11ea-84b5-b454690d8cd1.png)

Set wallet name and secret and was able to import my wallet
