### ISSUE TITLE
Minio chat flow, error after the first pane

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#609]
```
JSX> Mon 27 07:10:19 lows/minio_deploy.py -  21 - chat                               : EXCEPTION: 
    AttributeError("'Network' object has no attribute 'currency'")
--TRACEBACK------------------
/sandbox/lib/jumpscale/Jumpscale/servers/gedis/GedisChatBot.py in wrapper
    189    self.topic_method(bot=self)
/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/tfgrid_solu
tions/chatflows/minio_deploy.py in chat
    21    currency = network.currency
-----------------------------
```

My network was crearted quite some time ago, so the currency field does not exists on it yet

**Comment by ranatrk** [comment]
@zaibon the code associated with this change is in jumpscaleX_libs. Can you try and pull the changes there as well then try again?
reference: https://github.com/threefoldtech/jumpscaleX_libs/blob/development/JumpscaleLibs/sal/reservation_chatflow/reservation_chatflow.py#L23

**Comment by grimpy** [comment]
![failedpay](https://user-images.githubusercontent.com/143869/80352615-69c01000-8874-11ea-8971-23927bfc48be.jpg)
@ranatrk old reservations have empty curecny, in such a case please fall back to the original logic of checking the node type of the network

**Comment by ranatrk** [comment]
I adjusted getting the currency so be the value of `currencies[0]`, if empty will get from the node of the network if its `free_to_use` then use FreeTFT, otherwise use the currency 'TFT'
https://github.com/threefoldtech/jumpscaleX_libs/commit/e284167a636b83c3822b51384deae0a23d270175

**Comment by AhmedHanafy725** [comment]
**Verified**
I had this network before applying payment on `testnet` which this network has no currency attr, so it uses FreeTFT for this network.

![image](https://user-images.githubusercontent.com/41957921/80412557-5772c000-88ce-11ea-8e00-669bdfd7ea07.png)
