### ISSUE TITLE
MVP for wikis

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#61]
- [x] gslides (include 1 slide fails)
- [x] includes 
- [x] errors
- [x] documentation
  - [x] move all relevant docs from openpublishing to threebot repo (nothing remains in core)
  - [x] document includes and its usages
  - [x] document links and its usages
  - [x] document slides 
  - [x] document errors

**Comment by abom** [comment]
Checking why errors are not logged or added to `errors.md` properly.

**Comment by abom** [comment]
Now errors should be more meaningful (also, did some small fixed to include macro).

https://github.com/threefoldtech/jumpscaleX_libs/commit/d720b2ec840c02281717aa674a3d65981dc052cc

To test loading the sample wiki, we start `wikis` package using:
`kosmos -p "j.threebot.package.wikis.start()"`

Then, we can put the following into simple script:

```
from Jumpscale import j

def load_wiki(name, url): 
    wiki = j.tools.markdowndocs.load(path=url, name=name) 
    wiki.write()                                          


load_wiki("jsx", "https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/examples/docs")
```

Then, we can run this directly using `kosmos`

`kosmos -p <script name>.py`

Then go to `https://<container ip>/wiki/jsx`.

**Comment by abom** [comment]
For now, only Github formatted URLs are supported in include macro, other git URLs from other providers are not supported.

Any link that's not a valid github formatted link will be considered a raw link, will just download it and read its content.

**Comment by abom** [comment]
Include should support raw links and links from hosting services other than Github, the following should be added to documentation once we collect all of them into one place.

Including raw link:

```
!!!include("https://gitlab.com/threefoldforks/Threefold-Circles-back/raw/master/CODE_OF_CONDUCT.md", raw=True)
```

Including a custom link from gitlab.com as a host:

```
!!!include("threefoldforks:Threefold-Circles-back:CODE_OF_CONDUCT.md", host="gitlab.com")
```

**Comment by abom** [comment]
Documentation are now only at https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/wikis.

Macros are documented under https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/wikis/macro

For running own wiki and setting up service account
https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/wikis/tech

**Comment by Pishoy** [comment]
verified
- jsx version 
 ```
3BOTDEVEL:jsx:jumpscaleX_threebot: git log -1
commit a45a1bef5863a0c75900814950ff761f0e466c78 (HEAD -> development, origin/development, origin/HEAD)
Author: serboctor <boctor.sarah@gmail.com>
Date:   Wed Nov 6 17:29:42 2019 +0200

    Fix container destroy typo

```
