### ISSUE TITLE
can not create a network using TFT payment option in chatflow 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_threebot#610]
steps: network name --> TFT --> 1d --> IPV4 --> configure ip range myself & choose ip range for me 
error : below picture 
![image](https://user-images.githubusercontent.com/21987477/80363820-12766b80-8885-11ea-8cf2-70906ea5ec49.png)

- no wallet setted 
- jsx version 
```
root@3bot:/sandbox/code/github/threefoldtech/jumpscaleX_threebot# git log -1
commit 5e0e42c60eebed766f92addbb03f24a55fb47e07 (HEAD -> development, origin/development, origin/HEAD)
Author: Rana Tarek Hassan <tarekr@codescalers.com>
Date:   Sun Apr 26 16:03:52 2020 +0200

    Use currency from network instead of asking user in deploy solutions chatflows

```

**Comment by ranatrk** [comment]
Currently TFT is not supported, but an error is returned from the explorer indicating this. Will just make it visible in the chatflow

**Comment by Pishoy** [comment]
verified
