### ISSUE TITLE
3bot name too long for creating interface

### ISSUE THREAD

**Issue by maximevanhees** [threefoldtech/jumpscaleX_threebot#612]
As my 3bot name is "maximevanhees", when I setup my network and receive the wireguard .conf file I get an error:

![image](https://user-images.githubusercontent.com/25902145/80372302-a51e0700-8893-11ea-8fb8-d395d6bb8dcb.png)

As @grimpy pointed out this a related to the maximum length of network interfaces in Linux.

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/commit/e3a8f56259e57cbba1e4313e97acc458beef9bfa
