### ISSUE TITLE
env variables do not set in created ubuntu container by chatflow 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_threebot#613]
- am creating a ubuntu 16.04 container using chatflow and i set the env variable ` zosversion=2` but does not appear in container 

- the created container 
```
Solution name: testubuntu2
Version: ubuntu:16.04
CPU: 1
Memory: 1024
Public key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8o0jEGYqe2k7J0TNL6Gg8h86ic3ReiC6THlBnOKPDiKProj/4uMTmi1Qf5OcLIdeHgcP+zy+ZL4kpP7N6VTALRPiTn6Lty6ZP+5mQocaJYosoGLzB6+lx1NW/zXtscv4V3goULiDEx9SBzSuD8wS0k00iHcRjmuFUIfERyYR8mjmWC/sRf1Y7qk9kQjFOLW5Sw0+RLrxr4l2ur/n8bDVgGVpzWypKIsqRU6Rf1HdXWmdAMCucPAkxR5WNies5QFOkyllxI6Fq+G9M0Uf+EubpfpC1oOMWjNFy781M4KZF+FXODcBlwevfvk0HH/5mTHOymIfwVV8vjRzycxjuQib3 pishoy@Bishoy-laptop
Env variables: zosversion=2
Solution expiration: 1d
IP Address: 10.5.2.3
```

- ssh container 
```ssh root@10.5.2.3```
![image](https://user-images.githubusercontent.com/21987477/80379212-119e0380-889e-11ea-85df-a29b74ae7dcd.png)
- jsx  version 
```
3BOTDEVEL:3bot:jumpscaleX_threebot: git log -1
commit d83f639dd6cdfc69d56fc59a4979b3816ef5772c (HEAD -> development, origin/development, origin/HEAD)
Author: Rana Tarek Hassan <tarekr@codescalers.com>
Date:   Mon Apr 27 15:06:59 2020 +0200

    Pass bot to reservation register to view errors returned from register
3BOTDEVEL:3bot:jumpscaleX_threebot: 
```

**Comment by rkhamis** [comment]
Either we remove the question altogether or fix.

**Comment by grimpy** [comment]
I beleive we should remove the question alltogether I think the enviornments are only passed to the root/process aka entrypoint so it will not be passed on to the ssh server 

@zaibon is this correct?

So in the case of our ubuntu solution we should indeed just remove them (for flist solution it could be usefull)

**Comment by zaibon** [comment]
I think Jo's assumption is correct

**Comment by Pishoy** [comment]
verified
![image](https://user-images.githubusercontent.com/21987477/80416252-1e3d4e80-88d4-11ea-96a9-40e44f0af3b5.png)
