### ISSUE TITLE
old webgateway does not working using chatflow 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_threebot#615]
- i create a mino on my account and works well when i try to a Web Gateway point it fails  

steps : Select container (pishominio1) --> use 3bot.testnet.grid.tf --> Subdomain, the url will be (subdomain).bishoy.3bot.testnet.grid.tf (s3test2) 

error : something went wrong please contact support

- jsx version 
```
3BOTDEVEL:3bot:jumpscaleX_threebot: git log -1
commit d83f639dd6cdfc69d56fc59a4979b3816ef5772c (HEAD -> development, origin/development, origin/HEAD)
Author: Rana Tarek Hassan <tarekr@codescalers.com>
Date:   Mon Apr 27 15:06:59 2020 +0200

    Pass bot to reservation register to view errors returned from register

```

**Comment by Pishoy** [comment]
- threebot tmux logs
![image](https://user-images.githubusercontent.com/21987477/80383275-a9eab700-88a3-11ea-9f80-626e6648d568.png)

**Comment by grimpy** [comment]
This chatflow is not supported and will be removed
