### ISSUE TITLE
User should be able to choose all nodes for solutions

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_threebot#617]
For multi node solutions a user should be able to choose either:
 - the locations they want their solution to be deployed on
 - the farms they want their solutions to be deployed on

I think a user wouldn't need to choose the exact node, so we can choose the nodes in the farms/locations they choose for them

**Comment by ranatrk** [comment]
Initial attempt was to view all the farms through multiple select option in the chatbot, but since the farm number can be ~50 then this will overwhelm the user. So currently working on adding a filter option in the frontend of the chatbot with @waleedhammam

**Comment by BolaNasr** [comment]
Verified
