### ISSUE TITLE
chat package doesn't work

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#62]
can't get chat package to start with `kosmos -p 'j.threebot.package.chat.start()`

**Comment by siddiquagig** [comment]
I get the following error when starting it:

![image](https://user-images.githubusercontent.com/25789724/66712703-b305b200-edb1-11e9-97aa-13b2a2f3351b.png)

**Comment by abom** [comment]
@siddiquagig  make sure sonic is installed correctly.

**Comment by siddiquagig** [comment]
Sonic is installed correctly:

```
JSX> j.builders.apps.sonic.build()
'ALREADY DONE'

JSX> j.builders.apps.sonic.install()
'ALREADY DONE'
```

but now after updating all repos , i have a different error :

![image](https://user-images.githubusercontent.com/25789724/66899254-b300ee80-f00b-11e9-9f5d-7b28e8b2246e.png)

**Comment by xmonader** [comment]
@siddiquagig make sure to pull all jsx repos and run `jsx generate`

**Comment by siddiquagig** [comment]
Did pull all repos and jsx generate ,  same error still:

![image](https://user-images.githubusercontent.com/25789724/66913064-f2880480-f024-11e9-89c9-3ed2d3acf5b6.png)

**Comment by siddiquagig** [comment]
Working now after installing the required package ```pip3 install bottle_websocket```

![image](https://user-images.githubusercontent.com/25789724/66916240-e2275800-f02b-11e9-9224-2fdfda96a241.png)
