### ISSUE TITLE
Wallet Manager keeps on spinning - not activated after creation

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#620]
I create a new wallet (pushed button)
<img width="1278" alt="Schermafbeelding 2020-04-28 om 11 34 18" src="https://user-images.githubusercontent.com/30384423/80486605-c0544980-895b-11ea-964d-ae33c45cf938.png">

Then I click on the wallet address, but keeps spinning 
<img width="1278" alt="Schermafbeelding 2020-04-28 om 14 04 48" src="https://user-images.githubusercontent.com/30384423/80486692-e37ef900-895b-11ea-9f21-df1c679e7bbf.png">

It looks like activation hasn't happened. 
<img width="477" alt="Schermafbeelding 2020-04-28 om 14 17 26" src="https://user-images.githubusercontent.com/30384423/80486735-f2fe4200-895b-11ea-9d93-a1597537b592.png">

**Comment by gmachtel** [comment]
Error was due to Stellar service down on testnet. Best to improve error handling so you see what happened.

**Comment by siddiquagig** [comment]
Tested , is ok now

![image](https://user-images.githubusercontent.com/25789724/80591448-c6672a80-8a2e-11ea-88da-e3d70cd26362.png)

**Comment by zaibon** [comment]
Let's still make sure we show a proper error message when stellar is unreachable

**Comment by Dinaamagdy** [comment]
verified on development 
when cant connect to wallet raise right error (connection error)
![image](https://user-images.githubusercontent.com/24386802/80747890-65218300-8b24-11ea-95fc-a73540672c7c.png)
