### ISSUE TITLE
Implements a chat flow to reserve a 4to6 gateway

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#625]
Docs of 4to6: https://sdk3.threefold.io/#/capacity_gw4to6

- List gateway capable of 4to6 (no flag available yet)
- Ask the user if he would like to provide a wg public key or generate one for him
- make reservations/payment
- Allow user to download wg config (see network_create)

**Comment by BolaNasr** [comment]
Verified 
![image](https://user-images.githubusercontent.com/10259267/80725625-9dfd3000-8b03-11ea-8736-09213d0bc7b1.png)
