### ISSUE TITLE
Farm Management Page does not open

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/jumpscaleX_threebot#626]
Farm Management page keeps on loading after clicking on install required packages, tested on both mainet and testnet.

![image](https://user-images.githubusercontent.com/25789724/80589020-74240a80-8a2a-11ea-9dec-e93526eb014d.png)

![image](https://user-images.githubusercontent.com/25789724/80589040-7f773600-8a2a-11ea-967b-3b3674d6e62d.png)

Using : 3sdk v10.5 on ubuntu

```
root@3bot:/sandbox/code/github/threefoldtech/jumpscaleX_threebot# git log -1
commit 82dc566a0c014b7d4c30e493b5d7e73953667acf (HEAD -> master, tag: v10.5, origin/master)
Merge: 338fa1c9 fb239cd2
Author: rkhamis <reem.khamis@gmail.com>
Date:   Tue Apr 28 00:27:32 2020 +0200

    Merge branch 'development'
root@3bot:/sandbox/code/github/threefoldtech/jumpscaleX_threebot# git branch
* master
```

**Comment by Pishoy** [comment]
closing it, as it is already fixed in next that will be released of 3sdk
