### ISSUE TITLE
Solution wizard loading forever

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#628]
I just hit a bug where the solution chat flow is loading forever and never show the actual chat flows (network).

I access the GUI with https://localhost:4000

![2020-04-29_1346x1064_scrot](https://user-images.githubusercontent.com/303164/80600849-468c9080-8a2d-11ea-92ac-b3cdabe415e3.png)

Nothing special in the logs. I ended there cause I click on the resert button the top right corner of this chatflow.

Reloading the page doesn't solve it. Clicking on another solution doesn't solve it.

![2020-04-29_1502x418_scrot](https://user-images.githubusercontent.com/303164/80601358-fd890c00-8a2d-11ea-9417-4da1293766b3.png)

**Comment by zaibon** [comment]
I tried to connect to the GUI using the container IP, so https://172.17.0.2, and there is worked

**Comment by xmonader** [comment]
what is the branch for weblibs?
that was addressed a while ago on development branch of weblibs https://github.com/threefoldtech/jumpscaleX_weblibs/blob/development/static/gedis/gedis_package.js

and it was using hostname not host on master branch. I just merged development branch and hope that solves it.

**Comment by rkhamis** [comment]
loads

**Comment by achimha** [comment]
Just tried again with 10.5.1 on another machine and the problem did not show up.

**Comment by achimha** [comment]
The problems seems back with 10.5.2 on macOS. I deleted the 3bot container to be sure. Any chatbot invocation tries to do a REST call to https://localhost/zerobot/webinterface/actors/chatbot/session_new even though it should use port 4000 where the web app is loaded from.

**Comment by m-motawea** [comment]
Trying on weblibs master branch chatflow calls are ok.
![image](https://user-images.githubusercontent.com/32568986/81798038-d5120f00-950f-11ea-9012-ca4ecc057a40.png)

**Comment by Dina-Abd-Elrahman** [comment]
- cannot reproduce.
