### ISSUE TITLE
Need for adding trustlines in existing wallets in admin panel

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#629]
With the creation of new wallets, trustlines are created for known Threefold tokens. 
It could be, however, that a new token is created after the creation of the wallet. 

There needs to be a mechanism to scan all tokens for which a trustline should exist, and if not available, create it. 

Example: TFT and FreeTFT known at moment of wallet creation, but not yet TFTA.

**Comment by Dinaamagdy** [comment]
verified on development 
u can see update trustlines button in wallet manager page when u choose your wallet and if you press it will add your trustlines
![image](https://user-images.githubusercontent.com/24386802/80745207-399c9980-8b20-11ea-940f-33d3098d9163.png)
