### ISSUE TITLE
farm management screen is blank

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#630]
<img width="1271" alt="Schermafbeelding 2020-04-29 om 17 09 51" src="https://user-images.githubusercontent.com/30384423/80612873-d5ed7000-8a3c-11ea-8654-bec34927beed.png">

Config context: 
- SDK 10.5_OSX
- Chrome browser
- mainnet

**Comment by rkhamis** [comment]
Duplicate of #626
