### ISSUE TITLE
wrong url's used in wizards

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#632]
![image](https://user-images.githubusercontent.com/6021844/80676777-c95a2d80-8ab7-11ea-9a5a-25e689363ebb.png)

need to revisit how UI works, going to localhost while using a docker cannot be
is there a hard URL in the wizards somewhere?

lets review all URL's please and how they are used

**Comment by despiegk** [comment]
comes from Achim

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/80677050-6cab4280-8ab8-11ea-81b8-e026abc2b4c8.png)
bishoy on it as well

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/issues/628

Closing as duplicate, Achim confirmed it works on latest version
