### ISSUE TITLE
chat flow duration input improvement

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#637]
There needs to be some validation of the duration entered during chat flows.

The chat flows shows:
```
hour=h, day=d, week=w, month=M
I.e. 2 days = 2d
```
While you can enter things link `10m` and it will count as 10 minutes.

- [x] make some validation of the input and only accept units that are proposed
- [x] enforce minimum duration of 1H

**Comment by m-motawea** [comment]
PR: https://github.com/threefoldtech/jumpscaleX_core/pull/790

**Comment by grimpy** [comment]
Can we make it so if invliad data is enter we just ask again...

**Comment by m-motawea** [comment]
re-ask instead of error PR: https://github.com/threefoldtech/jumpscaleX_core/pull/791

**Comment by AhmedHanafy725** [comment]
In case of combining two type time like I need 1 year and 2 months (`1Y 2M`), it works and it shouldn't as year not supported.

![image](https://user-images.githubusercontent.com/41957921/80747128-3b1b9100-8b23-11ea-85bd-dc10ee8ac19e.png)

**Comment by grimpy** [comment]
Please fix the validator and allow years (add in description aswell)

**Comment by m-motawea** [comment]
PR: https://github.com/threefoldtech/jumpscaleX_core/pull/792

**Comment by AhmedHanafy725** [comment]
**Verified**

- Invalid char

![image](https://user-images.githubusercontent.com/41957921/80754503-6dcb8680-8b2f-11ea-8069-46a8bb8a8526.png)


![image](https://user-images.githubusercontent.com/41957921/80754445-59878980-8b2f-11ea-82ea-caab1386931c.png)


- Less that 1 hour
![image](https://user-images.githubusercontent.com/41957921/80754359-2e9d3580-8b2f-11ea-8386-5ca327a8e385.png)

![image](https://user-images.githubusercontent.com/41957921/80754404-407ed880-8b2f-11ea-9dd0-dd78fe6530f9.png)

- No char

![image](https://user-images.githubusercontent.com/41957921/80754564-86d43780-8b2f-11ea-96f9-0f7fe069fe6b.png)

![image](https://user-images.githubusercontent.com/41957921/80754604-96ec1700-8b2f-11ea-87c0-30c7efa329bc.png)

- Combine

![image](https://user-images.githubusercontent.com/41957921/80754672-b5eaa900-8b2f-11ea-84bd-83c66c3e3e1d.png)

![image](https://user-images.githubusercontent.com/41957921/80754729-d155b400-8b2f-11ea-8502-2be1c4ec0463.png)
