### ISSUE TITLE
chat flow duration: replace duration with date picker

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#638]
It is more intuitive for user to select an expiration date then a duration.
Instead of asking to enter weird duration code, use a nice data picker.

**Comment by waleedhammam** [comment]
PR at: https://github.com/threefoldtech/jumpscaleX_threebot/pull/658 and https://github.com/threefoldtech/jumpscaleX_core/pull/801

### Changelog
- Add the new datetimepicker component
 
![Screenshot from 2020-05-05 11-40-23](https://user-images.githubusercontent.com/10658229/81057234-504e4200-8ecc-11ea-89e8-46f4a5b8d2a4.png)
![Screenshot from 2020-05-05 11-42-32](https://user-images.githubusercontent.com/10658229/81057241-56dcb980-8ecc-11ea-82f0-51280f0bbc47.png)

___

- Add some validations to avoid empty/old dates
![Screenshot from 2020-05-05 11-40-34](https://user-images.githubusercontent.com/10658229/81057296-6f4cd400-8ecc-11ea-8933-ea07cd09ef57.png)

___

- Updated chatflows to use the new time picker

___
- Test some of the chat flows
![Screenshot from 2020-05-05 12-09-48](https://user-images.githubusercontent.com/10658229/81057342-84296780-8ecc-11ea-9a93-4a9914c043b3.png)

![Screenshot from 2020-05-05 12-14-11](https://user-images.githubusercontent.com/10658229/81057348-8a1f4880-8ecc-11ea-98c7-8f94562f8339.png)

![Screenshot from 2020-05-05 12-16-03](https://user-images.githubusercontent.com/10658229/81057359-8ee3fc80-8ecc-11ea-9616-9439d14163e4.png)

**Comment by AhmedHanafy725** [comment]
As per https://github.com/threefoldtech/jumpscaleX_threebot/issues/637#issue-609955035 there was a limitation on duration to not be less than 1 hour, now I can set date After now by 1 minute, is the limitation not needed in the new date picker?

**Comment by waleedhammam** [comment]
> As per [#637 (comment)](https://github.com/threefoldtech/jumpscaleX_threebot/issues/637#issue-609955035) there was a limitation on duration to not be less than 1 hour, now I can set date After now by 1 minute, is the limitation not needed in the new date picker?

set at https://github.com/threefoldtech/jumpscaleX_core/commit/f22237e5574e55473308dcbfc21279e68e0330b6

**Comment by AhmedHanafy725** [comment]
**Verified**
Branch: rc_10.5.3
threebot commit: 67ce0d84b2c615bf515eaa1141c0b1fcd78bbbdc
core commit: https://github.com/threefoldtech/jumpscaleX_core/commit/7d372250cb826cc070f90ac225df9b08f4810d35
