### ISSUE TITLE
Chat flow error message when wallet doesn't have enough found need to be improved

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#640]
We should catch these kind of error and show a nicer error message.
It is even maybe possible to warn the user before he tries to send the transaction to stellar since we can check the balance of the wallet.

![2020-04-30_2867x776_scrot](https://user-images.githubusercontent.com/303164/80714120-c598cc00-8af4-11ea-820e-9d6e27d25bd4.png)

**Comment by AhmedHanafy725** [comment]
**Verified**

There is a message now show that balance is not enough.

![image](https://user-images.githubusercontent.com/41957921/80741928-c2b0d200-8b1a-11ea-859f-1ebbf3f0de2a.png)
