### ISSUE TITLE
show secret button in wallet details is not reactivated after updating trustlines

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/jumpscaleX_threebot#645]
**steps to reproduce**:
- show wallet details
- click show secret 
- Click on update trustlines

secret is still hidden and show secret button is disabled 
![Screenshot from 2020-04-30 17-58-46](https://user-images.githubusercontent.com/36021484/80733108-8cb92100-8b0d-11ea-8a63-c9237539718c.png)

**Comment by dmahmouali** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/a2af2f87f6782c297288a12fe9bec654813f4f84

- [x] enabled

**Comment by Dinaamagdy** [comment]
verified on development
