### ISSUE TITLE
admin panel: Remove wiki from the left side menu

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/jumpscaleX_threebot#646]
it's trying to install mdbook but the repo was updated to run with the new Publishing tool.

```
Error has happened during this operation: {"error": "\nCould not execute: cd /sandbox/code/github/threefoldfoundation/info_threefold/ && mdbook build\n\nstderr:\n 2020-05-01 09:34:13 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md\n 2020-05-01 09:34:13 [ERROR] (mdbook::utils): Caused By: No such file or directory (os error 2)\n\n"}
```
3sdk 10.5.2
ubuntu 18.04

![image_roesau](https://user-images.githubusercontent.com/13523434/80801953-30f2a480-8bae-11ea-9c04-295b6bae47ee.png)

![image_1lt3jz0](https://user-images.githubusercontent.com/13523434/80801975-42d44780-8bae-11ea-90db-b57c7e4bd2af.png)

**Comment by despiegk** [comment]
remove the wiki package & from the left menu please,
check quickly in documentation if there is something left, we will re-enable wiki in a next release
