### ISSUE TITLE
I could not load my wallet on my 3bot, am blocked

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#647]
![image](https://user-images.githubusercontent.com/6021844/80811196-addd4880-8bc5-11ea-9912-75ea68ce04ab.png)

![image](https://user-images.githubusercontent.com/6021844/80811210-b6358380-8bc5-11ea-91db-308589501efc.png)

![image](https://user-images.githubusercontent.com/6021844/80811215-b9c90a80-8bc5-11ea-8d9d-4e8bd855aef4.png)

**Comment by grimpy** [comment]
@despiegk I couldnt reproduce this and the stacktrace you showed seem to indicated the wallet does not exists (not activated). How did you create this wallet and did it go wrong there?

Maybe the alert of 5-1 15:26:13 has some interesting information?
