### ISSUE TITLE
ssh key management on windows blocked

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#648]
clearly not good enough

or documentation needs to improve or our code needs to be smarter !

https://forum.threefold.io/t/3sdk-simulator-installation-help-needed-win10/411/5

**Comment by rkhamis** [comment]
clearer step by step docs added: https://github.com/threefoldtech/jumpscaleX_core/blob/development/docs/3sdk/3sdk_windows.md
