### ISSUE TITLE
we need step by step manual [development_getting_started]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#649]
![image](https://user-images.githubusercontent.com/6021844/80812671-acf9e600-8bc8-11ea-95d5-8c0ea54c0789.png)

starting from zero to deploying something

**Comment by despiegk** [comment]
for most people the manual is not clear enough

**Comment by grimpy** [comment]
https://github.com/threefoldfoundation/info_tfgridsdk/compare/development...development_getting_started

Worked already started and can be continued on the existing branch

**Comment by zaibon** [comment]
it's live: https://sdk.threefold.io/#/getting_started_first_solution
