### ISSUE TITLE
Getting Started Manual - Deploy website

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/jumpscaleX_threebot#653]
Create a manual with steps to deploy a website from scratch:

**Suggested flow:**
- [ ] Package website into an flist (either converting docker image or using jumpscale)
- [ ] Deploy a container with the flist created 
- [ ] configure web gateway to expose the website over the customer domain

**Comment by zaibon** [comment]
To create an flist, you can also just upload a tar archive to the hub. This is probably the easiest and straight  forward way to do it. `zflist` CLI is also available: https://github.com/threefoldtech/0-flist#zflist

**Comment by ranatrk** [comment]
moved to repo for manuals https://github.com/threefoldfoundation/info_tfgridsdk/issues/94
