### ISSUE TITLE
Chatflow for capa reservation doesn't work when node doesn't have a valid Stellar address

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#654]
If capacity is reserved on a node that doesn't have a public Stellar wallet address defined, reservation fails. So there should be filtering put in place to exclude these nodes. 

On mainnet, this will lead to substantial reduction of valid nodes until 3Bot connect app wallet is released (later this week).

**Comment by grimpy** [comment]
![image](https://user-images.githubusercontent.com/143869/81019355-c61fc280-8e66-11ea-967a-3fe928069d02.png)

Seems that even farms that have the 'TFT' address filled have bogus addresses...
https://explorer.grid.tf/explorer/farms/1
https://horizon.stellar.org/accounts/GD3DUMWG2I2AD2ZVZ3KA77NQP75TXNUXWQXLCROGC4ANZ657RZENC6OD

I'm not sure how to progress from here... should we really validate those aswell?

**Comment by gmachtel** [comment]
I think these 'bogus' addresses were created before Stellar network reset. Best is to have all Stellar addresses deleted at the same time as Stellar testnet reset.

**Comment by zaibon** [comment]
There were address set there before we enabled validation of the address. Nothing to do with the stellar reset, we're talking mainnet here, there is no reset happening.
I asked @andhartl to update the addresses on freefarm to put valid ones.

**Comment by grimpy** [comment]
Related: https://github.com/threefoldtech/tfexplorer/issues/51

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_libs/pull/192

**Comment by Dinaamagdy** [comment]
for TFT currency return the following error :
![image](https://user-images.githubusercontent.com/24386802/81159189-02e3da80-8f89-11ea-9462-6075d8aa3c02.png)

**Comment by Dinaamagdy** [comment]
verified on branch  rc_10.5.3
