### ISSUE TITLE
Make sure to enter a solution name while deploying 

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_threebot#655]
When I don't enter the solution name, it takes it empty and will crash of course later, maybe we can enforce user to enter it or generate random name, but since we save the reservations it stored also on the explorer so even after destroying the model it will crash. so had to cancel the reservation manually
![IMG_20200504_182344_097](https://user-images.githubusercontent.com/10658229/80988922-7de7ac80-8e34-11ea-8a9c-affe405ab41f.jpg)

**Comment by Dina-Abd-Elrahman** [comment]
- verified
