### ISSUE TITLE
admin panel: changing network doesn't seems to actually work

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#659]
The flow :
1. start threebot container on testnet network
2. go to setting page, change to mainnet
3. try to deploy a solution, specify a node ID from mainnet
4. error: `Node J1Xb2piba1vZM2pSmWP24CPgREnoTce7EuUJysttCyz6 doesn't seem to be up please choose another nodeid
Please enter a different nodeid to deploy on or leave it empty`

Expected behavior: changing the network in the setting should make everything in the admin panel switch to this network:
- explorer client
- setllar wallet
- deployed solutions
- possible identity

**Comment by Dina-Abd-Elrahman** [comment]
- verifed.
