### ISSUE TITLE
expose solution chat flow: give more explanation of what is going to be created

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#664]
one thing we could improve when we expose a solution is explain a bit what is happening
I had to pay some tokens while the gateway are free now so I was a bit surprised.

I understand it is because of the tcprouter container but we probably could explain this during the chat flow.

**Comment by ranatrk** [comment]
The overview before the payment will now look like this : 
![Screenshot from 2020-05-07 11-08-43](https://user-images.githubusercontent.com/17128393/81279189-165d7700-9057-11ea-952d-dab227a33ea1.png)

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/82217417-a97d9300-991a-11ea-8566-6cfdf254a761.png)
 - jsx version 
```
root@bishoy_testnet:/sandbox/code/github/threefoldtech/jumpscaleX_threebot# git log -1
commit a7a61bb6b949c89890a8a531740c229a71ff3304 (HEAD -> development, origin/development, origin/HEAD)
Merge: 3feaef0f b0950ac0
Author: Reem Khamis <khamisr@codescalers.com>
Date:   Mon May 18 14:11:50 2020 +0200

    Merge pull request #706 from threefoldtech/development_validatePackageTomlContent
    
    validate package toml config


```
