### ISSUE TITLE
admin panel: when reserving capacity with chatflow, opening calendar shows date in the past

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#670]
When creating a workload, expiry date is now shown as a calendar day, but flist chatflow shows timestamp in the past as proposed date.

**Comment by ranatrk** [comment]
The default date was set correctly but the time was in the beginning of the default date. The default time is now set to be 2 hours from the current time

https://github.com/threefoldtech/jumpscaleX_threebot/commit/3306457136c651a3559de050596f46a637f391b2

**Comment by AhmedHanafy725** [comment]
**Verified**
Branch: development
core: https://github.com/threefoldtech/jumpscaleX_core/commit/53eef55cfed1045a15fef2173f863ad0335e34b4
threebot: 5efa5a0412af68de2942c7bf28277f036eaf0dc2
 
Time is set to be after now by 1 hour and 5 mins

![image](https://user-images.githubusercontent.com/41957921/82207780-ab3f5a80-990a-11ea-98fb-fd69e73c72f6.png)
