### ISSUE TITLE
port not shown in 'deployed solutions' after flist reservation

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#671]
When reserving through an flist, at the end you get an ip-address:port which you can use for accessing your workload, in the chatflow. 
![image](https://user-images.githubusercontent.com/30384423/81404770-8ee73500-9136-11ea-96f6-22dabf6421f5.png)

However, when consulting afterwards in the deployed solutions, the port is nowhere specified. 

![image](https://user-images.githubusercontent.com/30384423/81404828-ade5c700-9136-11ea-984c-d25bf52100ad.png)

Making that the workload might be inaccessible if not remembered well.

**Comment by dmahmouali** [comment]
port is shown in 'deployed solutions' after flist reservation
commit:https://github.com/threefoldtech/jumpscaleX_threebot/commit/d3c0ebe32fb2d67626597c3470200994c56cb7e9

**Comment by AhmedHanafy725** [comment]
Branch: development
commit: ff742f685921038c591234977fc191146e465fed

I tried to deploy flist using chatflows and after it finished, I didn't find port on the deployed flist.

![image](https://user-images.githubusercontent.com/41957921/82575813-3c236980-9b89-11ea-8661-64bab2e21278.png)

**Comment by dmahmouali** [comment]
Added commit: https://github.com/threefoldtech/jumpscaleX_libs/commit/e4360a81ecbf73b403b9401a8be543b86c34ef71
Fixed on development - jumpscaleX_libs
![photo_2020-05-22_01-17-46](https://user-images.githubusercontent.com/36021484/82615186-1b2f3880-9bca-11ea-9139-784c752dc470.jpg)

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** rc_10.6
**libs:** https://github.com/threefoldtech/jumpscaleX_libs/commit/ded1bcc2af60e7ff226d642eb21568a49d339007
**threebot:** a9aca99fb37d0d9e866731d9f3dca06f98cb96b8

![image](https://user-images.githubusercontent.com/41957921/83137321-4691b600-a0e9-11ea-9228-23b823605148.png)
