### ISSUE TITLE
installation of TF Simulator in admin panel gives an error (MacOS)

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#672]
Used the latest available sdk for MacOS

![image](https://user-images.githubusercontent.com/30384423/81405062-3b291b80-9137-11ea-8f42-bfbf1a6f3be8.png)
![image](https://user-images.githubusercontent.com/30384423/81405087-4a0fce00-9137-11ea-8aac-bf3d35ed5008.png)

**Comment by m-motawea** [comment]
Fixed on branch rc_10.5.3 in repos: jumpscaleX_core, jumpscaleX_libs, jumpscaleX_builders

**Comment by m-motawea** [comment]
image updated and pushed

**Comment by hossnys** [comment]
Verified on branch ```rc_10.5.3``` 

![Screenshot from 2020-05-11 15-31-53](https://user-images.githubusercontent.com/26298009/81567585-cce59280-939c-11ea-9a3f-6fc0b9051cde.png)

![Screenshot from 2020-05-11 15-32-02](https://user-images.githubusercontent.com/26298009/81567590-cf47ec80-939c-11ea-9a51-4638cc807835.png)

![Screenshot from 2020-05-11 15-34-41](https://user-images.githubusercontent.com/26298009/81567595-cfe08300-939c-11ea-9f2d-800924e4adc6.png)
