### ISSUE TITLE
restart of 3bot fails

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#674]
Tried to restart a container, after it was started the previous day, using different options, but it fails. 
`container start` gives "Cannot use console in non-interactive mode" (but nothing specified there)
`container threebot restart=True`gives : 
![image](https://user-images.githubusercontent.com/30384423/81406207-73315e00-9139-11ea-9f73-bf66514799aa.png)

It shows that we need to build a smooth user experience, because users won't understand what to do.

**Comment by waleedhammam** [comment]
in that case:

we have an old container named 3bot and another new threebot container running with the same port range

container threebot starts/creates a container named 3bot. So it will conflict with port ranges

So either we make container threebot takes a name, or we stick to only one container named `3bot`

**Comment by m-motawea** [comment]
on branch rc_10.5.3
restart in 3sdk
```bash
3sdk> container stop
3sdk> container start server=True
```

```bash
3sdk> threebot restart
```

```bash
3sdk> threebot stop
3sdk> threebot start
```

in container shell
```bash
root@3bot:/sandbox# 3bot restart
```

```bash
root@3bot:/sandbox# 3bot stop
root@3bot:/sandbox# 3bot start
```

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
