### ISSUE TITLE
admin panel sidebar has no scrollbar

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#675]
Admin sidebar has no scrollbar, so if lines in sidebar are rolled out, the last lines become unreachable. 
If 'solutions' opened, all below Wallets manager becomes unreachable. 

OK: 
![image](https://user-images.githubusercontent.com/30384423/81409700-df16c500-913f-11ea-9f76-e020d3111c55.png)

After opening solutions: 
![image](https://user-images.githubusercontent.com/30384423/81409746-edfd7780-913f-11ea-82ce-b5f43c9ac4d3.png)

**Comment by ranatrk** [comment]
issue duplicate to item in https://github.com/threefoldtech/jumpscaleX_core/issues/797
