### ISSUE TITLE
Jumpscale SDK Farm Settings: Remove wallet address button removes the wrong address

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/jumpscaleX_threebot#676]
![1](https://user-images.githubusercontent.com/1249806/81410304-cd81ed00-9140-11ea-8c99-9b1885b5ead9.png)
![2](https://user-images.githubusercontent.com/1249806/81410321-d1157400-9140-11ea-886d-d7f36c9f64d6.png)

**Comment by AhmedSa-mir** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/72f77c416637a1b1614b41f0f510b8cfa182b410
Fixed remove wallet address button

**Comment by Dina-Abd-Elrahman** [comment]
- verified

**Comment by joefoxton** [comment]
@Dina-Abd-Elrahman @AhmedSa-mir 
How do I get my hands on this fix? Do I need to reinstall a new version Jumpscale?

**Comment by AhmedSa-mir** [comment]
@joefoxton Make sure you pull the latest version of jumpscaleX_threebot repo

**Comment by rkhamis** [comment]
@joefoxton this is yet unreleased. if you're comfortable with unreleased development, then you can just change your branches to "development" and pull :)

**Comment by joefoxton** [comment]
I’ll wait until its released. When might that be?

Will my workloads keep running before and after the upgrade?

**Comment by rkhamis** [comment]
@joefoxton by the end of the week if everything goes as planned
your workloads would be unaffected

**Comment by joefoxton** [comment]
Fantastic :)
