### ISSUE TITLE
simulator playground upgrade

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#677]
Code in https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/tfgrid_solutions/simulator_playground

- Check how can we load it with tokens and update the money flow in the package
- Update the package to allow reserving a 3bot container for 6 hours to start the simulator (Rate limit the creation per IP)
- Make sure it's back up & running
- Check saving/restoring layouts https://github.com/jupyterlab/jupyterlab/issues/502

**Comment by m-motawea** [comment]
- fixing the package
- rate limiting
https://github.com/threefoldtech/jumpscaleX_threebot/pull/697

**Comment by m-motawea** [comment]
mounting code & var on vols
https://github.com/threefoldtech/jumpscaleX_threebot/pull/704

**Comment by Dina-Abd-Elrahman** [comment]
- the chat is deployed on this url
http://play.grid.tf/tfgrid_solutions/simulator_playground/chat/simulator_playground
