### ISSUE TITLE
Get notified about new SDK versions

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/jumpscaleX_threebot#679]
As there are many fixes being applied to the SDK, what is the process for being notified about a new release, along with release notes?

**Comment by grimpy** [comment]
For the time being you can go to https://github.com/threefoldtech/jumpscaleX_core/releases
![image](https://user-images.githubusercontent.com/143869/81794936-cc1f3e80-950b-11ea-8fca-7a09b91f1317.png)

A feature to do updated will be added in 10.6, but untill you have 10.6 updates will need to be done manually

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_core/issues/838

feature was added here
