### ISSUE TITLE
GE: Can't set city location of farms/nodes

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/jumpscaleX_threebot#680]
Currently, this is what we see for location on a node:

Location
United States, Uknown

Two problems:
1. Unknown is mispelled
2. We have no way to set the city, which will be important as we market to users who want hyperlocal access

**Comment by AhmedSa-mir** [comment]
![Screenshot from 2020-05-13 11-20-31](https://user-images.githubusercontent.com/18093386/81795322-48b21d00-950c-11ea-8a53-076a98294188.png)

@zaibon We need to update it in explorer

**Comment by ranatrk** [comment]
Based on https://github.com/threefoldtech/tfexplorer/pull/86 only farm locations can be changed and node locations shouldnt be. 
Currently supported is changing the farm country only, will update it to include the city

**Comment by joefoxton** [comment]
FYI. We are in the process of moving our Cape Town modes to Johannesburg so we can get IPv6.
