### ISSUE TITLE
3sdk Chat kubernetes Cluster starts with "Chat has ended" 

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/jumpscaleX_threebot#683]

**Comment by grimpy** [comment]
@hteibler I can't reproduce this, are there any special steps to follow here?

**Comment by AhmedHanafy725** [comment]
**Verified**
Branch: development
core: https://github.com/threefoldtech/jumpscaleX_core/commit/53eef55cfed1045a15fef2173f863ad0335e34b4
threebot: 5efa5a0412af68de2942c7bf28277f036eaf0dc2

![image](https://user-images.githubusercontent.com/41957921/82204634-8bf1fe80-9905-11ea-9386-d55ddaaca633.png)
