### ISSUE TITLE
GE: Health Check Status BCDB Error?

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/jumpscaleX_threebot#684]
![image](https://user-images.githubusercontent.com/24313736/81649258-51352580-9430-11ea-8a49-a1f4010bd01d.png)

**Comment by dmahmouali** [comment]
Can't reproduce a bug, please could you add more details?

**Comment by waleedhammam** [comment]
@hteibler are there any alerts in alerts pane ? also can you provide logs with appname threebot server in the logs tab ?

**Comment by hteibler** [comment]
already deleted this VM 
no more infos
