### ISSUE TITLE
Split-up of bill about what is to be paid is not shown 

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#688]
We need to show how the capacity bill is split up. 
This transparency is a mandatory element on an invoice/receipt. How much goes to seller, how much is VAT. Here we don't have VAT yet but we have the % going to TFF. It's not yet shown to the user, see screenshot.

Example : 

`Farmer A -------------------- 30.0 TFT`
`Farmer B -------------------- 60.0 TFT`
`Threefold Foundation -------- 10.0 TFT`
`Transaction Fee -------------- 0.1 TFT`
`--------------------------------------`
`TOTAL ---------------------- 100.1 TFT`

Needs to be shown : 
- [x] during the capacity reservation (in all chatflows that have payment inside, before confirmation)
- [ ] ~~after reservation has been made, in 'Deployed solutions' details~~

**Comment by grimpy** [comment]
This kind of issue makes me wonder if the sdk is still and sdk or it's a marketstore... if it's a marketstore the way we do wizards now and so should be changed to a fullblown ui

**Comment by gmachtel** [comment]
Very good point, this is a feature that is goes beyond the ‘simple’ need for developers to have tooling to access the grid. 
But a) I think it was already evolving that direction (I also hear optimisations in the chatflow), and b) if money is involved, you have the legal obligation to be transparent about where money goes to. 
 I don’t knows if there are plans other than the sdk to create a full-blown marketplace however.
