### ISSUE TITLE
Cannot expose port for flist

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/jumpscaleX_threebot#689]
I deployed a custom flist solution and tried to expose a port.

![image](https://user-images.githubusercontent.com/7256303/81703576-156c8100-946d-11ea-888b-53be58f0fe96.png)

**Comment by m-motawea** [comment]
Can you please add which network you are connected to testnet, mainnet, devnet?
and which currency you used to create the flist (network which flist is connected to) TFT or FreeTFT?

**Comment by rkhamis** [comment]
Indeed there was no gw deployed then on testnet.
