### ISSUE TITLE
Page loading indefinitely when attempting to create a ubuntu container on the grid

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/jumpscaleX_threebot#691]
Seems to redirect me to the payment screen, but sometimes it's stuck on this page.

![image](https://user-images.githubusercontent.com/7256303/81694413-94f45300-9461-11ea-9316-c3bfc8a562ee.png)

**Comment by grimpy** [comment]
it would probably have giving you reservation failed to deploy in x time if you waited long enoug.

@ranatrk let's add a timer here that updates the time reiaming like we do during payments

**Comment by ranatrk** [comment]
Added showing loading of payment and deployment with the remaining time until it expires. If payment or deployment failed an error will be shown and if the expiration time show was finished then the deployment will be cancelled

**Comment by AhmedHanafy725** [comment]
**Verified**
Branch: development
libs: https://github.com/threefoldtech/jumpscaleX_libs/commit/268a841dc98a192c061139395a7a7f695cb49d1f
threebot: ddb70732c4e01fbd0c0773eb06c2b84a6adbbb94

Now there is a timer with the remaining time.

![image](https://user-images.githubusercontent.com/41957921/82218789-b4392780-991c-11ea-8471-d3bb3597541a.png)
