### ISSUE TITLE
Chatflows when entering a text field like solution named and using keyboard enter key the chatflow is restarted

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_threebot#692]
We need to make sure the default selected action on keyboard enter is next not back nor refresh

**Comment by ahelsayd** [comment]
commit https://github.com/threefoldtech/jumpscaleX_threebot/commit/aee153e0e7c81d873d1384ffeedb07cf144dfe7d

**Comment by AhmedHanafy725** [comment]
**Verified**
Branch: development
commit: 35454a9d7800eb7dd478a12c2820d383eb83ad9c
