### ISSUE TITLE
error with creating same network naming in network reservation in chatflow soultions

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_threebot#694]
- issue in creating a network as below 
![image](https://user-images.githubusercontent.com/21987477/81834459-3c948280-9541-11ea-9d65-c0fc5cf4080a.png)

 - sdk version is 10.5.2 with branch master and latest

**Comment by AhmedSa-mir** [comment]
In the networks solutions tab, I get an expired network in my networks list. Maybe there is an issue with expired network deletion.
![Screenshot from 2020-05-14 09-39-58](https://user-images.githubusercontent.com/18093386/81906802-19141b00-95c7-11ea-94ea-8a18f33167af.png)

**Comment by AhmedSa-mir** [comment]
Resolved issue by checking for duplicate network name.
https://github.com/threefoldtech/jumpscaleX_threebot/commit/5a133135fa4449327f4b81aaee788cf4bd2435f6 , https://github.com/threefoldtech/jumpscaleX_libs/commit/5cbbc8c9265477cfb72528eb21ff63bfe1ba2945

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
