### ISSUE TITLE
Need clear docs for wikis 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#7]
### missing clear and organized docs for wikis which should contain  :
- how to install wikis 
- features

**Comment by abom** [comment]
[This end-user docs](https://github.com/threefoldtech/digitalmeX/tree/development/docs/publishing_platform/wiki) are still relevant.

**Comment by abom** [comment]
@andrewayoub Can you reference the docs you wrote here? then put this issue to verification.

**Comment by andrewayoub** [comment]
https://github.com/threefoldtech/jumpscaleX_libs_extra/blob/development/JumpscaleLibsExtra/tools/threebot_deploy/README.md

**Comment by Pishoy** [comment]
verified
