### ISSUE TITLE
starting calendar raises an error 

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/jumpscaleX_threebot#70]
I started a bcdb server and tried to start a calendar instance but it raises the following error.

```python
3BOTDEVEL:3bot:/: kosmos -p "j.threebot.package.calendar.start()"
Mon 14 09:47:26 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.circle.2
Mon 14 09:47:26 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.user.2
Mon 14 09:47:26 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.client
Mon 14 09:47:26 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.server
Mon 14 09:47:26 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.websocket.1
Mon 14 09:47:26 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_custom
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_lapis
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_proxy
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_static
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.server.1
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.website
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.sonic.server.1
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.startupcmd.1
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot.package.1
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot_server.1
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.zdb.client.1
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.zdb.server.1
Mon 14 09:47:27 BCDB.py              -  87 - bcdb                               : BCDB INIT DONE:system
Mon 14 09:47:27 db39ba5615b225d6b.py -  31 - 1_a2ceb60df57b6ecdb39ba5615b225d6b : init index:jumpscale.threebot_server.1
Mon 14 09:47:27 adb60367236085428.py -  31 - 1_e65b143683ae0fdadb60367236085428 : init index:jumpscale.threebot.package.1
Mon 14 09:47:27 554491cc4784debd0.py -  31 - r_d62bc1899d73f8c554491cc4784debd0 : init index:jumpscale.gedis.server
Mon 14 09:47:27 BuilderBaseClass.py  - 147 - openresty                          : no need to do: openresty:{'kwargs': <class 'inspect._empty'>}, was already done
Mon 14 09:47:27 BuilderBaseClass.py  - 147 - lua                                : no need to do: lua:{'deps_reset': False}, was already done
Mon 14 09:47:27 BuilderBaseClass.py  - 147 - lua                                : no need to do: lua:{}, was already done
Mon 14 09:47:27 99aa9ab6c282bc932.py -  31 - 1_76f6215e7a241d899aa9ab6c282bc932 : init index:jumpscale.openresty.server.1
Mon 14 09:47:27 1c77f4579afba29aa.py -  31 - 1_f5b081f1ef927551c77f4579afba29aa : init index:jumpscale.zdb.client.1
Mon 14 09:47:27 BCDBFactory.py       - 311 - bcdbfactory                        : new bcdb:caldav
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.circle.2
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.user.2
Mon 14 09:47:27 BCDB.py              -  87 - bcdb                               : BCDB INIT DONE:caldav
Mon 14 09:47:27 BCDB.py              - 446 - bcdb                               : load model:tf.caldav.user.1
Mon 14 09:47:27 loader/CodeLoader.py -  85 - load                               : EXCEPTION: 
    SCRIPT CONTENT:
    import vobject
    from carddav import carddav
    import datetime
    from Jumpscale import j


    class addressbook(j.baseclasses.threebot_actor):
        def _init(self, **kwargs):
            self.base_url = "http://127.0.0.1:8851"
            self.client = None

        def login(self, username, password, addressbook=None, user_session=None):
            """
            ```in
            username = (S)
            password = (S)
            ```
            """
            self.client = j.clients.carddav.get(
                resource=f"http://172.17.0.2:8851/{username}", user=username, passwd=password
            )
            self.username = username

        def _verify_client(self):
            if not self.client:
                raise j.exceptions.Runtime("Use login method to enable the actor")

        def list_addressbooks(self, schema_out=None, user_session=None):
            """
            ```out
            addressbooks = (dict)
            ```
            returns dict of addressbooks {hrefs:etags}
            """
            self._verify_client()
            addressbooks = self.client.list_abooks()
            output = schema_out.new()
            output.addressbooks = addressbooks
            return output

        def add_addressbook(self, name, description, href=None, user_session=None):
            """
            ```in
            name = (S)
            description = (S)
            href = (S)
            ```
            """
            self._verify_client()
            self.client.create_abook(name, description, href)
            return True

        def get_addressbook(self, addressbook_id, schema_out=None, user_session=None):
            """
            ```in
            addressbook_id = (S)
            ```
            ```out
            addressbook = (dict)
            ```
            returns dict of addressbook vcards {hrefs: etags}
            """
            self._verify_client()
            addressbook = self.client.get_abook(addressbook_id)
            output = schema_out.new()
            output.addressbook = addressbook
            return output

        def delete_addressbook(self, href, user_session=None):
            """
            ```in
            href = (S)
            ```
            """
            self._verify_client()
            self.client.delete_abook(href)
            return True

        def add_vcard(self, vcard, href, user_session=None):
            """
            ```in
            vcard = (S)
            href = (S)
            ```
            Adds a new vcard to an address book
            """
            self._verify_client()
            self.client.upload_new_card(vcard, href)
            return True

        def get_vcard(self, href, user_session=None):
            """
            ```in
            href = (S)
            ```
            """
            self._verify_client()
            return self.client.get_vcard(href)

        def delete_vcard(self, href, etag=None, user_session=None):
            """
            ```in
            href = (S)
            etag = (S)
            ```
            if etag is provided will only delete if etag is matched
            """
            self._verify_client()
            if not etag:
                etag = None
            self.client.delete_vcard(href, etag)
            return True

        def find_vcards(self, text, addressbook_href, schema_out=None, user_session=None):
            """
            ```in
            text = (S)
            addressbook_href = (S)

            ```
            ```out
            vcards = (LS)
            ```
            """
            self._verify_client()
            if not addressbook_href:
                vcards = []
            else:
                vcards = self.client.find_vcards(text, addressbook_href)
            output = schema_out.new()
            output.vcards = vcards
            return output

        def update_vcard(self, vcard, href, etag=None, user_session=None):
            """
            ```in
            vcard = (S)
            href = (S)
            etag = (S)
            ```
            if etag is provided will only update if etag is matched
            """
            if not etag:
                etag = None
            self.update_vcard(vcard, href, etag)
            return True

    ---------------------------------
    COULD not load source:/sandbox/lib/jumpscale/threebot_packages/threebot/calendar/actors/addressbook.py
    ERROR WAS:No module named 'vobject'
--TRACEBACK------------------
<string> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/ThreeBotFactoryBase.py in start
    43    self.install()
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/ThreeBotFactoryBase.py in install
    36    package.prepare()
/sandbox/lib/jumpscale/Jumpscale/tools/threebot_package/ThreeBotPackage.py in prepare
    72    self._init_before_action()
/sandbox/lib/jumpscale/Jumpscale/tools/threebot_package/ThreeBotPackage.py in _init_before_action
    61    self.gedis_server.actors_add(path, namespace=self._package_author.actors_namespace)
/sandbox/lib/jumpscale/Jumpscale/servers/gedis/GedisServer.py in actors_add
    135    self.actor_add(file_path, namespace=namespace)
/sandbox/lib/jumpscale/Jumpscale/servers/gedis/GedisServer.py in actor_add
    156    self.cmds_meta[key] = GedisCmds(server=self, path=path, name=name, namespace=namespace)
/sandbox/lib/jumpscale/Jumpscale/servers/gedis/GedisCmds.py in __init__
    54    klass = j.tools.codeloader.load(obj_key=cname, path=path, reload=False)
/sandbox/lib/jumpscale/Jumpscale/tools/codeloader/CodeLoader.py in load
    85    raise j.exceptions.Base(msg)
-----------------------------

Mon 14 09:47:28 BCDB.py              - 338 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
Mon 14 09:47:29 BCDB.py              - 338 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
3BOTDEVEL:3bot:/: 

```

**Comment by serboctor** [comment]
Calendar works fine with me. This error doesn't relate to the calendar specifically, it's a bcdb bug/issue. @zaibon got this error too before. Chris, did you open a ticket for it or manage to figure out the issue?

**Comment by zaibon** [comment]
not really figure out the source of the error no. I just destroyed my BCDB instance and started from scratch... which is not a solution in itself :-/

**Comment by siddiquagig** [comment]
Calendar is working and  :

![image](https://user-images.githubusercontent.com/25789724/67288295-befa1e00-f4ed-11e9-9bb5-6f0e91fd36fb.png)
