### ISSUE TITLE
400 Bad Request error when install required package for network solution 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_threebot#707]
steps: 

1 - create a new sdk installation and go to shell
 ```
 ~/Downloads/3sdk_v10.5.3_linux_x86_64 container install name=bishoy_testnet
~/Downloads/3sdk_v10.5.3_linux_x86_64 container shell name=bishoy_testnet
```
2 - switch to development branch and pull all repos inside container 
3 - start theeebot `3bot start `
4 - git error when install network package 
![image](https://user-images.githubusercontent.com/21987477/82212686-391f4380-9913-11ea-9540-ca188617ac69.png)
5 - refresh network package page 
![image](https://user-images.githubusercontent.com/21987477/82212936-a59a4280-9913-11ea-8e78-8cb7cad17aed.png)

- bottle server logs 
https://gist.github.com/Pishoy/7f05ab05e3f3b491d33bb3264e1cdb3f

- host ubuntu 18.04

**Comment by BolaNasr** [comment]
@Pishoy 
Please pull all repos and run this command ```js_init generate```
https://gist.github.com/Pishoy/7f05ab05e3f3b491d33bb3264e1cdb3f#file-bottle_server-L112

the error in that line mean you don't have chatflow in ```j.servers``` and it's already exist.

![image](https://user-images.githubusercontent.com/10259267/82214048-74227680-9915-11ea-807e-84aeaec34509.png)

**Comment by Pishoy** [comment]
verified
