### ISSUE TITLE
GE: Minio deployment endet with "something went wrong please contact support"

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/jumpscaleX_threebot#708]
after entering all parameter and payment
I got this error, and no more info...

could maybe nr: 9511

chatflow: minio
Solution name: gs31
Disk type: HDD
Access key: miniog1
Secret: m987654321
CPU: 1
Memory: 1024
Locations: 6
Locations allowed to fail: 2
ZDB number: 8
Solution expiration: 1w 5d 12h 31m 3s

**Comment by hteibler** [comment]
how can I export the log, where can I find it in cli

**Comment by BolaNasr** [comment]
@hteibler 

goto your dashboard and press in logs in your left hand like the screenshot in the comment above.

Then select from list box ```threebot server```
and goto the last page and screenshot this page please

**Comment by hteibler** [comment]
![image](https://user-images.githubusercontent.com/24313736/82234268-798dba00-9931-11ea-85f5-1448b8978173.png)

**Comment by BolaNasr** [comment]
This log after errror of the minio reservation from minio chatflow ?

if not, please screenshot of all logs after make reservaion of minio to see where's the error.

**Comment by hteibler** [comment]
![image](https://user-images.githubusercontent.com/24313736/82235409-f53c3680-9932-11ea-8858-cbb937dfca6d.png)
![image](https://user-images.githubusercontent.com/24313736/82235464-084f0680-9933-11ea-88d5-c339302b3af4.png)
![image](https://user-images.githubusercontent.com/24313736/82235529-17ce4f80-9933-11ea-9ecd-1ada912e9f94.png)
![image](https://user-images.githubusercontent.com/24313736/82235565-24eb3e80-9933-11ea-8452-eb8db5021fa8.png)
![image](https://user-images.githubusercontent.com/24313736/82235589-2fa5d380-9933-11ea-9302-16a8bb1f4e67.png)

**Comment by hteibler** [comment]
an export would be great!

**Comment by rkhamis** [comment]
@hteibler please try again and if you hit an issue, attach the alerts and reservation number. indeed, an export button would make life easier, will create a FR

**Comment by hteibler** [comment]
now it was working...
what was the problem?

**Comment by rkhamis** [comment]
we didn't do anything

**Comment by Pishoy** [comment]
working with me 
```
Please make sure of the entered values before starting deployment
chatflow 	minio
Solution name 	tests3
Disk type 	HDD
Access key 	test105
Secret 	secret12345
CPU 	1
Memory 	1024
Locations 	6
Locations allowed to fail 	2
ZDB number 	8
Solution expiration 	17h 23m 56s
IP Address 	10.127.4.3
```
