### ISSUE TITLE
Flist deploy uses hru instead of mru

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/jumpscaleX_threebot#709]
My node has 0 HRU and 2500 SRU, when trying to make a reservation in the chatflow I cannot choose which of both I would like to have. It automatically tries to select HRU and then the deployment fails.

https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/your_flist.py#L100

**Comment by AhmedHanafy725** [comment]
**Environment:** testnet
**Branch:** development
**Commit:** a9aca99fb37d0d9e866731d9f3dca06f98cb96b8
**Reservation ID:** 460896

Now it is not blocking on farm selection, but after the deployment, I got this error

![image](https://user-images.githubusercontent.com/41957921/82893886-0815c300-9f52-11ea-901a-f0796a1d6b76.png)

**Comment by grimpy** [comment]
@AhmedHanafy725 the above error is actually cause by an issue we have on tesnet atm see: https://github.com/threefoldtech/zos/issues/803.

Please revist this when the above is fixed

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** rc_10.6
**libs:** https://github.com/threefoldtech/jumpscaleX_libs/commit/ded1bcc2af60e7ff226d642eb21568a49d339007
**threebot:** a9aca99fb37d0d9e866731d9f3dca06f98cb96b8

I am already have a container on this node, and it is using MRU and 0 HRU

![image](https://user-images.githubusercontent.com/41957921/83139341-7f7f5a00-a0ec-11ea-8d51-bccdc65a0270.png)
