### ISSUE TITLE
Improve error message to be more specific when not enough resources are found

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/jumpscaleX_threebot#711]
chat says
The following farms don't have enough resources for for for zdb: GreenEdge-Vienna1. Please reselect farms to check for resources or leave it empty

but there are 9 nodes with lots of resources....

**Comment by zaibon** [comment]
I'm suspecting the problems come from the fact that most of the nodes from this farm are marked as free to use and the network you selected has not been payed with freeTFT.

The reason why you cannot mix both currency in a single reservation is explained at https://sdk.threefold.io/#/explore_nodes?id=free-to-use but we know this is quite annoying so there is also an issue in progress to try to solve that: https://github.com/threefoldtech/tfexplorer/issues/50

@grimpy does my assumption would produce this error ?
I think we could be a bit more explicit about what resource is missing or if the currency selected is not applicable.

**Comment by grimpy** [comment]
@zaibon all what you said is within the realm of possibilities :)

**Comment by grimpy** [comment]
So for now as the title of this issue says all we can do is be a bit more verbose why we couldnt find resources

**Comment by BolaNasr** [comment]
add improve error message to be more specific when not enough resources are found
https://github.com/threefoldtech/jumpscaleX_libs/commit/9cda5149a3f46f1caad8d8b03284c34ddad13b2f

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
