### ISSUE TITLE
expose solution doesn't have form_info in its metadata

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_threebot#716]
### Environment 
explorer: [testnet](https://explorer.testnet.grid.tf/)
Branch: development
Commit: a71e86a30576ee7ecbe5538420d4f901451facb6
libs commit: https://github.com/threefoldtech/jumpscaleX_libs/commit/284806382d39619dfc85bf5689771fb39f50c1ba
reservation id: 460602

### Steps
1- Using `chatflows` to deploy `expose solution` and finished the wizard with success deployment
2- Close `threebot` server
3- Start `threebot` server again
4- Go to threebot dashboard

### Result
![image](https://user-images.githubusercontent.com/41957921/82440796-33556980-9a9d-11ea-9c2c-d5707c78e084.png)

### Problem
The `metadata` of the expose solution reservations don't have `form_info`, so it will crash in this [line](https://github.com/threefoldtech/jumpscaleX_libs/blob/development/JumpscaleLibs/sal/reservation_chatflow/reservation_chatflow.py#L788)

metadata after decryption 
```python
{'Solution name': 'zeroci'}
```

**Comment by AhmedHanafy725** [comment]
For expose solution in case of custom domain, it fail to load the reservation.

![image](https://user-images.githubusercontent.com/41957921/82567093-332c9b00-9b7d-11ea-8748-c6d3f562e786.png)

**Comment by grimpy** [comment]
thx fixed in https://github.com/threefoldtech/jumpscaleX_libs/commit/38e4ff7b2a67038e0958fc4f48df492af06244c3 for exposure with custom domain

**Comment by AhmedHanafy725** [comment]
**Verified**
Branch: development
threebot: ff742f685921038c591234977fc191146e465fed
libs: https://github.com/threefoldtech/jumpscaleX_libs/commit/38e4ff7b2a67038e0958fc4f48df492af06244c3

Object now is loaded on bcdb

![image](https://user-images.githubusercontent.com/41957921/82570221-94ef0400-9b81-11ea-8de5-7379ec4d7358.png)

And chatflows is working now

![image](https://user-images.githubusercontent.com/41957921/82570325-b7811d00-9b81-11ea-9951-4d1a6a06cd7e.png)
