### ISSUE TITLE
flist used for ubuntu solution should not install openssh at startup

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#719]
It seems the startup script of the flist used for the ubuntu soltion (https://hub.grid.tf/tf-bootable/ubuntu:18.04-r1.flist)  is 
```shell
#!/bin/sh

apt-get update
mkdir ~/.ssh
mkdir -p /var/run/sshd
chmod 700 ~/.ssh
touch ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
echo $pub_key >> ~/.ssh/authorized_keys
apt-get install -y openssh-server
chmod 600 /etc/ssh/ssh_host_*
exec /usr/sbin/sshd -D
```

There is really no reason to install openssh-server every time a container start. Just include it into the flist. The chmod calls can also be done when you build the flist. SO the enrtrypoint of this flist could just be
```shell
#!/bin/sh

apt-get update
mkdir ~/.ssh
echo $pub_key >> ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
exec /usr/sbin/sshd -D
```

**Comment by BolaNasr** [comment]
ubuntu 18.04 -> https://hub.grid.tf/bola.3bot/3bot-ubuntu-18.04.flist
ubuntu 19.10 -> https://hub.grid.tf/bola.3bot/3bot-ubuntu-19.10.flist
ubuntu 20.04 -> https://hub.grid.tf/bola.3bot/3bot-ubuntu-20.04.flist

we need to move those flist to official tf-bootable

and i wil add more check in ubuntu chatflow to choose ubuntu version ( 19.10 and 20.04)

**Comment by AhmedHanafy725** [comment]
**Verified**

+ ubuntu 18.04

![image](https://user-images.githubusercontent.com/41957921/83628447-c364da00-a598-11ea-9bf0-9ac3c0e3cb8c.png)


+ ubuntu 19.10

![image](https://user-images.githubusercontent.com/41957921/83628400-adefb000-a598-11ea-885d-6e017b138f82.png)


+ ubuntu 20.04

![image](https://user-images.githubusercontent.com/41957921/83628677-2ce4e880-a599-11ea-92c1-22a2ba814821.png)
