### ISSUE TITLE
GE: Can't add farm administrators in SDK

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/jumpscaleX_threebot#720]
I tried to add Guido Neumann as an administrator on our farms. However, there does not to be a "submit" button, and hitting enter doesn't do anything.

![Screenshot 2020-05-22 at 15 49 09](https://user-images.githubusercontent.com/1249806/82674566-c9c38f80-9c43-11ea-861c-e3ed6ab4c9c9.png)

**Comment by grimpy** [comment]
Seems you are trying to fill his name in the filter field, at the top right there is a button add new administrator which would show a popup to add the new administrator

**Comment by joefoxton** [comment]
Nothing happens when you click it

**Comment by dmahmouali** [comment]
fixed on commit : https://github.com/threefoldtech/jumpscaleX_threebot/commit/a9aca99fb37d0d9e866731d9f3dca06f98cb96b8

**Comment by joefoxton** [comment]
Is there a way for me to get a hot fix for this? Where can I run a git pull?

**Comment by rkhamis** [comment]
@joefoxton it's ported to master. please update jumpscalex_threebot repo :)

**Comment by joefoxton** [comment]
Did a git pull in jumpscalex_threebot  and restarted the SDK… same result, I’m afraid!

**Comment by rkhamis** [comment]
pushed again. @joefoxton please let me know if it's not working

**Comment by joefoxton** [comment]
Confirmed - it works!
