### ISSUE TITLE
Update chat flow with new container root disk type and size feature

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#722]
In 0-OS v0.3.2 a new feature allows to configure the size of type of the root filesystem disk of a container: https://github.com/threefoldtech/zos/issues/793

We could update the chat flow to allow to choose those new configuration

**Comment by AhmedHanafy725** [comment]
After deploying a container using ubuntu or your flist chatflows and opening the deployment details, rootfs type and size is not there.

![image](https://user-images.githubusercontent.com/41957921/83147951-a0e64300-a0f8-11ea-95e2-1f87e10876f3.png)

**Comment by Pishoy** [comment]
verified
- create container with 1G rootfs 
```
chatflow 	ubuntu
Solution name 	ububtu
Version 	ubuntu-18.04
CPU 	1
Memory 	1024
Root filesystem Type 	HDD
Root filesystem Size 	1024
``` 
![image](https://user-images.githubusercontent.com/21987477/83420654-39493400-a427-11ea-9d31-63f73e329765.png)
