### ISSUE TITLE
Import wallet doesn't have cancel button

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/jumpscaleX_threebot#724]
Import wallet doesn't have a cancel button + Esc functionality 
![image](https://user-images.githubusercontent.com/36021484/82894250-91c59080-9f52-11ea-8807-6ebb22436209.png)

**Comment by dmahmouali** [comment]
Added on commit : https://github.com/threefoldtech/jumpscaleX_threebot/commit/68c932db80b76cfca33de3051845d7658811399b

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
