### ISSUE TITLE
Issue installing 3bot on windows

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/jumpscaleX_threebot#729]
- When do command 
` threebot start`

`Error in executing docker run --name=3bot --hostname=3bot -d -p 7000:80 -p 5000:8888 -p 4000:443 -p 9001:9001/udp -p 9000:22 --device=/dev/net/tun --cap-add=NET_ADMIN --cap-add=SYS_ADMIN --cap-add=DAC_OVERRIDE --cap-add=DAC_READ_SEARCH -v C:\Users\Tom Van den Keybus\sandbox\myhost:/sandbox/myhost threefoldtech/3bot2 /sbin/my_init: Traceback:
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.`

Windows 10 Pro 64 bit
 3sdk_v10.5.3_windows
docker desktop

**Comment by grimpy** [comment]
Looks like a spacing issue in the path (cause of the username) needs better escaping in the code

**Comment by waleedhammam** [comment]
Bin available at latest 10.6rc1 release here https://github.com/threefoldtech/jumpscaleX_core/releases/tag/v10.6rc1

**Comment by AhmedHanafy725** [comment]
I was able to reproduce the error with 10.5.3 binary.

![image](https://user-images.githubusercontent.com/41957921/83253054-9c7b6200-a1ac-11ea-8e2d-beebe1b66b63.png)


And it works fine with the latest binary 10.6rc1

![image](https://user-images.githubusercontent.com/41957921/83253020-8b325580-a1ac-11ea-8d12-816ccae17997.png)

**Verified**
