### ISSUE TITLE
no more deployed solution shown in admin panel after update to 10.6-rc1

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#730]

**Comment by grimpy** [comment]
Could you be a bit more clear with what you mean?

in 10.6 all solutions are shown in the menu itself

![image](https://user-images.githubusercontent.com/143869/83156273-7c8f6400-a102-11ea-995b-f233b44cf485.png)
![image](https://user-images.githubusercontent.com/143869/83156298-84e79f00-a102-11ea-8d99-7900d47128dc.png)

**Comment by zaibon** [comment]
Well then there is a bug in the loading of these solution cause all show nothing to me. While when I list reservation from the API I do find some that are not expired yet.

**Comment by grimpy** [comment]
> Well then there is a bug in the loading of these solution cause all show nothing to me. While when I list reservation from the API I do find some that are not expired yet.

could you check your browser repsonse and your alerts to see if any errors are happening?

**Comment by zaibon** [comment]
alert dump : https://gist.github.com/zaibon/995668b0b66b0a147b0a62e3011be91b

**Comment by grimpy** [comment]
https://gist.github.com/zaibon/995668b0b66b0a147b0a62e3011be91b#file-gistfile1-txt-L89

i think this line is the culprit here

**Comment by zaibon** [comment]
Seems there is also an xhr request to `http://172.17.0.2/tfgrid_solutions/tfgrid_solutions/actors/tfgrid_solutions/solutions_list` which never finishes

**Comment by grimpy** [comment]
@zaibon can you verify / close this one as this is impossible to reproduce with the new code :)

**Comment by zaibon** [comment]
I just pulled development branch on all repos:
```
jumpscaleX_builders 1570b275d131771b3632a14a92d8a52398d32c42
jumpscaleX_core 9bc5b367ea32f9caa8778a87bcbe04fd3f2d1a63
jumpscaleX_libs 66438c14ab5eabdce6e02c37aedee3842c2a712d
jumpscaleX_libs_extra 905de16da9b8458070ca310b63d537f49a6e4941
jumpscaleX_threebot c4d435c8aafb1562b90fe55993e9841f5ca98c5b
jumpscaleX_weblibs db92a0e8a26fbdb73ff2c1f07b0730966fc015d3
```

Then did a `3sdk threebot restart`
I still don't see any deployed solution. While I
