### ISSUE TITLE
date show in the admin panel show follow the local time zone

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#731]
For example expiration date:
![2020-05-28_943x258_scrot](https://user-images.githubusercontent.com/303164/83155324-692fc900-a101-11ea-8f81-3e2721149922.png)
Seems the time is given in UTC which is very confusing. Or we show the local time or we show the time zone info but the user needs to know what he's looking at.

**Comment by ranatrk** [comment]
Changed the time to be based on the local time where the epoch from the reservation json is changed to the current date/time
![Screenshot from 2020-06-01 13-18-13](https://user-images.githubusercontent.com/17128393/83405248-63d9c380-a40c-11ea-92a8-4116aabe5c71.png)

**Comment by AhmedHanafy725** [comment]
**Verified**

**Branch:** development
**Commit:** 1701a86231412b9e9ea11171c84c00a44b251860

Local time is shown.

![image](https://user-images.githubusercontent.com/41957921/83626226-674c8680-a595-11ea-95ed-3180434912fd.png)
