### ISSUE TITLE
can not start threebot server using a 3bot account in mainnet 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_threebot#734]
steps :
1 - we asks 3bot guy to delete his account (ThreeFoldFarmer.3bot) and we creates a new 3bot account again with the same name as we have not the phrase words

2 - @zaibon reset and fix public key of new user ThreeFoldFarmer.3bot
https://explorer.grid.tf/explorer/users/94
https://login.threefold.me/api/users/ThreeFoldFarmer.3bot

3 - when try to install jsx we got error while installing 
![image](https://user-images.githubusercontent.com/21987477/83278093-52f23d80-a1d3-11ea-8ca6-4a45b1241edf.png)

4 - try to reconfigure account again 
`j.me.configure()`
![image](https://user-images.githubusercontent.com/21987477/83278137-643b4a00-a1d3-11ea-9876-5216b437d500.png)

-  sdk version 
3sdk_v10.6rc1_windows.exe

**Comment by grimpy** [comment]
@zaibon I remember in the past we made all usernames in the explorer lowercase, seems we forgot todo this for mainnet?

**Comment by Pishoy** [comment]
@grimpy fixed public key of the new user of lowercase https://explorer.grid.tf/explorer/users/180
but we still stuck as we got an error while user trying to update his farm as below 
![image](https://user-images.githubusercontent.com/21987477/83351929-65da4e80-a348-11ea-8b42-d75f4085c6c6.png)

we are waiting for @zaibon on that

**Comment by zaibon** [comment]
@grimpy what exactly what the problem ? Cause the public key  were correct so why did the installation complained and refuse to let it continue ? I don't see how a the case of the username would impact that ?

Regarding the signature verification error. There is nothing more I can do either. The signature sent to the server is wrong. So it means the code that does this request is not using the right key pair to sign the request.

**Comment by grimpy** [comment]
@zaibon the pubkey in explorer was not the same as in the threefold 3bot app.
For this signature verfication I assume it checks the pubkey of the threebot_user of the farm?
https://explorer.grid.tf/explorer/farms/161434

so in this case it should be using user 180 it's key to verify the signature?

**Comment by zaibon** [comment]
> @zaibon the pubkey in explorer was not the same as in the threefold 3bot app.

This is pretty much impossible cause we verify 2 twice by 2 different person. My guess is they sent me the wrong user in 3bot connect.

> so in this case it should be using user 180 it's key to verify the signature?

from what I can tell yes.

**Comment by Pishoy** [comment]
adding wallet to farm fixed but we still getting error of authorized when login to SDK and try to change in farm settings

As per @zaibon 
```
that means the wrong identity is used by the farm mangement actors I guess..
```

**Comment by Pishoy** [comment]
closing as it wass solved
