### ISSUE TITLE
chatflow: generic flist does not set the env correctly in the reservation

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/jumpscaleX_threebot#735]
I was trying to install `https://hub.grid.tf/tf-official-apps/prometheus:latest.flist` flist. It accepts `SSH_KEY` to set the authorized_key so we can ssh into the container. 

`SSH_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQJpNHC/AWNRAuDkqAZH6Y6pJsafTT9kslY486v0Bt2PfVK12mGdzLblzneqKdL/c75XUC4ujxR/7RXdGV+bicMoFJDFJeXCGyglzq0ep86TSMnw8/17uLWHunxzHs3xMSAXVZnCHeOB9EMvkInn0SS6Bp6SfkVDcx1kVFoY4+UXI4+/OQDkzbP6BB1QUcexeyqknAhFFaB6xCoMajRSgwoGTbEmc2dIc3jT5FJyW4WxEUhbI3cFd/LmVwVp5ttEVoW7sWUEHcG6CFg6NUVOkcpQc0X7YuBJ7oNgZFSKyUiumQO54ABtmzSOovUal0/GCNblv9nka8sfyod5DAYofbPGNrqKHnDkJRk9dQeB2xuRNK2Uiyz/iw/f13qc7WXdPeYHUhz3HSsn6EX0+wWK+0Sbk5kdVd+Hl8T3Ra7O1e7p5JuAUjcYtrBdw1KE3JxXjnpH33ORKj9Y/obyVcbjvIrMTf0JjGoG76DQFS+j5dRlfVcf0Ldb194PsqYCbwAUs= azmy@thanos`

This printed on the overview page, but did not set correctly on the reservation `https://explorer.devnet.grid.tf/explorer/reservations/541`

I checked the code and there was already a bug (you do `item.split("=")` not split `item.split("=", 1)` but fixing this didn't actually fix the issue.

Note: I think also all `Env` vars should be set in `secret_environment` (encrypte), so please make sure this is the case.

**Comment by Pishoy** [comment]
verified with gitea flist
