### ISSUE TITLE
minio-chatflow: Support Master/Slave setup

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/jumpscaleX_threebot#737]
- First of all make sure to use this flist `https://hub.grid.tf/tf-official-apps/minio:latest.flist.md`
- The chat flow must give you option to choose between a `Single Setup`, or `Master/Slave` setup.

# Single setup
This is exactly the same flow as the current chatflow

# Master/Slave setup
- Install an extra zdb instance (called `tlog`) this instance will have an address as `namespace:password@ip:port` will call it `tlog-access` in the reset of this issue
- The master minio instance have the same exact config as the current one PLUS
  - Will take a new ENV var called `TLOG` as `TLOG=<tlog-access>`
- A new (extra) minio instance will be installed, it should have the same exact config as the master instance (but installs on a different node), plus:
  - It will have exact same setup as the master (without the TLOG env), BUT will have another ENV var `MASTER` as `MASTER=<tlog-access>`

**Comment by AhmedHanafy725** [comment]
**Verified**

**Branch:** development
**Commit:** 1701a86231412b9e9ea11171c84c00a44b251860

I have tried both setups:

1- Single:
+ Only one minio is deployed.

2- Master/Salve:
+ Two minio are deployed.
+ Master can upload/download files and create buckets.
+ Slave only can download files.
