### ISSUE TITLE
gedis: needs a way to make big response scalable

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#74]
In the [directory actor](https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/threefold/tfgrid_directory) there are some methods that can return a pretty big [list of objects](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threefold/tfgrid_directory/actors/nodes.py#L45).

Currently the dataset of the nodes has +- 600 entries. When calling the list method, the 600 object are returned in one big blob. This operation takes more then **30 seconds** to finish.
This is not something we can live with specially when this method will be called a lot from the cockpit.

One easy solution is pagination. But that would be nice we could have something re-usable throughout any gedis actor, and I don't really know how we could design it like that with the current way of working of gedis.

ps: it might be worth it to benchmark the list method to identity exactly where the 30 seconds comes from. Maybe time is actually not spent during the transfer of the data...

**Comment by xmonader** [comment]
That's related to the response body size right? I remember the return proofs from capacity were so big?

**Comment by zaibon** [comment]
Well in gedis there is only "body". Since it is using RESP there is no header or anything this is just a big blob of data that is sent back to the client.

**Comment by andrewayoub** [comment]
- added `limit` and `offset` params to find method in bcdb model
- for usage example see the test here https://github.com/threefoldtech/jumpscaleX_core/blob/9fb84624624e07b5b4f039ed9c8228097d5e8655/JumpscaleCore/data/bcdb/tests/21_query_limit.py
- also added an example for an actor to list data with pagination here https://github.com/threefoldtech/jumpscaleX_threebot/pull/354/files

code:
https://github.com/threefoldtech/jumpscaleX_core/pull/475
https://github.com/threefoldtech/jumpscaleX_threebot/pull/354

**Comment by zaibon** [comment]
At the BCDB level this seems fine as it is.
Now on gedis level, the only solution when I want to paginate response is to add these 2 argument to each actor methods then ?

**Comment by xmonader** [comment]
> At the BCDB level this seems fine as it is.
> Now on gedis level, the only solution when I want to paginate response is to add these 2 argument to each actor methods then ?

Yup :)

**Comment by hossnys** [comment]
verified on branch development:

![Screenshot from 2020-02-18 12-37-47](https://user-images.githubusercontent.com/26298009/74728388-53318300-524b-11ea-9f29-ae3c4e09ae88.png)
