### ISSUE TITLE
Pressing wallets manager multiple times increases the wallets

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_threebot#741]
![image](https://user-images.githubusercontent.com/143869/83398585-e9a34200-a3ff-11ea-8e20-553c857e3ea9.png)
seems the grid is not cleared before adding the response from the actor

**Comment by AhmedHanafy725** [comment]
**Verified**

**Branch**: development
**Commit:** 1701a86231412b9e9ea11171c84c00a44b251860
