### ISSUE TITLE
network-chatflow: Please give option to choose the farm name to be used for your network

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/jumpscaleX_threebot#748]
Currently it choose the nodes randomly and sometimes the access point ends in a node that does not have a routable IP.

**Comment by BolaNasr** [comment]
add this feature in chatflow and libs:
Chatflow: https://github.com/threefoldtech/jumpscaleX_threebot/commit/0268075594310448ac1808aa12dc28ce313b1caf

libs: https://github.com/threefoldtech/jumpscaleX_libs/commit/868c8909bd13e3f8740844268f14aa48910a428c

**Comment by Dina-Abd-Elrahman** [comment]
- verified
