### ISSUE TITLE
Delete a reservation through the admin UI

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/jumpscaleX_threebot#749]
The solutions deployed through the admin panel can only be viewed under the tab `solutions`. There should be an option/button to be able to delete(from bcdb) the solution and cancel that reservation.

The delete endpoint is already implemented in the service https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/zerobot/admin/frontend_src/sources/services/deployedSolutions.js#L22 , it just needs to be used in the solutions views

**Comment by BolaNasr** [comment]
Commit : https://github.com/threefoldtech/jumpscaleX_threebot/commit/44c0cd1ed882a6d424087f38174bbe67cd8ffe04
![image](https://user-images.githubusercontent.com/10259267/84016933-46fa3e80-a97e-11ea-9e37-65801a6cb703.png)

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development
**Commit:** b0859730f1710c53a3faa8f6a47666706d27acdc

Tried for Ubuntu reservation.
Delete button

![image](https://user-images.githubusercontent.com/41957921/84258696-a8094a00-ab17-11ea-8f56-c37044738671.png)

Confirmation 

![image](https://user-images.githubusercontent.com/41957921/84258753-bce5dd80-ab17-11ea-9fec-ed3f7bf53172.png)

After deletion 
![image](https://user-images.githubusercontent.com/41957921/84258836-e4d54100-ab17-11ea-8e1f-18ee175e51e1.png)
