### ISSUE TITLE
Wallets created but NOT visible under the Wallet Manager

### ISSUE THREAD

**Issue by abdulgig** [threefoldtech/jumpscaleX_threebot#751]
We had this issue with a few other people also. They could create wallets inside the Wallet Manager but these wallets were not visible in the web interface. The wallets are there because if you try to create the wallet with the same name, it throws an error that this wallet name already exists. Apparently, seems to be an issue with GUI

We have another user who has the same issue. He has shared the following details with us,

3bot Name = flowmotion.3bot
Browser = Chrome

![image](https://user-images.githubusercontent.com/25789764/83898191-aa5e5380-a767-11ea-9d4d-b29e87ea4f7d.png)

From the browser debugger,

![image](https://user-images.githubusercontent.com/25789764/83898350-da0d5b80-a767-11ea-8184-01f22b42d4a6.png)

**Comment by grimpy** [comment]
@abdulgig strange to see a 400 on this request. Could you include an export of the alerts?

**Comment by abdulgig** [comment]
@grimpy , I ll check with the customer 

Thanks,

**Comment by grimpy** [comment]
Found the problem here, it's related to a wallet that has been created with an invalid secret.
When trying to load all wallets it's failing to load the wallet initialized with wrong secret.

**Comment by Pishoy** [comment]
verified
 - importing with incorrect wallet secret failing 
- cretae wallet option has been disabled
