### ISSUE TITLE
document an example vue package

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#76]
we should document the following for vue users

- creating vue app (using vue cli)
- creating routes
- setting the base url
- deployment of the app on the threebot server (location based and domain based) and setting the base url during the deployment

**Comment by waleedhammam** [comment]
Current state: 
- created a vuejs package with the routes.
base url changes according to environment if it's development will serve on "/example" else if it's on a domain will be served at "/"

- Now adding  more actors and models to verify it's working as expected

working at branch : https://github.com/threefoldtech/jumpscaleX_threebot/tree/development_vuejs_package

**Comment by Dina-Abd-Elrahman** [comment]
after merge this is the new documentation we should follow

https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/examples/vuejs/README.md

https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/examples/vuejs/newproject/README.md
