### ISSUE TITLE
[Security] Threebot passphrases are cleartext in the Alertsection and in the Alert-Export

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/jumpscaleX_threebot#760]
The Wallet Passphrases - maybe also others - are shown in cleartext in the Alertsection of the threeboot. Also if you export the Alerts as json they are cleartext... Thats a huge security problem.

![image](https://user-images.githubusercontent.com/24993288/84178766-43051400-aa85-11ea-8d06-c1f36a1100ff.png)

```
--TRACEBACK------------------ {DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/Decorators.py in wrapper_action 67 res = func(self, **kwargs) {DIR_BASE}/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/admin/actors/wallet.py in get_wallets 61 wallets = j.clients.stellar.find() {DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in find 263 item = self.get(id=id, reload=reload) {DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in get 116 jsconfig = self._get(name=name, id=id, die=needexist, reload=reload) {DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in _get 171 return self._create(name, obj) {DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in _create 96 jsconfig = jsconfig_klass(parent=self, jsxobject=jsxobject, **kwargs_to_class) {DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py in __init__ 66 self._init(**kwargs) {DIR_BASE}/lib/jumpscale/JumpscaleLibs/clients/stellar/StellarClient.py in _init 88 kp = Keypair.from_secret(self.secret) /usr/local/lib/python3.7/dist-packages/stellar_sdk/keypair.py in from_secret 63 raw_secret = StrKey.decode_ed25519_secret_seed(secret) /usr/local/lib/python3.7/dist-packages/stellar_sdk/strkey.py in decode_ed25519_secret_seed 92 "Invalid Ed25519 Secret Seed: {}".format(data)
-----------------------------
```

**json "Alert Export" example:**

`{"alert_id":5,"identifier":"684314bb96b7ccd1b57b902f63512aeb","alert_type":2,"level":50,"message":"\u001b[1;31mEXCEPTION: \n    Ed25519SecretSeedInvalidError('**Invalid Ed25519 Secret Seed: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')**\u001b[0;0m","message_pub":"","cat":"exception","count":3,"status":3,"time_first":1589563322,"time_last":1589999215,"support_trace":[],"events":[{"threebot_name":"flowmotion.3bot","process_ids":[1025,8015],"code_path":"/usr/local/lib/python3.7/dist-packages/stellar_sdk/strkey.py","code_line":"","code_line_nr":92,"count":3,"time_first":1589500800,"time_last":1589932800,"trace":"","data":"null"}],"tracebacks":[{"process_id":1025,"threebot_name":"flowmotion.3bot","formatted":"\n\u001b[1;31m--TRACEBACK------------------\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/Decorators.py\u001b[0;0m in \u001b[1;34mwrapper_action\u001b[0;0m\n    \u001b[0;32m67\u001b[0;0m    res = func(\u001b[36mself\u001b[39;49;00m, **kwargs)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/admin/actors/wallet.py\u001b[0;0m in \u001b[1;34mimport_wallet\u001b[0;0m\n    \u001b[0;32m77\u001b[0;0m    wallet = j.clients.stellar.new(name=name, secret=secret, network=network)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py\u001b[0;0m in \u001b[1;34mnew\u001b[0;0m\n    \u001b[0;32m27\u001b[0;0m    jsconfig = \u001b[36mself\u001b[39;49;00m._create(name=name, jsxobject=jsxobject, **kwargs)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py\u001b[0;0m in \u001b[1;34m_create\u001b[0;0m\n    \u001b[0;32m96\u001b[0;0m    jsconfig = jsconfig_klass(parent=\u001b[36mself\u001b[39;49;00m, jsxobject=jsxobject, **kwargs_to_class)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py\u001b[0;0m in \u001b[1;34m__init__\u001b[0;0m\n    \u001b[0;32m66\u001b[0;0m    \u001b[36mself\u001b[39;49;00m._init(**kwargs)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/JumpscaleLibs/clients/stellar/StellarClient.py\u001b[0;0m in \u001b[1;34m_init\u001b[0;0m\n    \u001b[0;32m87\u001b[0;0m    kp = Keypair.from_secret(\u001b[36mself\u001b[39;49;00m.secret)\u001b[0;0m\n\u001b[0;32m/usr/local/lib/python3.7/dist-packages/stellar_sdk/keypair.py\u001b[0;0m in \u001b[1;34mfrom_secret\u001b[0;0m\n    \u001b[0;32m63\u001b[0;0m    raw_secret = StrKey.decode_ed25519_secret_seed(secret)\u001b[0;0m\n\u001b[0;32m/usr/local/lib/python3.7/dist-packages/stellar_sdk/strkey.py\u001b[0;0m in \u001b[1;34mdecode_ed25519_secret_seed\u001b[0;0m\n    \u001b[0;32m92\u001b[0;0m    \u001b[33m\"\u001b[39;49;00m\u001b[33mInvalid Ed25519 Secret Seed: \u001b[39;49;00m\u001b[33m{}\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m.format(data)\u001b[0;0m\n\u001b[1;31m-----------------------------\n\u001b[0;0m"},{"process_id":8015,"threebot_name":"flowmotion.3bot","formatted":"\n\u001b[1;31m--TRACEBACK------------------\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/Decorators.py\u001b[0;0m in \u001b[1;34mwrapper_action\u001b[0;0m\n    \u001b[0;32m67\u001b[0;0m    res = func(\u001b[36mself\u001b[39;49;00m, **kwargs)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/admin/actors/wallet.py\u001b[0;0m in \u001b[1;34mimport_wallet\u001b[0;0m\n    \u001b[0;32m77\u001b[0;0m    wallet = j.clients.stellar.new(name=name, secret=secret, network=network)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py\u001b[0;0m in \u001b[1;34mnew\u001b[0;0m\n    \u001b[0;32m27\u001b[0;0m    jsconfig = \u001b[36mself\u001b[39;49;00m._create(name=name, jsxobject=jsxobject, **kwargs)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py\u001b[0;0m in \u001b[1;34m_create\u001b[0;0m\n    \u001b[0;32m96\u001b[0;0m    jsconfig = jsconfig_klass(parent=\u001b[36mself\u001b[39;49;00m, jsxobject=jsxobject, **kwargs_to_class)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py\u001b[0;0m in \u001b[1;34m__init__\u001b[0;0m\n    \u001b[0;32m66\u001b[0;0m    \u001b[36mself\u001b[39;49;00m._init(**kwargs)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/JumpscaleLibs/clients/stellar/StellarClient.py\u001b[0;0m in \u001b[1;34m_init\u001b[0;0m\n    \u001b[0;32m87\u001b[0;0m    kp = Keypair.from_secret(\u001b[36mself\u001b[39;49;00m.secret)\u001b[0;0m\n\u001b[0;32m/usr/local/lib/python3.7/dist-packages/stellar_sdk/keypair.py\u001b[0;0m in \u001b[1;34mfrom_secret\u001b[0;0m\n    \u001b[0;32m63\u001b[0;0m    raw_secret = StrKey.decode_ed25519_secret_seed(secret)\u001b[0;0m\n\u001b[0;32m/usr/local/lib/python3.7/dist-packages/stellar_sdk/strkey.py\u001b[0;0m in \u001b[1;34mdecode_ed25519_secret_seed\u001b[0;0m\n    \u001b[0;32m92\u001b[0;0m    \u001b[33m\"\u001b[39;49;00m\u001b[33mInvalid Ed25519 Secret Seed: \u001b[39;49;00m\u001b[33m{}\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m.format(data)\u001b[0;0m\n\u001b[1;31m-----------------------------\n\u001b[0;0m"},{"process_id":8015,"threebot_name":"flowmotion.3bot","formatted":"\n\u001b[1;31m--TRACEBACK------------------\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/Decorators.py\u001b[0;0m in \u001b[1;34mwrapper_action\u001b[0;0m\n    \u001b[0;32m67\u001b[0;0m    res = func(\u001b[36mself\u001b[39;49;00m, **kwargs)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/admin/actors/wallet.py\u001b[0;0m in \u001b[1;34mimport_wallet\u001b[0;0m\n    \u001b[0;32m77\u001b[0;0m    wallet = j.clients.stellar.new(name=name, secret=secret, network=network)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py\u001b[0;0m in \u001b[1;34mnew\u001b[0;0m\n    \u001b[0;32m27\u001b[0;0m    jsconfig = \u001b[36mself\u001b[39;49;00m._create(name=name, jsxobject=jsxobject, **kwargs)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py\u001b[0;0m in \u001b[1;34m_create\u001b[0;0m\n    \u001b[0;32m96\u001b[0;0m    jsconfig = jsconfig_klass(parent=\u001b[36mself\u001b[39;49;00m, jsxobject=jsxobject, **kwargs_to_class)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py\u001b[0;0m in \u001b[1;34m__init__\u001b[0;0m\n    \u001b[0;32m66\u001b[0;0m    \u001b[36mself\u001b[39;49;00m._init(**kwargs)\u001b[0;0m\n\u001b[0;32m{DIR_BASE}/lib/jumpscale/JumpscaleLibs/clients/stellar/StellarClient.py\u001b[0;0m in \u001b[1;34m_init\u001b[0;0m\n    \u001b[0;32m87\u001b[0;0m    kp = Keypair.from_secret(\u001b[36mself\u001b[39;49;00m.secret)\u001b[0;0m\n\u001b[0;32m/usr/local/lib/python3.7/dist-packages/stellar_sdk/keypair.py\u001b[0;0m in \u001b[1;34mfrom_secret\u001b[0;0m\n    \u001b[0;32m63\u001b[0;0m    raw_secret = StrKey.decode_ed25519_secret_seed(secret)\u001b[0;0m\n\u001b[0;32m/usr/local/lib/python3.7/dist-packages/stellar_sdk/strkey.py\u001b[0;0m in \u001b[1;34mdecode_ed25519_secret_seed\u001b[0;0m\n    \u001b[0;32m92\u001b[0;0m    \u001b[33m\"\u001b[39;49;00m\u001b[33mInvalid Ed25519 Secret Seed: \u001b[39;49;00m\u001b[33m{}\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m.format(data)\u001b[0;0m\n\u001b[1;31m-----------------------------\n\u001b[0;0m"}],"logs":[{"threebot_name":"flowmotion.3bot","app_name":"bottle_server","latest_logid":251},{"threebot_name":"flowmotion.3bot","app_name":"bottle_server","latest_logid":469},{"threebot_name":"flowmotion.3bot","app_name":"bottle_server","latest_logid":474}],"appname":"bottle_server","id":1591721393904,"index":2},{"alert_id":6,"identifier":"77b69dc7922cc681e748a4866eff9369","alert_type":2,"level":50,"message":"\u001b[1;31mEXCEPTION: \n    Va`

**Comment by Pishoy** [comment]
verified 

![image](https://user-images.githubusercontent.com/21987477/84362347-63d88100-abcd-11ea-9828-6d5eadeca334.png)

jsx version 
```
root@3bot:/sandbox/code/github/threefoldtech/jumpscaleX_threebot# git log -1
commit e2f1119a1b083ba963af8a33689ebb0786a8f651 (grafted, HEAD -> development, origin/development, origin/HEAD)
Author: Christophe de Carvalho <christophe.dcpm@gmail.com>
Date:   Wed Jun 10 15:14:02 2020 +0200

    farm management: show node hostname

```
