### ISSUE TITLE
3SDK install on Ubuntu 20.04 throws error

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/jumpscaleX_threebot#762]
We have one customer/partner who recently tried to install the 3SDK on his Ubuntu 20.04 machine.

The installation did not go as simple in one go and he got the following error after ```threebot start``` : 

![image](https://user-images.githubusercontent.com/25789724/84256352-d6d9ed00-ab24-11ea-900d-50ba08d00098.png)

Ubuntu:  20.04
Docker:  19.03.11 ce
3SDK v10.6 

When he manually tried to start 3bot from container he gets this : 

![image](https://user-images.githubusercontent.com/25789724/84259106-04289a00-ab29-11ea-9a49-1168a1bb6777.png)

And from tmux : 
![image](https://user-images.githubusercontent.com/25789724/84259205-2ae6d080-ab29-11ea-802b-ab80615f1e8e.png)

![image](https://user-images.githubusercontent.com/25789724/84259221-34703880-ab29-11ea-8ddf-4caa729fcd6b.png)

**Comment by BolaNasr** [comment]
i tried it at ubuntu 20.04 and it works very good 
![image](https://user-images.githubusercontent.com/10259267/84590423-b10b5b80-ae36-11ea-8717-0a619da1c207.png)

![image](https://user-images.githubusercontent.com/10259267/84590452-0e9fa800-ae37-11ea-8eb2-c0979fd912b0.png)

**Comment by grimpy** [comment]
@siddiquagig can you ask the customer on which kind of 'machine' he is running this?
Please provide the output of `lscpu` seems some instruction in the cpu is missing

**Comment by siddiquagig** [comment]
Update from him , he is running directly on a machine ```HP workstation XW8600```

result of ```lscpu``` :
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   38 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       2
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           23
Model name:                      Intel(R) Xeon(R) CPU           X5450  @ 3.00GHz
Stepping:                        6
CPU MHz:                         2000.891
CPU max MHz:                     3000.0000
CPU min MHz:                     1998.0000
BogoMIPS:                        6000.57
Virtualization:                  VT-x
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        24 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX EPT disabled
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm con
                                 stant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 l
                                 ahf_lm pti tpr_shadow vnmi flexpriority dtherm
```

**Comment by grimpy** [comment]
Sorry to say for now we can not support this cpu
we use openresty in the current version which requires a cpu with sse 4.2 [see](https://github.com/openresty/openresty/issues/267#issuecomment-309296900)

According to the following this cpu out of 2007 does not support it [X5450](http://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%20X5450%20-%20EU80574KJ080NT%20-%20AT80574KJ080NT%20(BX80574X5450A).html)
