### ISSUE TITLE
chatflow: we should validate the flist url

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#763]
I did make a mistake in the flist url when trying to deploy a container. The reservation eventually failed but we could have validated the format of the flist upfront to avoid the mistake sooner.

![2020-06-10_2273x693_scrot](https://user-images.githubusercontent.com/303164/84267674-bb6fe180-ab26-11ea-926d-eff53e7d2124.png)

**Comment by BolaNasr** [comment]
Fixed: https://github.com/threefoldtech/jumpscaleX_threebot/commit/bb6b1e03372a07b73dac98e60bc3e8fe2de4fe34

**Comment by Pishoy** [comment]
verified
flist url with .md an having spaces before and after flist url

**Comment by BolaNasr** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/commit/48b9f9876e494526e2a9c1450805f77a203dd7d7

**Comment by Pishoy** [comment]
verified
