### ISSUE TITLE
container logs are not properly generated in reservation

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#767]
Seems the reservation is filled with weird object result instead of the actual value.

Extract from https://explorer.devnet.grid.tf/explorer/reservations/621
```json
"logs": [
{
"type": "<Jumpscale.servers.gedis.GedisChatBot.Result object at 0x7fef4e140e90>",
"data": {
"stdout": "redis://<Jumpscale.servers.gedis.GedisChatBot.Result object at 0x7fef4e140750>:<Jumpscale.servers.gedis.GedisChatBot.Result object at 0x7fef4ebcd5d0>/<Jumpscale.servers.gedis.GedisChatBot.Result object at 0x7fef4ebcdf50>-stdout",
"stderr": "redis://<Jumpscale.servers.gedis.GedisChatBot.Result object at 0x7fef4e140750>:<Jumpscale.servers.gedis.GedisChatBot.Result object at 0x7fef4ebcd5d0>/<Jumpscale.servers.gedis.GedisChatBot.Result object at 0x7fef4ebcdf50>-stderr"
}
}
```

**Comment by ranatrk** [comment]
Fix: https://github.com/threefoldtech/jumpscaleX_threebot/commit/118975c272912f3cfbdc9a73e75916701e1b3d67
Example reservation created (with dummy log host/port): https://explorer.testnet.grid.tf/explorer/reservations/461482

**Comment by Pishoy** [comment]
verifed 
https://explorer.testnet.grid.tf/explorer/reservations/461492
