### ISSUE TITLE
make sure our SPA packages use service workers correctly 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#77]
Make sure we use service workers, and we use it correctly 
https://serviceworke.rs

- [x]  alerta
- [x] myjobs
- [x]  pastebin

**Comment by serboctor** [comment]
The service workers seem to cache everything except the gedis api calls. I am still trying to figure out the problem and doing some research.

**Comment by serboctor** [comment]
Depends on this https://github.com/threefoldtech/jumpscaleX_threebot/issues/168

**Comment by serboctor** [comment]
service workers support in alerta fixed here https://github.com/threefoldtech/jumpscaleX_threebot/commit/523920b643b852df4c2273f548ca7a05534006b2

**Comment by serboctor** [comment]
service workers support in myjobs fixed here https://github.com/threefoldtech/jumpscaleX_threebot/commit/0f4bdedd95e3cd62f1288ce810d191440e4d5477

**Comment by serboctor** [comment]
service workers support in pastebin fixed here https://github.com/threefoldtech/jumpscaleX_threebot/commit/915cc90d2b4f791988122d96201e2daaff380e7d

**Comment by xmonader** [comment]
I removed blog from the service workers because we are facing more problems in its core functionality testing and will keep this issue from being verified

**Comment by Pishoy** [comment]
alerta,myjobs and  pastebin are verified
