### ISSUE TITLE
got Ciphertext failed verification error when enter incorrect passphrase

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_threebot#770]
steps:

1- I started my threebot server successfully with passphrase=x
2- stop container ` 3sdk container stop`
3- start container ` 3sdk container start`
4 - login to container `3sdk container shell` and starting 3bot server with incorrect passpharse=y , give me below error 
![image](https://user-images.githubusercontent.com/21987477/84766596-5eb27200-afd1-11ea-878b-916f95636954.png)
5 - tried to start wth correct passphrase=x not working and give me same error
![image](https://user-images.githubusercontent.com/21987477/84766682-886b9900-afd1-11ea-877e-3e2329ae97ed.png)

- as i think, two-issues here: 
1 - step 4 : why it ask me to pass the passpharse twice while i should use the old one ( no need to verify it twice )
2 - step 5 should ask me for correct passphrase=x , to fix that manually  we need to kill redis in container

**Comment by rkhamis** [comment]
This is not a bug. this is indeed the intended behavior

however, indeed, instead of giving an error, it should allow to retry entering the password

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
