### ISSUE TITLE
GE: no network found in chatbot

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/jumpscaleX_threebot#775]
created a network in chatbot, OK:  ->9975
then trying ubuntu or minio
but no network to select
![image](https://user-images.githubusercontent.com/24313736/84779725-071e0180-afe5-11ea-999d-ad754fe7c6be.png)

**Comment by grimpy** [comment]
To reproduce this we first need to make more than 5 networks.

**Comment by Pishoy** [comment]
verified 6 network created successfully and listed whe trying adding an ubuntu container 

- js version 

```root@3bot:/sandbox/code/github/threefoldtech/jumpscaleX_threebot# git log -1
commit 6121737a21f9af5549815c7fbfb60e3f200082a3 (HEAD -> development, origin/development, origin/HEAD)
Author: Christophe de Carvalho <christophe.dcpm@gmail.com>
Date:   Wed Jun 10 16:12:30 2020 +0200

    farm management: show CPR in node info


```
