### ISSUE TITLE
threebot packages inconsistencies 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#78]
- some don't even have package.py file (ffconnect)
- the factories base classes
- some register actors, models dirs 
- manually, get_port_from should be always 443
- filemanager shouldn't use ports website

**Comment by jdelrue** [comment]
Also: please use models in and outs instead of strings

https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threebot/mail/actors/mail.md

**Comment by xmonader** [comment]
closed in favor for https://github.com/threefoldtech/home/issues/377
