### ISSUE TITLE
 ValueError while creating container with chatflow soultions 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_threebot#784]
- trying to create a container with chatflow , I got an error in payment step as below

![image](https://user-images.githubusercontent.com/21987477/86099262-903e3980-bab7-11ea-9c0f-676f66351c1c.png)

- jsx threebot logs 

![image](https://user-images.githubusercontent.com/21987477/86099318-a0eeaf80-bab7-11ea-868c-21042d294301.png)

 -  on testnet 

testnet wallet has tft , address GDITTQ6FXRYEF565WOMCP2VBQEE5YIHWIVF7CAJVVUJY3OY75TGPMLSB

**Comment by grimpy** [comment]
Seems bug made in https://github.com/threefoldtech/jumpscaleX_libs/pull/238
Will rectify asap
