### ISSUE TITLE
Not able to access flist through ipv6

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/jumpscaleX_threebot#788]
I've tried to deploy a flist through the 3sdk. Accessing it through ipv4 works fine. However, ipv6 is not working. I also added the public ipv6=true flag but I'm still not able to access the flist trough ipv6 publically or locally. Even the 7681 port is not accessible. 

Network: Mainnet
Reservation id: 11096 
Public ipv6 is 2001:728:1000:401:2026:e1ff:fe06:bf0e

Create script:
```
explorer_url = 'explorer.grid.tf'
network_name = 'digitalyou_network'
node_id = '2gKiAZgeA8C1HsvSYMfdnZYPWNm51xMdYRBNnZxAthWr'

j.clients.explorer.default_addr_set(explorer_url)
me = j.me
zos = j.sal.zosv2

r = zos.reservation_create()

container = zos.container.create(reservation=r,
                    node_id=node_id,
                    network_name=network_name,
                    ip_address='172.20.0.16',
                    public_ipv6=True,
                    flist='https://hub.grid.tf/tobias.3bot/jimbersoftware-digitalyouonline-0.4.flist',
                    interactive=True,
                    cpu=4,
                    memory=4196,
                    disk_size=8192,
                    disk_type='SSD',
                    entrypoint='/bin/bash /entrypoint.sh')

container.environment['pub_key'] = 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCTPaF1W8Fr9QAVtG7h8E+O9Kv+YWlfb1nK9vyxX+gm/27CpTTNJR+CZrhXAOnNoL8F3O2EFUtvzkx04n8gFfYUR1eHuVP3wIKXAF5qhQUwK18IfIPBIl9vvFSsMyGqRbNi4JVQ018IJP4tlejuMaPs8QBkEqMfHQy9FQGYGjzhJtpSgBvkhzrqToVhEunEgHCGDVdP+fJtM2ETGeoOCLD2xr9r+cakq2M3VwOj3teNN34+Mufz/INMIUrsFvIH4pdoMnKQbDfkF2gTLWOl902MOmlGxp/+hbtOxmZ962pNm07pEU9u553Km/KsUOJ54ZJybjQVS1ckB9OPHHA2AiUOWogWrJMPxYD0I9+FmFpvFdanh4+dFPHqt4X1uS/fqPrHgRCn/LfhOj7PHF2HOeB4PvVQf6vniTpxWLZAu6ldR3zyG+p9hUliZFAjDhATuzFUmqQhG+qULBh9Jai5gHNPeLD2KqYw39hPnn8baLj9rgWPRODNdIzdW4EomdgAVqhEXspH9uk+9i4BGyhzWH+gNvoVGYo2LmfQoHBCjobTlo/G/oWBZ4sq0RGi1YfMkDXictfKyRT2hSQu/X3vNJL+GFZRxL0N5upHEGxWwbogrMJoTwgVtmx75ulzu1aDBIn5144+d8aVSP6XEjnea+/1w6PU6NO7HktKxWklyjHgAQ== tobias.chielens@gmail.com'

expiration = j.data.time.epoch + 21600
rid = zos.reservation_register(r, expiration, identity=me, currencies=['FreeTFT'])
```

Terminal output
## tfgrid.workloads.reservation.1
ID: 11096
 - json                : {"description": "", "signing_request_provision": {"signers": [], "quorum_min": 0}, "signing_request_delete": {"signers": [198], "quorum_min": 1}, "containers": [{"workload_id": 1, "node_id": "2gKiAZgeA8C1HsvSYMfdnZYPWNm51xMdYRBNnZxAthWr", "flist": "https://hub.grid.tf/tobias.3bot/jimbersoftware-digitalyouonline-0.4.flist", "hub_url": "", "environment": {"pub_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCTPaF1W8Fr9QAVtG7h8E+O9Kv+YWlfb1nK9vyxX+gm/27CpTTNJR+CZrhXAOnNoL8F3O2EFUtvzkx04n8gFfYUR1eHuVP3wIKXAF5qhQUwK18IfIPBIl9vvFSsMyGqRbNi4JVQ018IJP4tlejuMaPs8QBkEqMfHQy9FQGYGjzhJtpSgBvkhzrqToVhEunEgHCGDVdP+fJtM2ETGeoOCLD2xr9r+cakq2M3VwOj3teNN34+Mufz/INMIUrsFvIH4pdoMnKQbDfkF2gTLWOl902MOmlGxp/+hbtOxmZ962pNm07pEU9u553Km/KsUOJ54ZJybjQVS1ckB9OPHHA2AiUOWogWrJMPxYD0I9+FmFpvFdanh4+dFPHqt4X1uS/fqPrHgRCn/LfhOj7PHF2HOeB4PvVQf6vniTpxWLZAu6ldR3zyG+p9hUliZFAjDhATuzFUmqQhG+qULBh9Jai5gHNPeLD2KqYw39hPnn8baLj9rgWPRODNdIzdW4EomdgAVqhEXspH9uk+9i4BGyhzWH+gNvoVGYo2LmfQoHBCjobTlo/G/oWBZ4sq0RGi1YfMkDXictfKyRT2hSQu/X3vNJL+GFZRxL0N5upHEGxWwbogrMJoTwgVtmx75ulzu1aDBIn5144+d8aVSP6XEjnea+/1w6PU6NO7HktKxWklyjHgAQ== tobias.chielens@gmail.com"}, "secret_environment": >>EMPTYDICT<<, "entrypoint": "/bin/bash /entrypoint.sh", "interactive": true, "volumes": [], "network_connection": [{"network_id": "digitalyou_network", "ipaddress": "172.20.0.16", "public_ip6": true}], "stats_aggregator": [], "farmer_tid": 2147483647, "logs": [], "capacity": {"cpu": 4, "memory": 4196, "disk_size": 8192, "disk_type": 1}}], "volumes": [], "zdbs": [], "networks": [], "kubernetes": [], "proxies": [], "reverse_proxies": [], "subdomains": [], "domain_delegates": [], "gateway4to6": [], "expiration_provisioning": 1597736027, "expiration_reservation": 1597756727, "currencies": ["FreeTFT"]}

    ## tfgrid.workloads.reservation.data.1
     - description         :

        ## tfgrid.workloads.reservation.signing.request.1
         - signers             : []
         - quorum_min          : 0
        

        ## tfgrid.workloads.reservation.signing.request.1
         - signers             : ['198']
         - quorum_min          : 1
        

     - containers          :
        - workload_id: 1    - node_id: 2gKiAZgeA8C1HsvSYMfdnZYPWNm51xMdYRBNnZxAthWr    - flist: https://hub.grid.tf/tobias.3bot/jimbersoftware-digitalyouonline-0.4.flist    - hub_url:
        - environment: {
     "pub_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCTPaF1W8Fr9QAVtG7h8E+O9Kv+YWlfb1nK9vyxX+gm/27CpTTNJR+CZrhXAOnNoL8F3O2EFUtvzkx04n8gFfYUR1eHuVP3wIKXAF5qhQUwK18IfIPBIl9vvFSsMyGqRbN
        i4JVQ018IJP4tlejuMaPs8QBkEqMfHQy9FQGYGjzhJtpSgBvkhzrqToVhEunEgHCGDVdP+fJtM2ETGeoOCLD2xr9r+cakq2M3VwOj3teNN34+Mufz/INMIUrsFvIH4pdoMnKQbDfkF2gTLWOl902MOmlGxp/+hbtOxmZ962pNm07pEU9
        u553Km/KsUOJ54ZJybjQVS1ckB9OPHHA2AiUOWogWrJMPxYD0I9+FmFpvFdanh4+dFPHqt4X1uS/fqPrHgRCn/LfhOj7PHF2HOeB4PvVQf6vniTpxWLZAu6ldR3zyG+p9hUliZFAjDhATuzFUmqQhG+qULBh9Jai5gHNPeLD2KqYw39h
        Pnn8baLj9rgWPRODNdIzdW4EomdgAVqhEXspH9uk+9i4BGyhzWH+gNvoVGYo2LmfQoHBCjobTlo/G/oWBZ4sq0RGi1YfMkDXictfKyRT2hSQu/X3vNJL+GFZRxL0N5upHEGxWwbogrMJoTwgVtmx75ulzu1aDBIn5144+d8aVSP6XEjn
        ea+/1w6PU6NO7HktKxWklyjHgAQ== tobias.chielens@gmail.com"
    }    - secret_environment: >>EMPTYDICT<<    - entrypoint: /bin/bash /entrypoint.sh    - interactive: True    - volumes: []    - network_connection: [{'network_id':
        'digitalyou_network', 'ipaddress': '172.20.0.16', 'public_ip6': True}]    - stats_aggregator: []    - farmer_tid: -    - logs: []    - capacity: {'cpu': '4', 'memory': '4,196',
        'disk_size': '8,192', 'disk_type': 'SSD'} - volumes             : []
     - zdbs                : []
     - networks            : []
     - kubernetes          : []
     - proxies             : []
     - reverse_proxies     : []
     - subdomains          : []
     - domain_delegates    : []
     - gateway4to6         : []
     - expiration_provisioning: 2020/08/18 07:33:47
     - expiration_reservation: 2020/08/18 13:18:47
     - currencies          : ['FreeTFT']
    

 - customer_tid        : 198
 - customer_signature  : 06209436f801ba1c936bb64a1b029da53852b7b9efe98475fcacc7d53724fc66a93a18a2e8d99f253610d7ee6e4e58e6d6749b340bd4917bee5e9a392340e00f
 - next_action         : DEPLOY
 - signatures_provision: []
 - signatures_farmer   : []
 - signatures_delete   : []
 - epoch               : 2020/08/18 07:18:48
 - metadata            : 
 - results             :
    - category: CONTAINER    - workload_id: 11096-1    - data_json: {
 "id": "11096-1",
 "ipv4": "172.20.0.16",
 "ipv6": "2001:728:1000:401:2026:e1ff:fe06:bf0e"
}    - signature: f181eb7e33571ee48b61c25c1d93f56684f653116a50ed7141ae653f9bccda5b7da52db4045941776ec26c1234977d5048ea3290eae78bf9a16d379350dc7003    - state: OK    - message:     - epoch: 2020/08/18 07:20:23

**Comment by m-motawea** [comment]
> but I'm still not able to access the flist trough ipv6 publically or locally. Even the 7681 port is not accessible.

are you unable to reach the assigned ip or you have a problem with corex? that's not clear in the issue.

if you can't reach the assigned ipv6, and you have correct ipv6 config on your local machine and network. then the node would probably be misbehaving.

if it is about corex, as far as I know, you should set `entrypoint = ""` when you use `interactive=True`

**Comment by tobiaschielens** [comment]
I am not able to reach the returned ipv6 address. However, I am able to reach the flist through ipv4. I'm also able to get a  shell through ipv4. 
Using ipv6-test I can see that I have correct access to ipv6.

I've tried putting entrypoint = "" but the result seems to be the same 

Changing from node results in the same issue

**Comment by zaibon** [comment]
I can't ping the public IPV6 either. The container seems to be properly deployed though. So my guess is there is a firewall that prevent traffic to reach the public IPv6 interface of the container.

@tobiaschielens did you had the same problem with nodes from other farms too ?

**Comment by zaibon** [comment]
So from what I can see in your comment, only the IPv6 was unreachable. Usually this means there is a firewall configuration issue at the farm network level that prevent traffic to go through. Did you ever had the same issue on nodes form different farms ?

**Comment by tobiaschielens** [comment]
I had it on node J1Xb2piba1vZM2pSmWP24CPgREnoTce7EuUJysttCyz6 from freefarm 
Reservation id: 11191
as well as the FLCoKMPfuDtbrwdfn2UN7dgKpMVizsbsWu3gYiGcpfRw from GreenEdge-Frankfurt1
reservation id: 11193

Both are accessible through ipv4 but not ipv6

**Comment by zaibon** [comment]
Keep in mind that coreX is not exposed on IPv6. So when you use the `interfactive=True`, you can only access port 7681 through your private network.

**Comment by zaibon** [comment]
After investigation it turns out the problem was the server running in the container was simply not listening on ipv6
