### ISSUE TITLE
Error in presentation macro 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#8]
```
 !!!include("presentations_toc.md")
```
doesn't work correctly as following 
![image](https://user-images.githubusercontent.com/24386802/64344889-a1313200-cfef-11e9-957e-e5d2cadd38b3.png)

**Comment by abom** [comment]
The first error message should be resolved [here](https://github.com/threefoldtech/jumpscaleX_libs/commit/1617633101dd12f7aed03a9e8faa4ca85d6cca56).

The second error message is related to the content itself, raw github urls is not supported.

**Comment by abom** [comment]
It doesn't work for me on chrome (version )
If it only works on latest chrome versions, i think we can [try this plugin](https://github.com/iPeng6/docsify-sidebar-collapse/tree/master/src).

**Comment by Dinaamagdy** [comment]
we need to declare which  things supported and which not 
as now macro return the following error and I think it user input miss .
```
ERROR IN MACRO*** TODO: *1 ***
macro:
include
ERROR:
must be str, not bytes
```

**Comment by abom** [comment]
@Dinaamagdy Which macro? the same one as this file?

**Comment by Dinaamagdy** [comment]
@abom  yes the same

**Comment by abom** [comment]
@Dinaamagdy It's already resolved, can you verify again?

**Comment by hossnys** [comment]
wiki showing slides correctly now :

![Screenshot from 2019-10-24 13-36-41](https://user-images.githubusercontent.com/26298009/67485596-a9f6c980-f66a-11e9-9924-904d127ded6e.png)
![Screenshot from 2019-10-24 13-43-43](https://user-images.githubusercontent.com/26298009/67485597-aa8f6000-f66a-11e9-8e29-29b6275e2123.png)
