### ISSUE TITLE
wikis: update macros to use parameters correctly

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_threebot#81]
- [x]  markdown: to pass the url as parameter instead of parsing the content

- [ ] slideshow: use parameters instead of parsing `[` and `]` by hand (indexing!).

Please update the related docs [here](https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/wikis/macro).

**Comment by serboctor** [comment]
Markdown fixed here https://github.com/threefoldtech/jumpscaleX_libs/commit/fdc89c3822f510f2847caf881c631c81c29fe63e, https://github.com/threefoldtech/jumpscaleX_threebot/commit/74db4992a3c71c19a5889abc3db6833a8ebcd800 and here https://github.com/threefoldtech/jumpscaleX_threebot/commit/34392d625b8f69a8dbb9187385561d18b8fc6540

**Comment by RafyAmgadBenjamin** [comment]
<b> proposed macro to handle the Slideshow </b>
```[[presentation]]
fruits = "www.google.com/presentaions/...."
cars = "www.google.com/presentaions/...."
books = "www.google.com/presentaions/...."
 
[[slideshow]]
presentation =  "fruits"
slide = 4
 
[[slideshow]]
presentation =  "fruits"
slide = 5
 
[[slideshow]]
presentation =  "cars"
slide = "1,4:8,10,12:"
 
[[slideshow]]
presentation =  "books"
slide = "1,5,2,9"
 
[[slideshow]]
presentation =  "books"
slide = "1:"```

Advantages:
- It's more readable. 
- It handles a range of slides in a time which was an issue in the old schema.

**Comment by RafyAmgadBenjamin** [comment]
I have done the basic functionality 
```
fruits = "www.google.com/presentaions/...."
cars = "www.google.com/presentaions/...."
books = "www.google.com/presentaions/...."
 
[[slideshow]]
presentation =  "fruits"
slide = 4
 
[[slideshow]]
presentation =  "cars"
slide = "1,4:8,10"
 
[[slideshow]]
presentation =  "books"
slide = "1,5,2,9"

```
and working now on adding more features like
```
[[slideshow]]
presentation =  "books"
slide = "1:"```
```

**Comment by Pishoy** [comment]
-  verified as docs
https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/docs/wikis/macro/slideshow_v2.md
- access as
https://IP/wiki/testwiki2#/test_presentation_v2
- jsx version 
```
3BOTDEVEL:jsxtesting:jumpscaleX_threebot: git log -1
commit bd8a3f2b38b261453c15fd0b9f5b2e5735d2a7b0 (HEAD -> development, origin/development, origin/HEAD)
Author: gmachtel <30384423+gmachtel@users.noreply.github.com>
Date:   Thu Oct 24 15:10:53 2019 +0200

    Add files via upload

```
