### ISSUE TITLE
wikis: move wiki bottle app to main webinterface

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_threebot#82]
Start wikis by default with the server (as it's now does not load any wikis).

**Comment by hossnys** [comment]
verified 
wikis start by default now with threebot server as appear in threebot logs when starting :
![Screenshot from 2019-10-24 10-17-37](https://user-images.githubusercontent.com/26298009/67466390-4c04ba80-f647-11e9-9797-3e052a301dc3.png)

also can reach in through https://172.17.0.2/wiki
![Screenshot from 2019-10-24 10-19-58](https://user-images.githubusercontent.com/26298009/67466501-75254b00-f647-11e9-9f82-69705170a326.png)
