### ISSUE TITLE
navigation sidebar in wikis doesn't work correctly

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#9]
## Steps 
 - Click  on any element from sidebar 
- try to collapse it 

## Issue 
it will not collapse and can't go to any  element from sidebar again

**Comment by rkhamis** [comment]
@Dinaamagdy I also tried this and it works perfectly fine on chrome. Can you add more details about your setup?

**Comment by abom** [comment]
It doesn't work for me on chrome (version 69)
If it only works on latest chrome versions, i think we can [try this plugin](https://github.com/iPeng6/docsify-sidebar-collapse/tree/master/src).

**Comment by abom** [comment]
After some investigation, this is not a problem, in some sub-folders, you can create a custom sidebar, this custom sidebar will be used anyway instead of the main one.

**Comment by Dinaamagdy** [comment]
can you please  make status of this issue more clear

**Comment by abom** [comment]
@Dinaamagdy Nothing need to be fixed, you can close it.
