### ISSUE TITLE
make sure to test threebot server on each commit for core and threebot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#91]
- [x] test ports captured by threebot
- [x] test gedis starts
- [x] test sonic starts
- [x] test zdb starts
- [x] test package manager actor is loaded
- [x] test package webinterface is loaded
- [x] test package wiki is loaded
- [x] test wiki package

**Comment by AhmedHanafy725** [comment]
Tests added [here](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threebot/wiki/tests/test_wiki.py).
All tests is working except webinterfaces as http client doesn't support insecure requests(issue: https://github.com/threefoldtech/jumpscaleX_core/issues/136).
```
-----------------------------------------------------------------------------
8 tests run in 183.726 seconds. 
1 error (7 tests passed)
```

**Comment by AhmedHanafy725** [comment]
Now all tests are passing and running with each commit on threebot and core.
- Last [run](https://zeroci.grid.tf/repos/threefoldtech%2FjumpscaleX_threebot/development/5db077a273c7c0db30cdae09) on threebot 
- Last [run](https://zeroci.grid.tf/repos/threefoldtech%2FjumpscaleX_core/development/5db02fdc6b6287a8adcdae00) on core

**Comment by despiegk** [comment]
is that realistic?
don't we have too many commits?
on which branch?

**Comment by xmonader** [comment]
Maybe bit too much, but we need it until we have the confidence that everything stabilized in 3bot area and test to be reproducible. And now that we will be working against more controlled environment we will have threebot tests to be running on PRs only.

**Comment by hossnys** [comment]
link for tests is updated up and all are [here](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/zerobot/wiki/tests/test_wiki.py)
they were green and running okay , but for now there is some changes happened which make threebot_server not starting which mentioned [here](https://github.com/threefoldtech/jumpscaleX_core/issues/154)
![Screenshot from 2019-11-04 14-36-35](https://user-images.githubusercontent.com/26298009/68121322-1f3a8800-ff10-11e9-95a4-24f6e89980e8.png)
