### ISSUE TITLE
cloning info_grid in the wikis fail

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#94]
![image](https://user-images.githubusercontent.com/64129/66991204-e43ef480-f0c7-11e9-9959-e1b5d30d5249.png)

```
u 17 08:10:34 DocSite.py           - 583 - docsite                            : verify:doc:readme:/sandbox/code/github
/threefoldfoundation/info_tokens/docs/faq/README.md
Thu 17 08:10:34 DocSite.py           - 583 - docsite                            : verify:doc:token_vesting_schemes:/sand
box/code/github/threefoldfoundation/info_tokens/docs/faq/token_vesting_schemes.md
Thu 17 08:10:34 MarkDownDocs.py      - 150 - markdowndocs                       : load macros:None
Thu 17 08:10:39 GitFactory.py        - 173 - gitfactory                         : None:pull:ssh://git@raw.githubusercontent.com/threefoldfoundation/info_grid.git ->/sandbox/code/raw/threefoldfoundation/info_grid
Thu 17 08:10:39 GitFactory.py        - 245 - gitfactory                         : git clone ssh://git@raw.githubusercontent.com/threefoldfoundation/info_grid.git -> /sandbox/code/raw/threefoldfoundation/info_grid (branch:master)
Thu 17 08:10:39 GitFactory.py        - 287 - gitfactory                         : mkdir -p /sandbox/code/raw/threefoldfoundation;cd /sandbox/code/raw/threefoldfoundation;git -c http.sslVerify=false clone  -b master ssh://git@raw.githubuserc
ontent.com/threefoldfoundation/info_grid.git /sandbox/code/raw/threefoldfoundation/info_grid
Cloning into '/sandbox/code/raw/threefoldfoundation/info_grid'...
ssh: connect to host raw.githubusercontent.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into '/sandbox/code/raw/threefoldfoundation/info_grid'...
```

**Comment by abom** [comment]
The issue is caused by raw links referenced in includes, this commit auto-detect raw links if `raw=True` is not passed.

https://github.com/threefoldtech/jumpscaleX_libs/commit/ec11a122334d3fc3e7ea8f94ab43a39be0aa20c7

**Comment by abom** [comment]
To verify:

Try to load a wiki that has an include with raw links and check if it's working or not

so, start default server

`kosmos -p "j.servers.threebot.local_start_default()"`

Then try loading e.g. our test wiki for example the following document has raw links:

https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/wikis/examples/docs/test_include


Try

```
jsx wiki-load -n test -u https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/wikis/examples/docs
```

And check if for example `https://<container_ip>/wiki/test#/test_include` and check if it includes the raw links or not and

**Comment by siddiquagig** [comment]
Verified

![image](https://user-images.githubusercontent.com/25789724/67377247-6df23480-f596-11e9-8286-0b94327edbcc.png)

![image](https://user-images.githubusercontent.com/25789724/67377295-7f3b4100-f596-11e9-8622-4cb41bcfc07c.png)
