### ISSUE TITLE
bottle servers to ignore the trailing slashes

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#95]
>

For Bottle, /example and /example/ are two different routes [1]. To treat both URLs the same you can add two @route decorators:

```python3
@route('/test')
@route('/test/')
def test(): return 'Slash? no?'
add a WSGI middleware that strips trailing slashes from all URLs:

class StripPathMiddleware(object):
  def __init__(self, app):
    self.app = app
  def __call__(self, e, h):
    e['PATH_INFO'] = e['PATH_INFO'].rstrip('/')
    return self.app(e,h)

app = bottle.app()
myapp = StripPathMiddleware(app)
bottle.run(app=myapp)
```
or add a before_request hook to strip the trailing slashes:
```python3
@hook('before_request')
def strip_path():
    request.environ['PATH_INFO'] = request.environ['PATH_INFO'].rstrip('/')
```

**Comment by abom** [comment]
Added by default to rack server bottle apps https://github.com/threefoldtech/jumpscaleX_core/commit/e3f52f4a390fe23987ffd4368ccb18eaed4769f1

**Comment by hossnys** [comment]
verified 
https://172.17.0.2/chat and https://172.17.0.2/chat/ are the same route and pointing to same page successfully.
![Screenshot from 2019-10-24 08-57-49](https://user-images.githubusercontent.com/26298009/67460942-8d439d00-f63c-11e9-9fe0-6f15ebd3766f.png)

![Screenshot from 2019-10-24 08-58-05](https://user-images.githubusercontent.com/26298009/67460943-8d439d00-f63c-11e9-8c46-c0ca721f777d.png)
