### ISSUE TITLE
myjobs package : workers filter options don't have all status 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#97]
## schema from myjob server 
state** = "NEW,ERROR,BUSY,WAITING,HALTED" (E)

## filter from myjob visualization 
![image](https://user-images.githubusercontent.com/24386802/67023211-b7f49980-f102-11e9-840a-0cad50bb07b9.png) 
 so fillter missing busy state and  error and tghere is no  running state 
![image](https://user-images.githubusercontent.com/24386802/67023534-3fdaa380-f103-11e9-9f70-fd6b26dbb21a.png)

**Comment by Pishoy** [comment]
- still the same issue that filters states (busy and error) are not shown in filter 
![image](https://user-images.githubusercontent.com/21987477/67467242-b36f3a00-f648-11e9-8712-42da4967f25a.png)

- second issue is when press in button halted, does not filter halted states , is shown both Waiting and halted state 
![image](https://user-images.githubusercontent.com/21987477/67467772-a99a0680-f649-11e9-8123-3c8cfbee9c29.png)
