### ISSUE TITLE
wiki: links

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_threebot#98]
Make sure links work (edge cases covered e.g case insensitive filenames, relatives).

**Comment by xmonader** [comment]
I think they need to be resolved into a full url in all cases.

**Comment by abom** [comment]
Added support at https://github.com/threefoldtech/jumpscaleX_libs/commit/7df2adf068c63a38d34fa220d2c0e4cf7b91a11f, https://github.com/threefoldtech/jumpscaleX_libs/commit/1fa5fef960e587bc9bb587f0e3c60eb13a31e045 and https://github.com/threefoldtech/jumpscaleX_libs/commit/3452e3c988ce70af52578b6c621c08c634a0b653.

Updated docs and examples: too https://github.com/threefoldtech/jumpscaleX_threebot/commit/b71e37b97bba49971debd04a19ccca4067d4ac03

**Comment by hossnys** [comment]
verified , full link redirect correctly to the needed file.
