### ISSUE TITLE
jsx: wiki-reload by name

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#99]
we can load wikis using jsx wiki-load -n NAME -u URL

now to reload the content of the wiki after content author update, we should provide `wiki-reload -n NAME`

**Comment by xmonader** [comment]
idea:  we only get the changed files between the current wiki github repo and the pulled one and apply only the difference and push it into bcdb

**Comment by waleedhammam** [comment]
method added at: https://github.com/threefoldtech/jumpscaleX_core/commit/9548342a0f680d2dd0360b36ee72334881729f94

updated docs at: https://github.com/threefoldtech/jumpscaleX_threebot/commit/530f67cd9a1582017a8aa0654464e839b0342398

**Comment by hossnys** [comment]
verified :
steps :
1- editing any local file in wiki repo , i edited this one for sidebar

/sandbox/code/github/threefoldtech/jumpscaleX_threebot/docs/wikis/examples/docs/_sidebar.md

2-then reload wikis

jsx wiki-reload -n examples
3- i found my local changes in wiki page

![Screenshot from 2019-10-23 10-50-18](https://user-images.githubusercontent.com/26298009/67382356-a0e3fa80-f58d-11e9-99c5-725bccecf2c0.png)
